### ISSUE TITLE
App works even when mobile Id policy failed in json validation with additional comma.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#107]
**Describe the bug**
Mobile Id policy had additional comma and failed in json validation but app works seemlessly , Able to download VC & credential status moved to ISSUED from API.

**To Reproduce**
1. Validate policy in json lint 
2. download VC in app

**Current behavior**
App works even when mobile Id policy failed in json validation with additional comma.

**Expected behavior**
Credential status should failed when policy in invalid json.

**Screenshots**
![image (33)](https://user-images.githubusercontent.com/79500509/190623504-53c2abd5-e31e-460c-ba3f-ebf1501800e1.png)
![image (32)](https://user-images.githubusercontent.com/79500509/190623516-c1427b12-a0e2-499c-b806-e93e58055ea2.png)
![image](https://user-images.githubusercontent.com/79500509/190625074-57600b4f-63d9-4f2c-b03c-2b2ff00e3fa3.png)

**Smartphone (please complete the following information):**
- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: 1.2.0.1
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
The mobile ID policy is invalid in both DB and default DB scripts .

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
