### ISSUE TITLE
mobile id - device is stuck in connecting state when two or more devices trying to connect to same relying party simentaniously

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#109]
Describe the bug
The device got in stuck while connecting state when two or more devices trying to connect to same relying party simentaniously

To Reproduce
1. Have device A in request
2. Try to scan device A QR code from two diffrent devices 
3. Only one of the device will be connected 

Current behavior
When two devices trying to connect to same relying party phone, simentaniously one device gets connected succesfully, while second device stuck in connecting state - unable to get the app out of this state until we close the whole app by phone’s home button and reopen the app again

Expected behavior
When two devices trying to connect to same relying party phone, simentaniously one device gets connected succesfully, while second device shouldnt be stuck in connecting state - the app should allow to go back

Screenshot

https://user-images.githubusercontent.com/102220709/190653116-e677b8a3-37fa-456d-99d1-c4c193c98652.mp4

Smartphone (please complete the following information):

Device: Android
Inji app version: [e.g 0.3.0]
Mimoto version: [e.g 1.2.x]
MOSIP Version: 1.2.0.1
Mimoto server: [e.g. https://.....com]
MOSIP server: [e.g. https://...mosip.com]
Additional context
Env: qa5.mosip.net

**Comment by rakhimosip** [comment]
@kneckinator @pmigueld can you please have a look at this issue?

**Comment by jannahadlaon** [comment]
**Tested on:** QA4_io.mosip.residentapp-0.4.0-rc3-dirty-newlogic_20220927_0710.apk - Android

**Resident app build version:** v0.4.0 R3 - Android

**MOSIP server:** QA4

Devices:
Samsung Galaxy A23
Samsung Galaxy A20s
Samsung Galaxy Tab A7 Lite

Issue is still present in the latest build. Kindly see attached video and screenshot for reference. 

**ASSIGNED BACK TO DEV**
@pmigueld @kyanthony

**Screenshots**
![IMG_1830](https://user-images.githubusercontent.com/102940764/192716393-0ee6ede1-09c2-4d5a-93c3-e114a693f230.jpg)
https://user-images.githubusercontent.com/102940764/192716424-5732db98-eefb-4a8a-a580-76633244f4bf.mov

**Comment by santhoshsunder** [comment]
Tested in BLE build (le730bf), Able to connect more than one device, but while sharing VC, the transfer failed in all devices, pragya to add a new ticket in jira, the user should able to connect either only with one device or should be allowed to share VC successfully, both are not occurring hence need a new ticket

**Comment by santhoshsunder** [comment]
this bug is related to GNB, since we moved to BLE, we are closing this bug. commit mentioned below
![image](https://github.com/mosip/inji/assets/102220709/5979ff42-671a-4c31-9cdd-230eb7fab198)
