### ISSUE TITLE
mobile id - Template exceptionServiceError occurring while downloading VC

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#111]
**Describe the bug**
Template exceptionServiceError occurring while downloading VC

**Current behavior**
While trying download VC from both API and APK, we are faced this error and unable to download VC for a while, after a while it started working and able to download VC, I have added the respective screenshot bellow for refrence 

**Expected behavior**
While trying download VC from both API and APK, we should able to download VC without facing any errors

**Screenshot**
![image-20220829-051834](https://user-images.githubusercontent.com/102220709/190655606-51deaaa9-79ea-4b80-a953-455b45dc3a07.png)
![image-20220829-051818](https://user-images.githubusercontent.com/102220709/190655621-30288027-7bcf-44ba-8a65-33c3d0857863.png)

Smartphone (please complete the following information):

Device: Android
Inji app version: [e.g 0.3.0]
Mimoto version: [e.g 1.2.x]
MOSIP Version: 1.2.0.1
Mimoto server: [e.g. https://.....com]
MOSIP server: [e.g. https://...mosip.com]

Additional context
Env: qa5.mosip.net

**Comment by Anushree09-N** [comment]
@rakhimosip Above ticket is raised with recent testing for the packets that was created in arabic and similar jira from resident module too https://mosip.atlassian.net/browse/MOSIP-23696 
is still open.

**Comment by Sujithbn** [comment]
Anushree, please verify and confirm.

**Comment by santhoshsunder** [comment]
Verified this in qa5 env, issue is not occoring any more, iam attaching the screen shot bellow, hense closing this bug

**Screenshot:**
![image](https://user-images.githubusercontent.com/102220709/208157224-a2841067-ccb6-4375-b59e-d541f0430fa9.png)

**Smartphone**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816
-

**Comment by santhoshsunder** [comment]
Verified this issue on QA-5 env, issue is still occuring, we are not able to download credentials when the UIN is created only in arabic language, hense reopening this bug

**Screenshot :**
![image](https://user-images.githubusercontent.com/102220709/209076911-99247d78-4183-4ae5-a2d5-f63a05f48e21.png)

**Arabic UIN:** 2830754082

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1846

**Comment by Anushree09-N** [comment]
Changed the severity to critical as we are blocked with UIN that is created in arabic login from Regclient.

**Comment by Sujithbn** [comment]
@santhoshsunder Please verify and update the latest results.

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, now we able to download VC card with different languages without any error, I am attaching the screenshots and the device details below for reference. Hence closing the bug.
Screenshot: -
![image](https://user-images.githubusercontent.com/124761463/225622866-1247fd62-d332-4a0c-8594-26033540ff43.png)
![image](https://user-images.githubusercontent.com/124761463/225622903-410015e7-ad77-4a5d-9a41-67b57a646bbd.png)
![image](https://user-images.githubusercontent.com/124761463/225622966-c8f689be-909c-4b38-ae77-314d79ec374c.png)
![image](https://user-images.githubusercontent.com/124761463/225623060-340808ba-06cc-442d-917f-942540e9b2b1.png)
Tested in:
Device: Redmi K20 pro
Android Version: 11
BLE version :5.0
Inji app link: https://github.com/mosip/inji/actions/runs/4376878070
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
