### ISSUE TITLE
Mobile id - can't change the field from uin to vid while generating id

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#114]
**Describe the bug**
can't change the field from uin to vid while generating id

**To Reproduce**
1. Open the app
2. Click on add UIN 
3. Add a vid number under uin field and click Add ID 
4. It will show an error as invalid uin
5. Don't clear the vid number that you added and change the field to vid

**Current behavior**
The field is not changing to vid any more

**Expected behavior**
The dropdown feild should allow us to change the feild

**Screenshots**
![image-20220418-085439](https://user-images.githubusercontent.com/102220709/190659418-455732c9-9ccd-4cfd-806d-c4b5ad85ef84.png)
![image-20220418-085331](https://user-images.githubusercontent.com/102220709/190659425-1e1dd64e-6165-4649-83f1-e364761515d4.png)

Device: Android
Inji app version: [e.g 0.3.0]
Mimoto version: [e.g 1.2.x]
MOSIP Version: 1.2.0.1
Mimoto server: [e.g. https://.....com]
MOSIP server: [e.g. https://...mosip.com]

Additional context
Env: qa5.mosip.net

**Comment by rakhimosip** [comment]
Changing the dropdown to VID should clear the error message as well as the value entered previously.

**Comment by Anil-kumar-Majji** [comment]
Now both the error message and the previous value were clearing when the option changed to either UIN or VID in both cases.

**Comment by Anil-kumar-Majji** [comment]
@santhoshsunder I have gone through this bug to solve it. However, by adding a VID number under the UIN field and clicking Add ID, The VC was generated without showing any error. The same happens in the vice-versa case also.

**Comment by Sujithbn** [comment]
This needs to be retested in the latest IOS 16 build

**Comment by santhoshsunder** [comment]
Verified this in qa5 env, issue is not occoring any more, iam attaching the screen recording bellow, hense closing this bug

**Video :**
https://user-images.githubusercontent.com/102220709/208162252-ff1f0248-0035-4dd1-8627-5c944c851e09.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816
