### ISSUE TITLE
Sharing device (Android) is stuck in Connecting.. toast after scanning the QR code in Requesting device (iOS) 

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#116]
**Describe the bug**
After scanning the QR code in iOS, device B (android) is stuck in **`Connecting...`** toast --at the moment we can't share UIN/VIDS from Android to iOS which was possible in the 0.4.0-beta.1

**To Reproduce**
**Device A** (requesting device): iOS
**Device B** (sharing device): Android
1. On device A, go to REQUEST (third icon from left) - verify qr code is displayed and message is correct
2. On device B, go to SCAN (second icon from left) - verify camera is activated
3. On device B, scan QR code displayed on phone A – display “Connecting…” - **SEE ERROR**

- Device: Samsung Galaxy A23, iPhone11
- MOSIP server: QA4

**Screenshots**
![issue3 2](https://user-images.githubusercontent.com/102940764/190960494-d727ef9b-94b9-4727-8386-182e7c9e6d71.jpg)

https://user-images.githubusercontent.com/102940764/190960503-4c34c4bc-a5a6-4f11-babc-a0d691d31c8a.mp4

**Comment by jannahadlaon** [comment]
**Tested on:**
QA4 - 0.4.0 (10.5) -iOS
QA4_io.mosip.residentapp-0.4.0-rc5-dirty-newlogic_20221012_0759.apk]

**Resident app build version:**
v0.4.0 (10.5) - iOS
v0.4.0 RC5

**MOSIP server:** QA4

**Devices:**
Samsung Galaxy A23
iPhone 11

Issue is still present. This has been reported and assigned back to the devs.
@pmigueld @kyanthony @danicaerediano

**Comment by jannahadlaon** [comment]
**Tested on:**
Android - [QA4_io.mosip.residentapp-0.4.0-rc6-newlogic_20221014_1752.apk](https://github.com/idpass/inji/releases/download/0.4.0-rc6/QA4_io.mosip.residentapp-0.4.0-rc6-newlogic_20221014_1752.apk)
iOS - 0.4.0 (11.0)

**MOSIP server:** QA4
**Devices:**
Samsung Galaxy A23
iPhone 11

**WORKS AS EXPECTED**
@pmigueld @danicaerediano @kyanthony

**Comment by santhoshsunder** [comment]
IOS cannot be a verifier in BLE protocol, hence this scenario is not relevant to BLE, closing the bug
