### ISSUE TITLE
"Go to settings" button is unclickable in REQUEST tab when bluetooth is disabled (Android version)

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#117]
**Describe the bug**
The **`Go to settings`** button in the REQUEST tab (third icon from the left) is unclickable when the bluetooth in the requesting device is disabled.

**To Reproduce**
1. Disable bluetooth
2. Open resident app
3. Go to the third icon from the left
4. Click Deny on the toast for turning on bluetooth
5. **SEE ERROR:**  `Go to settings`  button is unclickable

- Device: Samsung Galaxy A23
- Resident app build: 0.4.0 RC1
- MOSIP server: QA4

**Screenshots**
https://user-images.githubusercontent.com/102940764/190957653-7360652a-6d9b-4197-89ab-3b2db5570208.mp4

**Comment by jannahadlaon** [comment]
**Tested on:** QA4_io.mosip.residentapp-0.4.0-rc3-dirty-newlogic_20220927_0710.apk
**Resident app build:** v0.4.0 R3 (android)
**MOSIP server:**QA4
**Devices:**
Samsung Galaxy A23
Samsung Galaxy A20s

**STEPS**
1. Disable bluetooth
2. Open resident app
3. Go to the third icon from the left
4. Click Deny on the toast for turning on bluetooth
5. Click `Go to settings`
6. Enable bluetooth from settings
7. Go back to app
8. Verify that QR code is displayed

**WORKS AS EXPECTED**
@pmigueld @kyanthony

**Comment by santhoshsunder** [comment]
Tested in the BLE build (le730bf), the go-to settings button is clickable in both android and IOS, hence closing the bug
