### ISSUE TITLE
QR code is displayed together with the error message when bluetooth is disabled (Android and iOS version)

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#118]
**Describe the bug**
QR code is displayed together with the error message when bluetooth is disabled (Android version)

**To Reproduce**

**For Android** 
1. Disable bluetooth
2. Open resident app
3. Go to the third icon from the left (REQUEST)
4. Click Deny on the toast for turning on bluetooth
5. Error message is displayed: Please enable Bluetooth to be able to request ID
6. Enable bluetooth - verify that QR code is displayed
7. Go to HOME and disable bluetooth 
8. Go to the third icon from the left (REQUEST)
9. Click Deny on the toast for turning on bluetooth
10. **SEE ERROR**

**For iOS**
1. Open Resident app
2. Go to the third icon from the left (REQUEST)
3. Go to HOME
4. Disable Bluetooth connection in toggle
5. Go to the third icon from the left (REQUEST)
6. **SEE ERROR**

**Device**: 
Samsung Galaxy A23
iPhone 11 

**Resident app build:** 
v0.4.0 R2 (android)
v0.4.0 (7.1)

**MOSIP server:** 
QA4

**Screenshots**
https://user-images.githubusercontent.com/102940764/190963920-943e23d1-66e3-4f28-8fcb-416b2eaced79.mp4
![IMG_1804](https://user-images.githubusercontent.com/102940764/191715587-c213354f-7cb4-4ea6-b5c3-4c37d9dbac8e.png)

**Comment by jannahadlaon** [comment]
**Tested on:** 
QA4 - 0.4.0 (8.0) -iOS
QA4_io.mosip.residentapp-0.4.0-rc3-dirty-newlogic_20220927_0710.apk - Android

**Resident app build version:** 
v0.4.0 (8.0) - iOS
v0.4.0 R3 - Android

**MOSIP server:** QA4

**Devices:**
Samsung Galaxy A23
Samsung Galaxy A20s
iPhone SE
iPhone 11

**WORKS AS EXPECTED**
@kyanthony @pmigueld

**Comment by santhoshsunder** [comment]
Tested in the BLE build (le730bf), the QR code is not displayed with the go-to settings button in both android and IOS, hence closing the bug
