### ISSUE TITLE
Interrupted connection popup was not displayed after clicking reject on device B (iOS -> iOS)

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#120]
**Describe the bug**
After clicking on **Reject** in **Sharing Card** page (Device B), display popup with message about interrupted connection was NOT displayed in Device A

**To Reproduce**

**Prerequisite device A (requesting)**: Bluetooth enabled
**Prerequisite device B (sharing)**: Bluetooth, location, location and camera access: enabled
1. On device A, go to REQUEST (third icon from left)
2. On device B, go to SCAN (second icon from left)
3. On devjce B, scan QR code displayed on device A – display “Connecting…”
4. Device A should display “Connected to device. Waiting for VC…”. Device B should display “Sharing VC” card.
5. On device B, click “Reject”
6. SEE ERROR

**Expected behavior**
Device A should display popup with message about interrupted connection. 

**Device:**
iPhone11 - iOS 15.5
iPhone SE - iOS 15.4

**MOSIP server**: QA4

**Comment by danicaerediano** [comment]
@jannahadlaon this is standard at least in IOS whenever you change an app's settings
tried it on Doctor Anywhere app
https://streamable.com/gi8sb2

**Comment by jannahadlaon** [comment]
**Tested on:** QA4 - 0.4.0 (10.5) -iOS

**Resident app build version:**
v0.4.0 (10.5) - iOS

**MOSIP server:** QA4

Devices:
iPhone SE
iPhone 11

Issue is still present in the build. Assign back to dev.
@pmigueld @danicaerediano @kyanthony

**Comment by jannahadlaon** [comment]
Tested on: QA4 - 0.4.0 (12) -iOS

Resident app build version:
v0.4.0 (12) - iOS

MOSIP server: QA4

Device:
iPhone 11

Issue is still present in the build. Assign back to dev.
@pmigueld @danicaerediano @kyanthony

**Comment by jannahadlaon** [comment]
**Tested on:** QA4 - 0.4.0 (14.1) -iOS

**MOSIP server**: QA4

**Device**:
iPhone 11

**WORKS AS EXPECTED**
@pmigueld @danicaerediano @kyanthony

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
