### ISSUE TITLE
App logged out and asked for log in credentials after enabling the camera access in the settings

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#121]
**Describe the bug**
After Clicking `Allow access to camera` and activating the camera access in the settings, going back to the app results to logging again.

**To Reproduce**

**Prerequisite (sharing device)**: Bluetooth, location, location access: enabled. Camera access: disabled
1. Disable camera access of the app in the settings
2. Open app and go to the second icon from the left (SCAN)
3. Click “Allow access to camera” – taken to settings
4. Allow access to camera
5. Go back to the app 
6. **SEE ERROR**

**Expected behavior**
Go back to app - should land on "SCAN" page with camera displayed

Device:
iPhone11 - iOS 15.5
iPhone SE - iOS 15.4

MOSIP server: QA4

**Screenshots**
https://user-images.githubusercontent.com/102940764/191890799-e2b28d73-64f3-4e47-8fa6-3eb545c268d2.MP4

**Comment by danicaerediano** [comment]
@jannahadlaon this is standard at least in IOS whenever you change an app's settings
tried it on Doctor Anywhere app
https://streamable.com/gi8sb2

**Comment by jannahadlaon** [comment]
Thanks for the update @danicaerediano 
We can close this ticket after noting it in this document: https://docs.google.com/document/d/1KFoDK0s6tmy3erafPzHaSBGn-L7Rb--UW9Y_3KGUMq8/edit#heading=h.una0vopyp7lh
@pmigueld @kyanthony

**Comment by pmigueld** [comment]
@jannahadlaon can you verify this behavior in Android as well? I tested with my Slack app (changed permission and it also restarted). If so we don't need to add this to the doc since it seems to be standard behavior for mobile apps.

**Comment by jannahadlaon** [comment]
@pmigueld i tried it on the Resident app (_see attached video_)
For slack, it did not restart on my end. 

Steps:
1. Go to Settings >> App >> Slack
2. Disable camera access for Slack
3. Open slack
4. Go back to App settings and enable camera access for Slack
5. Switch back to Slack
6. Verified that Slack did not restart 

https://user-images.githubusercontent.com/102940764/193183526-aa2bad0c-2873-4a65-b1ad-a1c3ad721684.mp4

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
