### ISSUE TITLE
Incoming Card's accept and request button is not translated to Filipino

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#122]
**Describe the bug**
Incoming Card's Accept and Request button is not translated to Filipino

**To Reproduce**

**Prerequisites:**
**Change language to "Filipino"**
**Device A (requesting)**: Bluetooth enabled
**Device B (sharing)**: Bluetooth, location, location and camera access: enabled
1. Change language to "Filipino"
2. On device A, go to REQUEST (third icon from left) 
3. On device B, go to SCAN (second icon from left)
4. On device B, scan QR code displayed on device A – verify device B displays “Connecting…”
5. Device A should display “Connected to device. Waiting for VC…”. Device B should display “Sharing VC” card
6. Click “Accept request and choose VC”
7. On device B, select VC to share and click “Share”
8. On device B, text “Sharing…” should be displayed. On device A, “Incoming VC” card should be displayed
9. **SEE ERROR** on device A. 

**Expected behavior**
Incoming Card's accept and request button should be translated to Filipino

**Device**:
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11
iPhone11 - iOS 15.5
iPhone SE - iOS 15.4

**MOSIP server:** QA4

**Screenshots**
![IMG_1806](https://user-images.githubusercontent.com/102940764/191896262-50f7d2b7-af22-427d-85f1-c09538280aea.png)

**Comment by jannahadlaon** [comment]
**Tested on:** QA4 - 0.4.0 (8.0) -iOS
**Resident app build version:** v0.4.0 (8.0) - iOS
**MOSIP server:** QA4
**Device:** iPhone 11

See screenshots for more pages which were not translated to Filipino @pmigueld 

**Screenshots**
![IMG_1848](https://user-images.githubusercontent.com/102940764/193008340-d48e1578-06a1-42f2-b0b1-23ee30772960.png)
![IMG_1849](https://user-images.githubusercontent.com/102940764/193008394-f6e5b045-c255-4e7d-8a02-2fe5b16109b6.png)
![IMG_1850](https://user-ima
![IMG_1851](https://user-images.githubusercontent.com/102940764/193008440-0b9bbd56-e907-4156-bd52-3ccd3a10290d.png)
ges.githubusercontent.com/102940764/193008423-f0ab9ac8-77d2-45d6-98f3-6af9c199cc24.png)

**Comment by jannahadlaon** [comment]
Tested on:
QA4 - 0.4.0 (10.5) -iOS
QA4_io.mosip.residentapp-0.4.0-rc5-dirty-newlogic_20221012_0759.apk]

Resident app build version:
v0.4.0 (10.5) - iOS
v0.4.0 RC5

MOSIP server: QA4

Devices:
Samsung Galaxy A23
Samsung Galaxy A20s
iPhone SE
iPhone 11

Issue is still present in the build. Assign back to dev.
@pmigueld @kyanthony @danicaerediano

**Comment by jannahadlaon** [comment]
Tested on:
QA4 - 0.4.0 (11.0) - iOS
[QA4_io.mosip.residentapp-0.4.0-rc6-newlogic_20221014_1752.apk](https://github.com/idpass/inji/releases/download/0.4.0-rc6/QA4_io.mosip.residentapp-0.4.0-rc6-newlogic_20221014_1752.apk) - Android

MOSIP server: QA4

Devices:
Samsung Galaxy A23
iPhone 11

**WORKS AS EXPECTED** -  _please see additional comments_
@pmigueld @kyanthony @danicaerediano

**Additional Comments** 
- Text overlaps the button when translated to Filipino -> already informed @danicaerediano 

![IMG_2081](https://user-images.githubusercontent.com/102940764/196653744-f54581e1-da6f-4d90-993c-672d5791cfb2.png)
![IMG_2080](https://user-images.githubusercontent.com/102940764/196653767-ae3ff6b6-805d-4a31-8ed0-e3d7bbeba39f.png)

**Comment by jannahadlaon** [comment]
**Tested on:**
QA4 - 0.4.0 (12) - iOS
QA4_io.mosip.residentapp-0.4.0-rc6-15-c83731a-feat_187-use-real-sdk-dirty-newlogic_20221101_1219 - Android

**MOSIP server:** QA4

**Devices:**
Samsung Galaxy A23
iPhone 11

**WORKS AS EXPECTED**
@pmigueld @kyanthony @danicaerediano

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
