### ISSUE TITLE
Unable to download credential displayed UIN not available in Database

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#134]
**Describe the bug**
Took UIN from regclient and irdepo both fails displaying a error **UIN not available in database**

**To Reproduce**
1. Go to resident API's 
2. enter UIN in sendotp request and click on send

**Current behavior**
Displays the error **UIN not available in DB**

**Expected behavior**
Should get success response in sendOtp and we should be able to get the credential.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/192473687-1bc8b7cd-0681-4e01-a4a1-c6a9b8006b12.png)
![Screenshot_2022-09-27-14-02-32-51_fba87592218da393460b8e128d2f49dd](https://user-images.githubusercontent.com/79500509/192475922-b0cee809-3846-4b0e-83a1-531bcd2c1df4.jpg)

**Smartphone (please complete the following information):**
- Device: Android
- MOSIP Version: 1.2.1
- MOSIP server: https://api-internal.qa-121.mosip.net/
- apk : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Additional context**
Regclient UIN : 4607596213
Idrepo UIN : 7186723906

For both UIN we are able to fetch the detials from Idrepo successfully.
![image](https://user-images.githubusercontent.com/79500509/192474530-ca3fd31e-5fd6-4f54-b878-42016276177f.png)

**Comment by LoganathanSekar7627** [comment]
This is now fixed after clearing the old websub subscriptions which was causing the signature failure in websub client with below error:
`{"@timestamp":"2022-09-27T09:22:24.512Z","@version":"1","message":"sessionId - Exception - io.mosip.kernel.websub.api.exception.WebSubClientException - io.mosip.kernel.websub.api.exception.WebSubClientException: KER-WSC-108 --> Error occured while verifing authenticated content :- content signature is not maching\n Request : ServletWebReques`

**Comment by santhoshsunder** [comment]
verified this issue in QA-121 env, issue is not observed any more, hense closing the bug
