### ISSUE TITLE
Unable to download credential displayed invalid input Parameter - mobileNumber

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#135]
**Describe the bug**
Took UIN from regclient and irdepo both fails displaying a error invalid input Parameter - mobileNumber

**To Reproduce**
1. Open apk and authenticate it
2. go to home and click on ADD ID
3. enter the UIN and click on Generate ID

**Current behavior**
Displays the error invalid input Parameter - mobileNumber

**Expected behavior**
should able to download VC without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/192711821-6d812921-77f2-436e-8f4c-223779108236.png)

**Smartphone (please complete the following information):**

Device: Android
MOSIP Version: 1.2.1
MOSIP server: https://api-internal.qa-121.mosip.net/
apk : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Additional context**
Regclient UIN : 2053728061

For the UIN we are able to fetch the detials from Idrepo successfully.
![image](https://user-images.githubusercontent.com/102220709/192712087-2c336384-4966-4604-a071-4ef1444962d3.png)

From Resident API sentOtp request throwed same error:

![image](https://user-images.githubusercontent.com/79500509/192753904-7a24d3b6-cfe1-488c-9594-52c96940c423.png)

**URL**: {{url}}/resident/v1/req/otp
**Request**: {
  "id": "mosip.identity.otp.internal",
  "individualId": "6521320590",
  "metadata": {},
  "otpChannel": ["PHONE", "EMAIL"],
  "requestTime": "2022-09-28T06:20:26.569Z",
  "transactionID": "1234567890",
  "version": "1.0" 
} 

**Response:** 
{
    "id": "mosip.identity.otp.internal",
    "version": "1.0",
    "transactionID": "1234567890",
    "responseTime": "2022-09-28T06:22:04.354Z",
    "errors": [
        {
            "errorCode": "IDA-MLC-009",
            "errorMessage": "Invalid Input Parameter - mobileNumber"
        }
    ],
    "response": null,
    "metadata": null
}

checked all the values in config/identity-mapping.json all are marked to phone.
![image](https://user-images.githubusercontent.com/102220709/192712749-05590d70-e13d-4542-a22b-b2e5dd764313.png)

checked in id schema, we have phone atribute there
[idschema_qa121.txt](https://github.com/mosip/inji/files/9662652/idschema_qa121.txt)

**Comment by LoganathanSekar7627** [comment]
With the new image of credential service there is a coding issue with for a new feature code change, hence reverted back to the old image of credential service to proceed with the testing. The fix is being made separately and tested, which will be available in the new code soon.

**Comment by santhoshsunder** [comment]
verified this issue in QA-121 env, issue is not observed any more, hense closing the bug
