### ISSUE TITLE
VC stuck at loading state in Mobile ID app 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#140]
**Describe the bug**
Unable to download VC from mobile APK, VC stuck at loading state

**To Reproduce**
1.Unlock app
2.Enter valid UIN and request for VC

**Expected behavior**
without any errors we should be able to download VC

**Current behavior**
Unable to download VC, VC stuck in loading state

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/193265621-b7e03032-c3d2-4616-a79f-fd4f5aab1c12.png)

**Smartphone (please complete the following information):**
- Device: android
- MOSIP Version: 121
- MOSIP server: qa-121.mosip.net

**UINs used**
- 5104814723
- 9750139584
- 2057135194

**Additional context**
Able to print VC via API, used the same UINs and verified VC in https://verifiablecredential.io/
![image](https://user-images.githubusercontent.com/102220709/193266146-8369de32-f026-439e-a4ef-5c49549d78c2.png)
![image](http
[qa-121 vc.txt](https://github.com/mosip/inji/files/9684038/qa-121.vc.txt)
s://user-images.githubusercontent.com/102220709/193266211-d9ddbdf4-d2c9-4354-9fa1-b3dc1175d8a0.png)

**Comment by Sujithbn** [comment]
@santhoshsunder @Anushree09-N : Please verify and update the bug

**Comment by Anushree09-N** [comment]
@Sujithbn The issue is resolved now but we would like to know the fix given.

**Comment by santhoshsunder** [comment]
Verified this in qa5 env, issue is not occoring any more, iam attaching the screen shot bellow, hense closing this bug

**Screenshot :**
![image](https://user-images.githubusercontent.com/102220709/208161667-1e633b05-9b28-4747-af16-868955ef5b46.png)

**Smartphone**

- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816
