### ISSUE TITLE
Resident should have a provision to delete VC in the app which is stuck at downloading state.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#141]
**Describe the bug**
Resident should have a provision to delete VC in the app which is stuck at downloading state.

**To Reproduce**
1. Enter valid UIN to get VC -> If VC stuck at downloading state due to service failure 

**Current behavior**
There is no option for a resident to clear/delete VC which is stuck at downloading state which depicts poor UX.

**Expected behavior**
Should have an option to remove the VC from the list if it's stuck in loading state

**Screenshots**
![Screenshot_2022-09-30-17-56-56-98_fba87592218da393460b8e128d2f49dd](https://user-images.githubusercontent.com/79500509/193269511-c99a9612-6d40-4fab-9f18-682db85f07e6.jpg)
![image](https://user-images.githubusercontent.com/79500509/193269823-7962a5f8-825d-421b-b678-8a5465c036bc.png)

**Smartphone (please complete the following information):**
- Device: Android
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by hegdenitin** [comment]
Working as expected. Tested in the latest build. Hence closing the bug.
