### ISSUE TITLE
Using 'Bulk revoke VID' when there's is only one VID in My IDs does not revoke the VID.

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#144]
**Describe the bug**
Using 'Bulk revoke VID' when there's is only one VID in My IDs does not revoke the VID.

**To Reproduce**
1. Generate 2 different VIDs, verify that it is displayed under `My IDs`
2. Go to `My IDs` then click on first VID 
3. Revoke the VID - verify that it has been successfully revoked 
4. Go to `Profile` then select the remaining VID
5. Revoke the VID
6. Got to `My IDs`
7. See error - VID is still in `My IDs`

**Expected behavior**
Bulk revoke VID should function even if only one VID is in My IDs

**Tested on:** MOCK_io.mosip.residentapp-0.4.0-rc3-17-5f7c994-develop-temp-dirty-newlogic_20221003_0914.apk
**Resident app build:** v0.4.0 R3-17-5f7c994 (android)
**MOSIP server:** Mock
**Device:** Samsung Galaxy A23

**Comment by jannahadlaon** [comment]
Tested on:
Android - [MOCK_io.mosip.residentapp-0.4.0-rc6-newlogic_20221014_1757.apk](https://github.com/idpass/inji/releases/download/0.4.0-rc6/MOCK_io.mosip.residentapp-0.4.0-rc6-newlogic_20221014_1757.apk)
iOS - 0.4.0 (11.1)

MOSIP server: Mock

Devices:
Samsung Galaxy A23
iPhone 11

**WORKS AS EXPECTED for both android and iOS**
@pmigueld @danicaerediano @kyanthony

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
