### ISSUE TITLE
Unable to get UIN/VID using AID as we do not see the text box to enter the AID in the app.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#151]
**Describe the bug**
Unable to get UIN/VID using AID as we do not see the text box to enter the AID in the app.

**To Reproduce**
1. Unlock the app
2. click on ADD ID button in home page
3. click on "Don't have your UIN/VID? Get it here " link.

**Current  behavior**
App does not have a textbox to enter the AID number to retrieve the UIN/VID.

**Expected behavior**
We should have a textbox and Get ID buttons to retrieve UIN/VID.

**Screenshots**
![IMG_0036](https://user-images.githubusercontent.com/79500509/195506712-9543474a-84c7-4464-9852-03c6d41a26e9.PNG)

**Smartphone (please complete the following information):**
- Device: iOS
- OS: 15.4.1
- Inji app version: 0.4.1 (5)
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by srikanth716** [comment]
fixed and [PR](https://github.com/mosip/inji/pull/183) raised

**Comment by Sujithbn** [comment]
@Anushree09-N : Please verify and update the bug

**Comment by Anushree09-N** [comment]
Textbox is available now, however feature is still not working we have ticket for the same https://github.com/mosip/inji/issues/185 . Hence closing this bug

![File (9)](https://user-images.githubusercontent.com/79500509/199927607-b8ad99c6-46d0-49ab-b208-ae9b3490b576.jpg)

**Comment by Anushree09-N** [comment]
Textbox is available now, however feature is still not working we have ticket for the same https://github.com/mosip/inji/issues/185 . Hence closing this bug

![File (9)](https://user-images.githubusercontent.com/79500509/199927607-b8ad99c6-46d0-49ab-b208-ae9b3490b576.jpg)
