### ISSUE TITLE
VC's border is not round edged properly 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#155]
**Describe the bug**
VC's card border is not round edged properly 

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home

**Expected behavior**
The downloaded VC card should be with proper rounded edges 

**Current behavior**
Downloaded VC's card border is not round edged properly 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/195576181-e632a8f9-0987-4dc6-9065-6d4d9f0a6e35.png)
![image](https://user-images.githubusercontent.com/102220709/195576250-fdf97885-e3c7-4f2b-aaa5-6f35c2051859.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/actions/runs/3240349594

**Comment by Anil-kumar-Majji** [comment]
@rakhimosip This Issue was solved and submitted raised PR to @gsasikumar  sir.

**Comment by santhoshsunder** [comment]
Verified this issue on QA-5 env, still the edge of the VC card is not proper, still the corner looks blur, hense closing this jira 

**Screenhot :**
![image](https://user-images.githubusercontent.com/102220709/208932319-540f86c4-e843-42e6-b9ac-bc1fce020f71.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1846

**Comment by santhoshsunder** [comment]
Verified this issue in QA-1201-b2 android orange app, in the orange app the issue not observed anymore, in all the pages the VC cards layout is perfect, we will wait till the perple is released and will close this bug once the testing done in it

**Smartphone :**

- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://github.com/mosip/inji/actions/runs/3854157494

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, still in the purple theme the issue is occurring, the edge of the VC card is not proper, still the corner looks blur, hence reopening this bug, I am attaching the screenshot and the device details below for reference.
Screenshots:
![image](https://user-images.githubusercontent.com/124761463/224638172-be5a74bd-6300-42e0-a8f8-e6bab6e9171a.png)
![image](https://user-images.githubusercontent.com/124761463/224638212-86e86cc9-e4d5-46ba-979b-c9c6e1492ddd.png)
![image](https://user-images.githubusercontent.com/124761463/224638244-7099d6fb-3eb9-4bee-8776-39d187d2e841.png)
Tested in;
Device: Redmi 7A
Android Version:10
BLE version :4.2
Inji app version: https://github.com/mosip/inji/actions/runs/4376897206
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Comment by santhoshsunder** [comment]
The purple theme app in both IOS and android, while sharing the selected VC is getting selected differently, the VC is getting big, but in the orange app it is working differently, where a green layout will surround the VC, I am attaching the working video of purple app bellow

Screenshot : 

Tested in :
Device: pixel 6
Android Version: 13
BLE version : 5.2
Inji app version: https://github.com/mosip/inji/actions/runs/4376897206
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Comment by santhoshsunder** [comment]
In the purple theme app, when non of the downloaded VC is binded, when you try to scan the IDP login page, the layout of the error message is not proper, iam attaching a screenshot below for reference

Screenshot : 
https://user-images.githubusercontent.com/102220709/225009403-136f5d17-e3b8-4c42-aa71-55b5bb31265d.mp4

Tested in :
Device: pixel 6
Android Version: 13
BLE version : 5.2
Inji app version: https://github.com/mosip/inji/actions/runs/4376897206
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.ne

**Comment by santhoshsunder** [comment]
In the purple theme, all the text box's font is not proper, when we enter the value in the textbox and highlight it , it is highlighted in dark purple and the font is in black color, which is not visible properly, it happens all the textboxes in the app, please look into this too 

screenshot : 
![image](https://user-images.githubusercontent.com/102220709/227438038-1a7a4c3f-0161-4056-a1da-97554f63a61d.png)

Smartphone :
device : redmi k20 pro
ble : 5.0
android : 11
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079

**Comment by santhoshsunder** [comment]
In the purple app, when the VC tag is filled with a big paragraph, the VC borders are stretched, and the VC tags alignment is also not proper, it should align properly as same as the orange theme, attaching a screenshot below, please look into this

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/227496034-c82f0c4d-4f08-47e3-80b6-2f2e3161ba38.png)
![image](https://user-images.githubusercontent.com/102220709/227496098-69990154-3858-4bf6-973d-838f5faa4f8c.png)

Smartphone :
device : redmi k20 pro
ble : 5.0
android : 11
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/801d8373-bc7b-45c8-862d-8dfa6ab6b9d1)
