### ISSUE TITLE
When a requesting device cancels a sharing request device details are still displayed in the sharing device

### ISSUE THREAD

**Issue by rakhimosip** [mosip/inji#156]
**Describe the bug**
During credential sharing after a connection is established when requesting device cancel's the request, the sharing device continues to display the connection details of the requesting device.

**To Reproduce**
**Steps to reproduce the behavior:**

Device A (resident)
Device B (Relying Party)

- Using A resident scans QR code on B
- On A resident accept's sharing request
- On B -> user clicks Cancel
- On A -> resident still sees sharing ID UI with device B's details

**Current behavior**
On device A resident still sees sharing ID UI with device B's details

**Expected behavior**
On device A resident should be navigated back to the QR code scan UI

**Comment by Anil-kumar-Majji** [comment]
@rakhimosip In the current behaviour, there were showing messages in both the mobiles that were about requesting cancellation.
I think those were mandatory.
# Resident side 
![image](https://user-images.githubusercontent.com/106086523/196106706-ffbd7bed-1340-4ab1-a803-f0d196a0ca08.png)

# Relaying Party side
![image](https://user-images.githubusercontent.com/106086523/196106306-a4c80271-5839-47af-a44a-9e957a2da111.png)

**Comment by Anil-kumar-Majji** [comment]
I couldn't replicate this issue after pulling the recent code from mosip/inji/develop branch. Following are the respective screen records on the resident and relaying party sides.

![Resident side](https://user-images.githubusercontent.com/106086523/201570225-06e6c6aa-22da-4da4-bd33-63119ee47f77.mp4)

![Relaying party side](https://user-images.githubusercontent.com/106086523/201570696-3b0bb0b5-1d7a-42a1-ae4f-70424f1ca405.mp4)

**Comment by santhoshsunder** [comment]
Verified this in qa5 env, issue is not occoring any more, hense closing this bug

**Smartphone**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816
