### ISSUE TITLE
To turn on the bluetooth "Go to setting" button is not working

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#159]
**Describe the bug**
In the request page  "Go to setting" button is not working

**To Reproduce**
1. Turn off the Bluetooth
2. Open mobile app
3. Go to request page
4. The page will ask permission to activate Bluetooth
5. Deny the permission, "Go to settings" button will appear

**Expected behavior**
The button should take us to the mobile Bluetooth settings page 

**Current behavior**
The button is not permorming any action, issue accurs in both purple and orange theme apps

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/195614560-229b0c39-5d5f-487b-8a95-f54df24380fb.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
Purple APK link : https://github.com/mosip/inji/actions/runs/3240349594
Orange APK link : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Comment by srikanth716** [comment]
Fixed in the latest build(https://github.com/mosip/inji/actions/runs/3295104425)

**Comment by Sujithbn** [comment]
This needs to be reverified in IOS 16

**Comment by santhoshsunder** [comment]
Tested this issue in QA-121 env, the issue is not observed any more, hense closing this bug
