### ISSUE TITLE
App is crashing when trying to launch

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#164]
**Describe the bug**
App crashes when we click upon.

**To Reproduce**
1. Install the app from the test flight.
2. click on the app to launch

**Current behavior**
App is crashing when we click on the app to launch.

**Expected behavior**
App should be launched successfully.

**Screenshots**
![IMG_0019](https://user-images.githubusercontent.com/79500509/196350828-74598f63-a7f0-4461-ad33-f94d6ec30666.PNG)

**Smartphone (please complete the following information):**
- Device: iPhone 7
- OS: 15.4.1
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Tested from API able to get VC and same is verified in https://verifiablecredential.io/playground
![image](https://user-images.githubusercontent.com/79500509/196351319-c6ed1ef9-5850-4468-8505-0c9066fd049b.png)
![image](https://user-images.githubusercontent.com/79500509/196351360-12aeefed-e900-4638-89dc-8579318e76c0.png)
[qa121VC.txt](https://github.com/mosip/inji/files/9807029/qa121VC.txt)

**Comment by Sujithbn** [comment]
@MonobikashDas Could you please share the root cause of the issue and assign this to the QA team for closure.

**Comment by Anushree09-N** [comment]
Verified in 1.2.1, qa-121.mosip.net on both iOS and Android. Working as expected able be launch the inji app.
iOS:
![image](https://user-images.githubusercontent.com/79500509/201572018-b71ceed5-34b4-4ec8-9d78-f5c7f75f1b35.png)
Android:
![image](https://user-images.githubusercontent.com/79500509/201572174-7b62b359-b57c-4c70-b2cd-a89e29e83eb4.png)
