### ISSUE TITLE
App crashes when clicked on profile Icon

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#171]
**Describe the bug**
App crashes when clicked on profile Icon

**To Reproduce**
1. Unlock the app
2. click on the profile icon

**Current behavior**
App crashing when we click on profile icon.

**Expected behavior**
Should be able to view profile section

**Screenshots**
![IMG_0057 (2)](https://user-images.githubusercontent.com/79500509/196724239-aa17aa18-24db-4b92-81da-300f967b3eb7.PNG)

**Smartphone (please complete the following information):**
- Device: iPhone 7
- OS: 15.4.1
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
The is observed both on iOS app and android apk
Android apk : https://github.com/mosip/inji/actions/runs/3281982294

**Comment by Sujithbn** [comment]
@MonobikashDas Please share the root cause of the issue

**Comment by Anushree09-N** [comment]
verified in 1.2.1, qa-121.mosip.net on both iOS and Android, Working as expected able to view and access profile section.
iOS:
![image](https://user-images.githubusercontent.com/79500509/201571578-4f2b6981-400f-4cad-a153-35a7de269727.png)
Android: 
![image](https://user-images.githubusercontent.com/79500509/201571634-06893b78-95e0-4c38-accc-cf3de8128732.png)
