### ISSUE TITLE
Notification alert is being triggered when enabling the device to online mode 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#176]
**Describe the bug**
Notification alert is being triggered when enabling the device to online mode 

**To Reproduce**
1. Unlock the app
2. click on qr code option 
3. click on toggle to enable online mode 

**Current behavior**
Notification alert is being triggered when enabling the device to online mode ."Mosip Resident App is having trouble with Google Play services. Please try again ".

**Expected behavior**
Alert message should be revised to convey user to accept the permission to enable the online mode in the app.

**Screenshots**

https://user-images.githubusercontent.com/79500509/196919464-c7022022-b20d-4d65-99c0-785dc141d027.mp4

**Smartphone (please complete the following information):**
- Device: Android
- OS: v11.3
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by Sujithbn** [comment]
This needs to be verified with NL team

**Comment by jannahadlaon** [comment]
**We are not able to replicate this issue.**
@Sujithbn @Anushree09-N 
cc: @kyanthony @pmigueld @danicaerediano 

**Screenshot**
https://user-images.githubusercontent.com/102940764/200817755-b2480d8d-9370-4493-9d0b-0f619d876daa.mp4

**Smartphone (please complete the following information):**
Device: Galaxy A23  - Android
Android version: 12
MOSIP Version: [QA4_io.mosip.residentapp-0.4.0-rc8-newlogic_20221109_1559.apk](https://github.com/idpass/inji/releases/download/0.4.0-rc8/QA4_io.mosip.residentapp-0.4.0-rc8-newlogic_20221109_1559.apk)
MOSIP server: QA4

**Comment by Sujithbn** [comment]
@Anushree09-N Could you please connect with Anthony and reproduce the bug on screen share session.

**Comment by Anushree09-N** [comment]
@jannahadlaon 
**Notification alert is being triggered when enabling the device to online mode ."Mosip Resident App is having trouble with Google Play services. Please try again ".**

- Noticed that if inji is installed on device and if you would have accepted and allowed access permission for above alert message then this pop will not be triggered even if you uninstall and uncheck all the given permission in settings page and reinstall the app. Rather use the device where inji app will be the first time use.

I was able to replicate when I used the device where inji app installation was done for the first time.
CC @rakhimosip @Raginikrishnamurthy @kyanthony

**Comment by Sujithbn** [comment]
As discussed with Anushree, reduced the severity to Major.

**Comment by pmigueld** [comment]
As noted by Anushree above, the popup only shows first time if user did not allow permission for the Google Nearby Messages feature. Looking into the documentation it could be related to [handling user consent](https://developers.google.com/nearby/messages/android/user-consent). 

It was noted in the docs that:
> You can avoid the opt in dialog if your app has been granted the ACCESS_FINE_LOCATION permission and only uses BLE during publishes and subscribes.

I have already tried this in the app but the popup still shows.

**Comment by Sujithbn** [comment]
This issue has been descoped from the beta release.
