### ISSUE TITLE
Unable to delete the numbers in the textbox in AID screen

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#187]
**Describe the bug**
Unable to delete the numbers in the textbox in AID screen

**To Reproduce**
1. unlock the app
2. click on Add ID button in HOME page
3. click on link **Don't have your UIN/VID? Get it here**
4. Enter valid AID
5. click on Get UIN/VID button
6. unable to get UIN due to issue https://github.com/mosip/inji/issues/185
7. Now try to delete the number using delete option from phone's keyboard

**Current behavior**
Unable to delete the numbers in the textbox in AID screen

**Expected behavior**
should be able to clear the number in the text box using delete option in phone's keyboard.

**Screenshots**

https://user-images.githubusercontent.com/79500509/198688525-dfdef4f1-f1a0-46c5-9dca-7c418e63f9a4.MP4

**Smartphone (please complete the following information):**
- Device: iPhone XR 
- OS: 15.4.1
- Inji app version: iOS 0.4.0 (16)-> in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by srikanth716** [comment]
MessageOverlay is added as a popup message which shows "Requesting OTP" at the time of API call in screens\Home\MyVcs\IdInputModal.tsx and screens\Home\MyVcs\GetIdInputModal.tsx to avoid editing the ID number at the time of API call. PR(https://github.com/mosip/inji/pull/255) raised and waiting for code review by @gsasikumar sir

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 
OS: 16.0.2 (20A380)
Inji app version: 0.4.1 (6) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Working as expected , Able to delete AID number 

https://user-images.githubusercontent.com/79500509/208127437-cf97613b-49a3-46fe-a62b-f6544b67d0fb.MP4
