### ISSUE TITLE
VC's border is not round edged properly 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#193]
**Describe the bug**
VC's border is not round edged properly

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home

**Current behavior**
Downloaded VC's card border is not round edged properly

**Expected behavior**
The downloaded VC card should be round edged.

**Screenshots**
![File (2)](https://user-images.githubusercontent.com/79500509/199668462-e32a61c9-fc20-41b0-9285-87ddda5717cf.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Issue registered for Android app https://github.com/mosip/inji/issues/155

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, issue is not occurring, the edge of the VC cards layout is proper, I am attaching the screenshot and the device details below for reference. Hence closing this bug.
Screenshots:
![image](https://user-images.githubusercontent.com/124761463/224664591-2608b9dd-25f4-4f94-a57f-f6ac37fd8e52.png)
![image](https://user-images.githubusercontent.com/124761463/224664707-2b6413ec-1152-48e9-b1ba-57e8f0ab228f.png)
![image](https://user-images.githubusercontent.com/124761463/224664750-2199cb7e-032c-405c-b1ff-ba633a2c38d5.png)
![image](https://user-images.githubusercontent.com/124761463/224664802-5391dd09-cc79-42ac-bfe1-6ce57dba7d2a.png)
![image](https://user-images.githubusercontent.com/124761463/224664879-bad04b6d-8746-49fd-a58e-2b7efefd4cae.png)
![image](https://user-images.githubusercontent.com/124761463/224665735-49f9cfbe-1ae2-4724-a97f-00e321659f0e.png)
![image](https://user-images.githubusercontent.com/124761463/224665839-7386de8e-fdc5-482f-8998-55ae27e4cb0c.png)

Tested in;
Device: iPhone7
OS: 15.6
Inji app version: 0.4.1 (27) in test flight

Device: Galaxy A03 Core
Android Version:11
BLE version :4.2
Inji app version: https://github.com/mosip/inji/actions/runs/4374171157
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Comment by Raginikrishnamurthy** [comment]
issue not occurring any more, refer above screenshots. hence closing the bug.
