### ISSUE TITLE
Renaming VC replacing UIN number in the home screen

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#195]
**Describe the bug**
Renaming VC replacing UIN number in the home screen

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home
4. Open the downloaded VC
5. Click on the edit button on the top right corner
6. Enter the recuird value and click on save
7. Go back to home

Current behavior
Renaming the VC using edit tag replaces the UIN number in the HOME screen.

**Expected behavior**
Renaming VC should not impact UIN number.

**Screenshots**
![File (3)](https://user-images.githubusercontent.com/79500509/199671455-f9d8c6af-aace-4461-86e3-01ea2ccd11ed.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Issue registered for Android app https://github.com/mosip/inji/issues/148

**Comment by rakhimosip** [comment]
@kyanthony @kneckinator
With the new card layout for credentials, the ability to assign a name to a credential does not seem relevant anymore. Can we remove this feature? Or are there any concerns? 
![image](https://user-images.githubusercontent.com/86289097/199954262-66d2c2f8-cb67-4a3f-a602-d43883ae328b.png)

**Comment by kneckinator** [comment]
@rakhimosip with the new card layout, where does the ID type come from? For now, it seems that it is a hard-coded placeholder: https://github.com/mosip/inji/blob/qa-develop/components/VcItem.tsx#L129-L144

What is the plan forward?

**Comment by kneckinator** [comment]
@rakhimosip But the type will be communicated through the credential coming from MOSIP?

**Comment by rakhimosip** [comment]
@kneckinator currently MOSIP is only providing credentials of type 'National Identity Card' (foundational ID). We envision Inji supporting multiple credential types in the future. Depending on the design we adopt those credentials might either come from MOSIP or from another system integrated with Inji. Inji should be able to determine the type either based on the source it calls or based on some attributes in the VC itself.

**Comment by kneckinator** [comment]
Because what I was thinking here @rakhimosip is that for now, using the "edit tag" functionality could update the string displayed under the ID type. If that would not be meaningful, I agree that with this layout the "edit/create tag" functionality has outlasted its purpose.

https://github.com/mosip/inji/issues/195#issuecomment-1303246868 shows where it could be useful though, as I believe these two VCs are VID:s derived from the same UIN. If the ID type would be "National Identity Card" it would be impossible to tell them apart. So some type of user-settable information like a tag "for house loan", "for car lease" etc could be useful.

**Comment by rakhimosip** [comment]
@kneckinator @kyanthony as discussed in today's call ->
- we will retain the ability to add a tag to a credential. NOTE: This will be different from the ID type attribute.
- a tag is an optional attribute the user can associate with a credential if required.
- the way a tag is displayed will be redesigned. Need input from Walid
   - Question: Will tags be displayed in both minimized card view and details view? Evaluate the design options.

**Comment by walidkhouryNL** [comment]
Hello @rakhimosip 
Here are layout suggestions for adding a tag(s) for a VC, 
I prefer the first option, as it is the least disruptive, but that would mean enforcing the 2 columns layout for the information on the card. 

When expanded, the Tags field can sit at the bottom of the card, or right below the "Status" field, depending on how much emphasis we would like to put on the tags. 

![Opt1](https://user-images.githubusercontent.com/68055940/200821585-350eed08-049d-4ab4-b5b5-e5d3e325b5a8.png)
![Opt2](https://user-images.githubusercontent.com/68055940/200821588-5b460701-48cc-4f0c-947d-00570507ae1d.png)
![Opt3](https://user-images.githubusercontent.com/68055940/200821590-15f8cd8c-93fe-429d-b362-27ef567816d6.png)
![Expanded](https://user-images.githubusercontent.com/68055940/200821582-832fab0f-101c-4fdc-b6ad-086a7456929a.png)

Let me know if you have any questions, comments, 
Thanks
cc: @kyanthony

**Comment by rakhimosip** [comment]
Thanks @walidkhouryNL 

Can we look at an option where an icon is used in the minimized view to indicate that there are associated tags and we list the actual tags in the detail view as shown above?

**Comment by pmigueld** [comment]
@walidkhouryNL @rakhimosip currently we can only set one tag in the app. Adding the option for multiple would need more work.

**Comment by rakhimosip** [comment]
@pmigueld that is correct. Multiple tags might be supported in the future and we want to design the UI by taking that also into consideration. Hope this helps.

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-beta.1-10-d68f577-feature_mosip-55-face-matching-newlogic_20221115_1441.apk
iOS: 0.4.1 (1)

**Assign back to dev** 
@pmigueld @kyanthony 

**Devices**:
iPhone 11 - iOS 16.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Additional context**
Issue registered for Android app [#148](https://github.com/mosip/inji/issues/148)

**Comment by jannahadlaon** [comment]
**Tested on:**
iOS: inji 0.4.1 (2) (TestFlight)

**WORKS AS EXPECTED**
CC: @kyanthony @pmigueld @danicaerediano 

**
**Screenshots**
![IMG_2951](https://user-images.githubusercontent.com/102940764/203500917-60293207-d8c8-4828-999b-281cd7f5571d.jpg)
![IMG_2952](https://user-images.githubusercontent.com/102940764/203500930-3391d6f2-569d-4832-bfd6-8a1f361663a6.jpg)


**Additional context**
Issue registered for Android app https://github.com/mosip/inji/issues/148

**Comment by jannahadlaon** [comment]
**Tested on:**
iOS: inji 0.4.1 (3) (TestFlight)

**WORKS AS EXPECTED**
CC: @kyanthony @pmigueld @danicaerediano

**Additional context**
Issue registered for Android app https://github.com/mosip/inji/issues/148

**Screenshots**
https://user-images.githubusercontent.com/102940764/203712115-12bcf68b-5029-4688-bd2a-e4cda01e352f.mov
![IMG_2980](https://user-images.githubusercontent.com/102940764/203712135-07cbb28f-f4d0-4874-a366-ba76a379086a.jpg)
![IMG_2981](https://user-images.githubusercontent.com/102940764/203712145-25304c5c-82e5-4b91-8d77-9938dac8912f.jpg)

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (4) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Able to add tag name and UIN details are retained without modification. Hence closing bug
![image](https://user-images.githubusercontent.com/79500509/207299124-cc427da0-ceaf-46e8-a561-118a02439837.png)
![image](https://user-images.githubusercontent.com/79500509/207299157-b04a0f89-9d26-4ff3-bc44-4fd76924374a.png)
 

https://user-images.githubusercontent.com/79500509/207299298-629e90e8-a682-48c8-a907-7b5739355b05.MP4
