### ISSUE TITLE
RTL is not handled in inji app

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#197]
**Describe the bug**
The app is not properly capable of left to right,when Arabic language is selected

**To Reproduce**
1. Click the app icon 
2. Authenticate it and get in 
3. In the right top , the language filter will be available 
4. Click it and slect Arabic language

**Expected behavior**
The whole app should convert its layout to left to right as the language preference

**Current behavior**
few of the feilds where left to right and remaining are right to left, the whole app looks cracked 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/199674690-967b33df-6c2e-432c-a111-564307363815.png)
![image](https://user-images.githubusercontent.com/102220709/199674712-8d5b637b-afe8-44ea-8a0b-3623ac2a9466.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Comment by kyanthony** [comment]
Duplicate tickets with [https://github.com/mosip/inji/issues/203](url)
Already worked on.
@rakhimosip @Sujithbn

**Comment by rakhimosip** [comment]
@kyanthony QA team has raise one bug each for iOS and android.  https://github.com/mosip/inji/issues/203 is for iOS and this is for android.

**Comment by santhoshsunder** [comment]
Tested this issue in the QA5 env, we are still able to recreate this issue in few places eg. version of the app is still in english, in history feild few elements still in english, iam attaching the screenshot down bellow, and reopeninng the bug

**screenshots:**
![image](https://user-images.githubusercontent.com/102220709/206623793-238daddc-5c39-4267-8f88-ccf65bcfa33a.png)
![image](https://user-images.githubusercontent.com/102220709/206623802-bed67695-073e-40bf-b582-c8c5e1955d03.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736

**Comment by santhoshsunder** [comment]
**Verified on:**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
APP link; https://mosip.atlassian.net/browse/DSD-1816

came across few elements are still not in RTL format yet, adding those screen shot bellow
![image](https://user-images.githubusercontent.com/102220709/208116831-f9aba993-d497-47db-b775-131437dffa17.png)
![image](https://user-images.githubusercontent.com/102220709/208117049-eeb378da-9dc8-445b-be2a-f761e1eb5d62.png)
![image](https://user-images.githubusercontent.com/102220709/208117091-2e352208-48a0-4d50-99a4-608f96c69bb8.png)
![image](https://user-images.githubusercontent.com/102220709/208117113-ef533a11-2e55-4cd3-8742-7ec37e120313.png)

Due to above listed issue we will keep this ticket open.

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

@rakhimosip I noticed that the text in the attached photos below was not translated. Can we get these translated so that our team can properly modify it to RTL?
@kyanthony @pmigueld @danicaerediano @Anushree09-N 

**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12

![IMG_3272](https://user-images.githubusercontent.com/102940764/208600981-5afde188-d76e-47dc-aa40-96983f80383f.png)
![IMG_3273](https://user-images.githubusercontent.com/102940764/208600983-4ebcea39-d7fa-4f59-9018-96adf6c191d2.png)
![IMG_0081](https://user-images.githubusercontent.com/102940764/208600986-4770a417-dc8b-4c0c-b0f6-2f24168302b5.jpg)
![IMG_0082](https://user-images.githubusercontent.com/102940764/208600989-cc298ba6-c795-4ad8-a972-d1689353daec.PNG)
![IMG_0082](https://user-images.githubusercontent.com/102940764/208600974-c33b4aff-6cf1-44ff-b177-1d4baea81729.jpg)

**Comment by rakhimosip** [comment]
@jannahadlaon @pmigueld all the texts displayed on the UI should come from locale files.

**Comment by santhoshsunder** [comment]
Verified this issue in QA5 env, as mentioned in the above comment, we are able to to see some feilds are still not converting into RTL, iam attaching those screen shots bellow

**Screenshot :**
Genrate VC text box still work in LTR
![image](https://user-images.githubusercontent.com/102220709/209087467-1131e7c5-e651-4b0f-a9a5-ca989bec753b.png)
Reason for sharing text box and the reason for sharing message in LTR
![image](https://user-images.githubusercontent.com/102220709/209087657-4e14c028-a00a-41b8-ac86-0f721fdb09f3.png)
Pop up messages still come in LTR
![image](https://user-images.githubusercontent.com/102220709/209088036-13371851-6ac4-4766-bbe8-3cf07a6eb8dc.png)
![image](https://user-images.githubusercontent.com/102220709/209088047-6999ec37-d9ac-44b0-ad30-3901fc1ba465.png)

**Smartphone :**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by jannahadlaon** [comment]
**Tested on:** 
Android build: COLLAB_io.mosip.residentapp-0.4.1-rc5-19-7f194bd-fix_mosip-324-325-reset-user-consent-newlogic_20230106_1727.apk


**WORKS AS EXPECTED** 
@pmigueld @kyanthony @santhoshsunder  @Anushree09-N 

**Devices:**
Samsung Galaxy A23 - Android 12

**Screenshot**
![Screenshot_20230110-160921_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/211499346-095063b6-df41-4d4c-973c-1fb7f4f9201c.jpg)
![Screenshot_20230110-161103_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/211499351-a463201d-7be0-4f04-8136-a02698817b07.jpg)
![Screenshot_20230110-161301_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/211499355-170908b5-7c16-4fb2-b6cc-4088193705b5.jpg)
![Screenshot_20230110-161309_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/211499359-d77a835c-3116-42b9-8686-28234452473c.jpg)
![Screenshot_20230110-161356_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/211499363-ea845fe2-f215-4b84-bf7c-93b9b3341986.jpg)

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, still issue is occurring, we are able to see some fields are still not converting into RTL, I am attaching the screenshot and the device details below for reference.
Screenshots:
![image](https://user-images.githubusercontent.com/124761463/224304103-ab967531-3884-4028-a677-3f4f17e84246.png)
![image](https://user-images.githubusercontent.com/124761463/224304132-2d093b98-e148-4d4a-b1e2-661ce8e5359d.png)
![image](https://user-images.githubusercontent.com/124761463/224304153-3d4c6f20-c500-4fcb-9c63-8dfe96b19e55.png)
![image](https://user-images.githubusercontent.com/124761463/224304187-a12e2eb1-cf4f-4854-ab94-48f619541f11.png)
![image](https://user-images.githubusercontent.com/124761463/224304225-7c0f779b-c847-4476-a118-c4549747add7.png)
![image](https://user-images.githubusercontent.com/124761463/224304267-5b2ecebe-44fb-4c94-99cc-e0c67fce334c.png)
![image](https://user-images.githubusercontent.com/124761463/224304325-913a0810-c7e4-4b20-8924-6357575dcfde.png)
![image](https://user-images.githubusercontent.com/124761463/224304355-abba3644-c1a0-471c-a6c1-3930034063b6.png)
![image](https://user-images.githubusercontent.com/124761463/224305312-2a7b8765-fa4c-4f3c-bd89-92fb6d1b07e7.png)
![image](https://user-images.githubusercontent.com/124761463/224305638-10b5cdc0-f971-4d96-8685-ef2d4aff4448.png)
![image](https://user-images.githubusercontent.com/124761463/224305881-5f2949bb-fb35-4787-b3c3-882152c50c81.png)
Tested in;
Device: Galaxy A03 core
Android Version:11
BLE version :4.2
Inji app version: https://github.com/mosip/inji/actions/runs/4376897206

Device: Redmi K20 pro
Android Version: 11
BLE version :5.0
Inji app link: https://github.com/mosip/inji/actions/runs/4376878070
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26837

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed on jira https://mosip.atlassian.net/browse/INJI-34, hence closing on Github.
