### ISSUE TITLE
The full name attribute is missing in the VC detailed view

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#199]
**Describe the bug**
The full name attribute is missing in the VC detailed view

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home
4. Open the downloaded VC card

**Expected behavior**
All the atribute should be listed properly

**Current behavior**
The full name attribute is missing in the VC detailed view

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/199676034-300eb601-d675-4504-9c30-a55cdd729654.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Comment by rakhimosip** [comment]
@santhoshsunder @Anushree09-N why is this a critical bug? Please elaborate

**Comment by santhoshsunder** [comment]
verified this issue in qa5 env, the issue is not observed any more, we are able to see full name attribute in the detailed view, adding the screen show bellow, hense closing the jira 

**Screenshot :**
![image](https://user-images.githubusercontent.com/102220709/209547919-8b4343a9-c0d2-4e14-ba65-4089c37fa9f1.png)

**Smartphone :**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
APP link; https://mosip.atlassian.net/browse/DSD-1816
