### ISSUE TITLE
VC detailed layout is not ocupying the spaces properly 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#200]
**Describe the bug**
VC card's detailed layout is not ocuppying the spaces properly 

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home
4. Open the downloaded VC card

**Expected behavior**
The layout should occupy the available space properly 

**Current behavior**
The layout is aligned to the left and all the values where listed one by on by bellow, even the is enough space in the right as shown in the bellow screen shot

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/199678087-75f43ccc-8a1e-4dda-8f1c-c6a344aba1ad.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Comment by rakhimosip** [comment]
@santhoshsunder @Anushree09-N please add the format of the address from the underlying policy to the bug description.

**Comment by srikanth716** [comment]
In VcDetails.tsx the text is restricted by the flex, fixed it by changing it to padding-right so that it can occupy the right side space. PR(https://github.com/mosip/inji/pull/263) raised and code review has to be done by @gsasikumar sir

**Comment by santhoshsunder** [comment]
Verified this issue in qa-1201-b2 env, the issue is not observed any more, the attributes using the space perfectly in the detailed view, iam attaching the screen shots here, hense closing this bug

**Screenshot :** 
![image](https://user-images.githubusercontent.com/102220709/212893648-8444b118-79f5-4257-ba46-5600521adbed.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://github.com/mosip/inji/actions/runs/3854157494
