### ISSUE TITLE
When the VC card is downloading it has two id type's attribute 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#202]
**Describe the bug**
When the VC card is downloading it has two id type's feild attribute 

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home

**Expected behavior**
The secont id type should be named as UIN

**Current behavior**
There is a second ID type attribute instead of UIN atribute as shown in the bellow screenshot 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/199718409-5d114532-6ab2-4d52-ab6d-71bf9e163b7c.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Comment by rakhimosip** [comment]
The label can be 'ID'

**Comment by santhoshsunder** [comment]
Verified this issue in qa-1201-b2 env, the issue is not observed any more, we are seeing only one ID type now while the VC is loading, iam attaching the screen shots here, hense closing this bug

**Screenshot :** 
![image](https://user-images.githubusercontent.com/102220709/212894115-a1a4d1dd-81f8-468d-9f54-635d055d9d3d.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://github.com/mosip/inji/actions/runs/3854157494
