### ISSUE TITLE
RTL is not handled in inji app

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#203]
**Describe the bug**
RTL is not handled in inji app

**To Reproduce**
1. unlock the app
2. In the right top click on language icon
3. select Arabic language

**Current behavior**
RTL is not handled in inji app.

**Expected behavior**
Arabic language should be rendered from right to left.

**Screenshots**
![File (4)](https://user-images.githubusercontent.com/79500509/199886249-419f69d6-d4f4-4383-9001-50f192c2ceb3.jpg)
![File (5)](https://user-images.githubusercontent.com/79500509/199886939-b33204fc-6471-4f9f-94d3-b6212abee975.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Issue registered for Android app https://github.com/mosip/inji/issues/197

**Comment by Sujithbn** [comment]
This will be included in the Facenet android New logic build( ).

**Comment by jannahadlaon** [comment]
**Tested on:** 
Android: QA4_io.mosip.residentapp-0.4.1-beta.1-10-d68f577-feature_mosip-55-face-matching-newlogic_20221115_1441.apk
iOS:  0.4.1 (1)

**STEPS**

1. Open the app
2. In the right top click on language icon
3. select Arabic language

**WORKS AS EXPECTED** 
@kyanthony @pmigueld @danicaerediano 

**Screenshots**
![Screenshot_20221116-123209_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202093165-332a7c2c-556d-408f-aac4-5e5eff791255.jpg)

![Screenshot_20221116-123226_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202093176-aed17a53-ccb6-4c5e-afaf-0ad7fa83542b.jpg)

**Comment by jannahadlaon** [comment]
Tested on:
iOS: Inji version 0.4.1 (12)

**WORKS AS EXPECTED** 
some of the texts were not translated but in RTL format
@pmigueld @santhoshsunder @kyanthony @Anushree09-N 

**Devices**
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot** 
![IMG_3727](https://user-images.githubusercontent.com/102940764/213962479-972dde4e-289c-461f-8097-f1fc5682f636.png)
![IMG_3728](https://user-images.githubusercontent.com/102940764/213962485-15040173-ab33-424c-b78c-cd2e0efc62e0.png)
![IMG_3729](https://user-images.githubusercontent.com/102940764/213962486-70b678de-930e-4101-98d0-043c98303ba8.png)
![IMG_3730](https://user-images.githubusercontent.com/102940764/213962488-7a3488a4-d572-45fe-8c89-b42da9659f72.png)
![IMG_3732](https://user-images.githubusercontent.com/102940764/213962501-6382fea7-51d6-4980-a404-b251fd4f3357.png)
![IMG_3733](https://user-images.githubusercontent.com/102940764/213962506-b178b921-d054-4c97-943a-efb1bfbc6c11.png)
![IMG_3734](https://user-images.githubusercontent.com/102940764/213962508-e4df357a-72dc-482a-811c-b391cc29440e.png)
![IMG_3731](https://user-images.githubusercontent.com/102940764/213962526-f5faf8dc-edf6-43ef-b7a7-c2a0aff9de89.png)

**Comment by Raginikrishnamurthy** [comment]
@Sujithbn Please check if the PR is merged in develop branch and re-assign to qa.

**Comment by santhoshsunder** [comment]
In the RTL the app is not having a header highlighted on the home page, please look into the screen recording for reference, since it is not highlighted, we are not able to make out, on which screen we are , it is occurring in both themes, please look into this 

Screenshot : 
https://user-images.githubusercontent.com/102220709/227505681-6910bd4c-353a-49c4-936d-6690711ce173.mp4
https://user-images.githubusercontent.com/102220709/227505769-d084acd9-d3d0-42e3-86af-87100a2149c3.mp4

Smartphone :
device : redmi k20 pro
ble : 5.0
android : 11
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26839

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed on jira https://mosip.atlassian.net/browse/INJI-36, hence closing the same on Github.
