### ISSUE TITLE
Full name attribute is missing in detail view screen of VC 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#205]
**Describe the bug**
Full name attribute is missing in detail view screen of VC 

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home
4. Open the downloaded VC

**Current behavior**
Full name attribute is missing in detail view screen of VC 

**Expected behavior**
Detail view of VC screen should contain Full Name details.

**Screenshots**
![File (6)](https://user-images.githubusercontent.com/79500509/199888465-cdf34775-394f-4a91-9497-2103a7676d28.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Issue in Android is registered https://github.com/mosip/inji/issues/199

**Comment by srikanth716** [comment]
Missing full name label element in the VcDetails.tsx, fixed in the android platform by [PR] (https://github.com/mosip/inji/pull/239) #239 and merged.

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Able to get Full name in detail view screen

![image](https://user-images.githubusercontent.com/79500509/209326889-56535128-e4fc-416c-b9a9-b3325832dfa6.png)
