### ISSUE TITLE
MOSIP logo trimed in VC card

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#206]
**Describe the bug**
MOSIP logo is trimmed in both VC's preview in home page and VC detail view page.

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. view VC

**Current behavior**
MOSIP logo trimed in VC card.

**Expected behavior**

**Screenshots**
![File (8)](https://user-images.githubusercontent.com/79500509/199907450-56ce4fda-8eb9-447e-9e15-4f21b7c10006.jpg)
![File (7)](https://user-images.githubusercontent.com/79500509/199907453-a19e71ad-2c7e-449c-be28-23f447a51234.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
https://github.com/mosip/inji/issues/142

**Comment by Anil-kumar-Majji** [comment]
The above issue was rectified by adjusting logo styles in module defaultTheme.tsx. Check the expected logs in the below screenshots.
[In Detailed VC-card](https://user-images.githubusercontent.com/106086523/203773892-c314beee-5983-4019-9b18-9df7076d2bfd.png)
[In VC-cards](https://user-images.githubusercontent.com/106086523/203773987-147ca27c-07a7-46f1-ac33-f343985ad245.png)
