### ISSUE TITLE
Unable to download VC with the UIN which is created in Arabic language.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#208]
**Describe the bug**
Unable to download VC with the UIN which is created in Arabic language.

**To Reproduce**
**prerequisite** : have a UIN created with English and Arabic.

1. Open app and head to home page
2. Click on add ID
3. Enter a valid UIN and click on generate VID
4. Enter the OTP

**Current behavior**
Unable to download VC with the UIN which is created in Arabic language. Displayed "Template exceptionServiceError" 

**Expected behavior**
We should be able to download VC even with the UIN that is created in Arabic language.

**Screenshots**
![File (10)](https://user-images.githubusercontent.com/79500509/199934192-460a23a4-6bbc-4fcc-909b-b6167bc9be5c.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Issue in Android is registered https://github.com/mosip/inji/issues/196

**Comment by rakhimosip** [comment]
@Anushree09-N is the VC generation happening from the API?

**Comment by Anushree09-N** [comment]
@rakhimosip The issue is from API 
![image](https://user-images.githubusercontent.com/79500509/200227249-544c6506-e984-4990-b072-4b8b21e17cbe.png)
Non-RTL language VC download is working

**Comment by LoganathanSekar7627** [comment]
@Anushree09-N , from the ID Repo the preferredLang seems to be not having the languageCode (ara) but the language name itself like (Arabic). It needs correction from registration client to send the language code only in preferred language attribute instead of language name.

**Comment by LoganathanSekar7627** [comment]
@MonobikashDas , thanks, I got it. We already started working on fixing this. Will update you once done.

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot. 
![image](https://github.com/mosip/inji/assets/88436594/d78719d5-d280-41b6-b64d-f6e34ea38db0)
