### ISSUE TITLE
Unable to download credential with infant's UIN.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#209]
**Describe the bug**
Unable to download credential with infant's UIN.

Prerequisite
Infant's UIN from Reg client **6340627136**

**To Reproduce**
1. unlock the app
2. click on Add ID 
3. Enter UIN and click on Generate ID
4. Enter otp

**Current behavior**
Displayed error as **"Unsupported Authentication Type for child-otp"**.

**Expected behavior**
If Otp Authentication is not supported for a child then app should provide other possible authentication types.

**Screenshots**
![File (11)](https://user-images.githubusercontent.com/79500509/200132028-4b67aa83-7784-48d9-9216-51e03194b35d.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by rakhimosip** [comment]
@Anushree09-N @Raginikrishnamurthy 
There is a child auth filter that is configured in `https://github.com/mosip/mosip-config/blob/develop-v3/id-authentication-default.properties`

```
# Child Auth Filter configurations
ida.child-auth-filter.factors.denied=otp,bio
ida.child-auth-filter.child.max.age=5
```
This config controls what auth types are allowed for age groups i.e infant in this case.

**Comment by Anushree09-N** [comment]
Verified in: 
iPhone 8
iOS version 16
BLE 5.0
Inji app version: 0.4.1 (25) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Current configured value is below:
https://github.com/mosip/mosip-config/blob/qa-1201-B2/id-authentication-default.properties

# Child Auth Filter configurations
ida.child-auth-filter.factors.denied=otp,bio
ida.child-auth-filter.child.max.age=5

Working as expected , below is the test data with results :

![image](https://user-images.githubusercontent.com/79500509/224709922-602730e5-b75e-4090-8474-0255cbfbc807.png)

Tested results have been discussed with @rakhimosip too.

Commit Id of verified app: 
![image](https://user-images.githubusercontent.com/79500509/224631346-2f3d9305-f3ec-4c86-92f3-5389c6d742f6.png)

![image](https://user-images.githubusercontent.com/79500509/224631485-d9a1fd70-249a-4055-bfef-bb55b1531ebb.png)
