### ISSUE TITLE
Message should be revised in sharing device while waiting for receiver to accept VC

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#210]
**Describe the bug**
Message should be revised in sharing device while waiting for receiver to accept VC

**Prerequisite** Download VC in sharing phone.

**To Reproduce**
1. unlock the app
2. Open qr code in  requesting device.
3. Open scanner in sharing device and scan the qrcode
4. select VC and click on Accept and share button
5. Incoming VC in requesting phone and message pop-up button in sharing phone.

**Current behavior**
When receiver is about to Accept incoming VC the sharing device will have message saying "It's taking a while to share VC. **There could be a problem with the connection**".

**Expected behavior**
Though both devices are connected message is misleading user saying "There could be a problem with the connection". which should be revised.

**Screenshots**
![IMG_0044 (1)](https://user-images.githubusercontent.com/79500509/200172649-4de8403e-f1cf-484c-b4d0-76eed8567463.jpg)

**Smartphone (please complete the following information):**

- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by pmigueld** [comment]
What should the revised message be?

**Comment by Anushree09-N** [comment]
Unable to verify the ticket due to linked issue https://github.com/mosip/inji/issues/370

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

Message was revised to: _**It's taking a while to establish connection. Is the other device open for connection?**_ (refer to screenshot)
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. unlock the app
2. Open qr code in requesting device.
3. Open scanner in sharing device and scan the qrcode
4. select VC and click on Accept and share button
5. Incoming VC in requesting phone and message pop-up button in sharing phone.

**Test devices:**
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12

**Screenshot** 
![Screenshot_20230103-162903_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/210323968-74116854-9f1e-4ecd-a3e3-693d40b7e0b9.jpg)

**Comment by pmigueld** [comment]
Here's a screenshot of updated text:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1631922/212618717-2710d8e4-63f0-4da1-aac4-295f8fbf1a73.png">

**Comment by rakhimosip** [comment]
@kyanthony one question -> Is the text 'ID' in the above message coming from the 'VC Label' set in the Profile section? If yes, then the above message works for this scenario.
CC @Anushree09-N @pmigueld @jannahadlaon

**Comment by pmigueld** [comment]
@rakhimosip yes, it is the `vcLabel` set in profile.

**Comment by rakhimosip** [comment]
Thanks, @pmigueld 

@Anushree09-N @jannahadlaon the above message looks good. Please test and close.

CC @kyanthony

**Comment by jannahadlaon** [comment]
tested on:
iOS: Inji version 0.4.1 (12)

**WORKS AS EXPECTED**
@pmigueld @santhoshsunder @kyanthony 

**Steps** 

1. unlock the app
2. Open qr code in requesting device.
3. Open scanner in sharing device and scan the qrcode
4. select VC and click on Accept and share button
5. Incoming VC in requesting phone and message pop-up button in sharing phone.

**Devices**
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot** 

![IMG_0106](https://user-images.githubusercontent.com/102940764/213958351-e6e695a9-489a-4d3e-b56a-b4e3f2e536e0.png)
![IMG_0107](https://user-images.githubusercontent.com/102940764/213958384-d0bf1175-0d5b-44fe-8761-9f4c1aee787e.png)

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, we getting appropriate popup message when we sharing VC and waiting for receiver for receiving VC card. I am attaching the screenshot and the device details below for reference. Hence closing the bug.

Screenshots:
![image](https://user-images.githubusercontent.com/124761463/228244391-a3a2b790-65ea-4e72-ac07-847151884ebd.png)
![image](https://user-images.githubusercontent.com/124761463/228244429-94a71429-b45c-4be9-89c1-2b4b01e2f00f.png)
![image](https://user-images.githubusercontent.com/124761463/228244458-d31b58fb-7776-4c45-b8f2-e1ad1fe4e6dd.png)
![image](https://user-images.githubusercontent.com/124761463/228244495-9773224b-1df4-42d8-9db3-1b1b2bb3f272.png)
![image](https://user-images.githubusercontent.com/124761463/228244582-5f78315e-cfa5-49b4-b4ec-d74b621d61ee.png)
![image](https://user-images.githubusercontent.com/124761463/228244633-015fdbae-62a3-41e3-9c4f-4accbc668db6.png)
![image](https://user-images.githubusercontent.com/124761463/228244682-19bbcbc8-419d-41ed-8ed1-2e473a364d69.png)

Tested in:
Device: iPhone7 
OS: 15.6.1
Inji app version: 0.4.0 (32) in test flight

Device: Samsung Galaxy A03 core
Android Version: 11
BLE version : 4.2
Inji app link: https://github.com/mosip/inji/actions/runs/4511525622
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
