### ISSUE TITLE
VC is not in card format in sharing device.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#211]
**Describe the bug**
VC is not in card format in sharing device.

**Prerequisite** Download VC in sharing phone.

**To Reproduce**
- unlock the app
- Open qr code in requesting device.
- Open scanner in sharing device and scan the qrcode
- select VC to share

**Current behavior**
VC is not in card format in sharing device.

**Expected behavior**
VC is expected to be in card format

**Screenshots**
![IMG_20221106_193014 (2)](https://user-images.githubusercontent.com/79500509/200176040-af5582bf-dd66-41d1-b27f-8197e0079372.png)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Same issue is observed in cross platform sharing as well.

**Comment by Anil-kumar-Majji** [comment]
@rakhimosip @Anushree09-N Once confirmed with the following image. Is that ok?
[Screenshot](https://user-images.githubusercontent.com/106086523/200817387-402c9e12-39f3-4239-8126-054d3027690b.jpg)

**Comment by Anil-kumar-Majji** [comment]
@santhoshsunder Before rectifying, I could able to replicate this issue in android too.  Here I also adjusted the border radius.

**Comment by Anil-kumar-Majji** [comment]
@rakhimosip I raised PR and sent you it in slack.

**Comment by Anil-kumar-Majji** [comment]
I fixed this issue in android by adding style, and border-radius at the ImageBackground component in the singleVcItem.tsx module. [Screenshot](https://user-images.githubusercontent.com/106086523/200817387-402c9e12-39f3-4239-8126-054d3027690b.jpg)

Related PR:- https://github.com/mosip/inji/pull/237/files

**Comment by Anushree09-N** [comment]
1. Verified in:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (10) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

![image](https://user-images.githubusercontent.com/79500509/212623593-2e786903-bf2d-4191-9fdd-45182ca46327.png)

Working as expected in iOS devices.

2. Verified in:

Device : iPhone 8 & OnePlus Nord 2
OS: 16.0.2
Inji app version: 0.4.1 (10) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Android is sharing
iOS is requesting

Working as Expected in cross platform sharing device , VC is in card format.

![image](https://user-images.githubusercontent.com/79500509/212636176-b3e649c9-414b-4b53-b50b-adef28a670d6.png)
