### ISSUE TITLE
Radio button should be removed if device contain single VC while sharing. 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#212]
**Describe the bug**
Radio button should be removed if device contain single VC while sharing. 

**Prerequisite** Download VC in sharing phone.

**To Reproduce**
- unlock the app
- Open qr code in requesting device.
- Open scanner in sharing device and scan the qrcode
- select VC to share

**Current behavior**
Even when device has single VC, while sharing radio button is added on VC for selection. 

**Expected behavior**
Radio button should be removed if device contain single VC while sharing.

**Screenshots**
![IMG_20221106_202615](https://user-images.githubusercontent.com/79500509/200178213-fd18fca3-f610-480f-b5b6-119361a71cc4.png)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Same issue is observed in cross platform sharing as well.

**Comment by Anil-kumar-Majji** [comment]
The above Issue was fixed by removing check-box reacthnative-element in singleVcItem.tsx module. Now radio button will be not there while sharing if, single VC in device.
[Respective Screenshot](https://user-images.githubusercontent.com/106086523/201587064-71259c59-c9e8-474b-bf68-249ac48f6c47.jpg)

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Able to replicate the issue

![image](https://user-images.githubusercontent.com/79500509/209316308-657ad79b-96c3-436b-aea5-d96209c6767b.png)

**Comment by Anil-kumar-Majji** [comment]
@Anushree09-N The above Issue was rectified, Raised and shared respective PR #392

**Comment by Anuranjan14** [comment]
As per the latest design radio button is removed instead we have vc selection via green border on selected vc. Hence closed.
Attaching the screenshot for the reference:
![image](https://user-images.githubusercontent.com/120705365/227172862-f3d34432-6e2f-4fff-a6c4-9be37133fb06.png)
