### ISSUE TITLE
While Downloading VC field Name is displayed as idtype instead of UIN.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#213]
**Describe the bug**
While Downloading VC field Name is displayed as idtype instead of UIN.

**To Reproduce**
- Unlock the app
- click on add ID and Enter UIN
- Click on Get ID and Back to Home button

**Current behavior**
While Downloading VC field Name is displayed as idtype instead of UIN.

**Expected behavior**
Field Name should be retained as UIN only.

**Screenshots**
![File (13)](https://user-images.githubusercontent.com/79500509/200178932-7f26e243-62a7-4f15-8d4b-fdfa69fb7809.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Issue in Android is registered https://github.com/mosip/inji/issues/202

**Comment by srikanth716** [comment]
Changing the Label Idtype as Id until the VC downloads in VcItem.tsx, Once the VC gets downloaded then based on the policy if there is a UIN then it will change to UIN, or if there is a VID then it will change to VID. PR(https://github.com/mosip/inji/pull/254)  raised waiting for code review by @gsasikumar sir

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

The field name is change to ID 

![image](https://user-images.githubusercontent.com/79500509/209323031-7d34887b-7165-4020-8fb0-0d3840b48011.png)

![image](https://user-images.githubusercontent.com/79500509/209323065-a1fdede2-20fc-44f6-94c6-a5516b2bcca8.png)
