### ISSUE TITLE
Message popup in sharing device is still retained even after successful VC share.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#214]
**Describe the bug**
Message popup in sharing device is still retain even after successful VC share.

**To Reproduce**
1. open qrcode in Android app (online mode)
2. open scanner in iOS device
3. scan the qrcode from iOS device 
4. After establishing connection choose VC and click on AcceptRequest button .
5. will see incoming VC in requesting device and message popup in sharing device.
6. Accept the incoming VC -> success message popup is displayed.
7. Check the message pop in sharing device

**Current behavior**
Message popup in sharing device is still retain even after successful VC share.

**Expected behavior**
As VC share was success the message pop up in share device should dismiss the message automatically.

**Screenshots**
![File (14)](https://user-images.githubusercontent.com/79500509/200224701-d4d1a1e7-3acb-4825-b67f-80fce403f341.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone7 & Samsung Galaxy A03
- OS: 15.4.1 & 11
- Inji app version: 0.4.0 (16) in test flight , untagged-1-c464508-qa-develop-dirty-newlogic. 
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net
- APK link : https://github.com/mosip/inji/actions/runs/3287270987

**Comment by Anushree09-N** [comment]
@rakhimosip this issue is inconsistent and also observed that if sharing device dismiss the message automatically the history is being captured otherwise we will not see history for sharing . Hence increasing the severity to critical

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-beta.1-10-d68f577-feature_mosip-55-face-matching-newlogic_20221115_1441.apk

**Assign back to dev**
Issue is still present

**STEP:**

1. Open qrcode in Android app (online mode)
2. Open scanner in iOS device
3. Scan the qrcode from iOS device
4. After establishing connection choose VC, and share.
5. Accept the incoming VC in the receiving device -> success message popup is displayed -> CLICK ANYWHERE ON THE RECEIVING DEVICE before the success message is displayed on the sharing device.
6. See error on the sharing device.

@kyanthony @pmigueld @danicaerediano

**Devices:**
Samsung Galaxy A23 - Android 12
iPhone 11 - iOS 16.1.1

**Screenshot**
https://user-images.githubusercontent.com/102940764/203754150-1bdd1465-16a7-46ad-908f-d0c3aa405be9.mov

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

**Issue is still present** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Open qrcode in Android app (online mode)
2. Open scanner in iOS device
3. Scan the qrcode from iOS device
4. After establishing connection choose VC, and share.
5. Accept the incoming VC in the receiving device -> success message popup is displayed -> CLICK ANYWHERE ON THE RECEIVING DEVICE before the success message is displayed on the sharing device.
6. See error on the sharing device.



**Test devices:**
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12

**Screenshot**

https://user-images.githubusercontent.com/102940764/208400237-d1fa5c1d-310a-4a51-aabc-83cbb5dc2091.MOV

![FullSizeRender](https://user-images.githubusercontent.com/102940764/208398998-4f5d8e85-bc84-4a26-96d1-4441389c780d.jpg)

**Comment by Anushree09-N** [comment]
Verified on:
Device : iPhone 8 & OnePlus Nord 2
OS: 16.0.2
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Working as expected , Displayed success pop up message on sharing device .

https://drive.google.com/file/d/1OecsTUI_bcmTYBWnhbvx1RrQlS2a0lc3/view?usp=share_link
