### ISSUE TITLE
Mobile id API credentials are not moving to printing state

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#215]
**Describe the bug**
The Mobile id API credentials are not moving to printing state

**To Reproduce**
1. Send OTP from api
2. Request credentials 
3. check the credential's status

**Expected behavior**
The credentials status should moved to printing state, without any errors 

**Actual output:**
Credential are not moving to printing state

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/200230283-f8bccf1a-eebd-424e-bfdf-44cdc3ac6aae.png)
![image](https://user-images.githubusercontent.com/102220709/200230294-86fabb7f-80ec-4528-8a76-7e79dc9d47fb.png)

**Environment details**
- MOSIP Version: 1.2.1
- MOSIP server: qa-1.2.1.mosip.net

**Additional context**
{
  "id": "string",
  "request": {
    "additionalData": {},
    "credentialType": "vercred",
    "encrypt": true,
    "encryptionKey": "abc123",
    "individualId": "8435214723",
    "issuer": "mpartner-default-print",
    "otp": "111111",
    "recepiant": "",
    "sharableAttributes": [],
    "transactionID": "1234567890",
    "user": "string"
  },
  "requesttime": "2020-12-02T04:48:08.731Z",
  "version": "v1"
}
End point : https://api-internal.qa-121.mosip.net/resident/v1/req/credential/status/18fd4b71-2fbc-43bb-9c84-842551df4aa8

**Comment by Sujithbn** [comment]
@LoganathanSekar7627 : Please add the root cause of the issue and share the updates to QA team

**Comment by LoganathanSekar7627** [comment]
@Anushree09-N , as the same issue is not reproduced to me. Please check now if it is reproducing for you now and let me know.

**Comment by LoganathanSekar7627** [comment]
@Anushree09-N No root cause found . I tested with the same UIN, and is working fine now. Could be some environment issue by then. Please let me know if this reproduces, so that immediately I will get the logs to see the root cause.

**Comment by santhoshsunder** [comment]
Verifed this issue in QA5 env, the issue is not observed anymore, now the credentials are moving to printing state, hense closing the jira
