### ISSUE TITLE
The ADD ID getting stacked down by the VC card

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#216]
**Describe the bug**
The ADD ID button getting stacked down by the VID card

**To Reproduce**
1. Open the app 
2. Authenticate it and enter to the home screen
3. Download more than four VC cards

**Current behavior**
The VC cards stacked one by one bellow and making the ADD id butto go to the bottom of the screen, to access the button it takes us to scroll down to access it

**Expected behavior**
as from the previous version of the app the ADD id button used to hover over the screen, so it wont get stacked down

**Screenshots**
https://user-images.githubusercontent.com/102220709/200237741-6c39ad60-b1ab-42fa-9faf-1b36a260fcaa.mp4

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/actions/runs/3287270987

**Comment by rakhimosip** [comment]
@kyanthony can we get Walid's input on this?

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-beta.1-10-d68f577-feature_mosip-55-face-matching-newlogic_20221115_1441.apk

**STEPS**
1. Open the app
2. In the right top click on language icon
3. select Arabic language

**WORKS AS EXPECTED**
@kyanthony @pmigueld @danicaerediano

**Devices:**
Samsung Galaxy A23 - Android 12

**Screenshot**

https://user-images.githubusercontent.com/102940764/202134692-d4607a9e-8960-4129-81aa-f47721a0fb29.mp4

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk

**WORKS AS EXPECTED**
@kyanthony @pmigueld @danicaerediano

**Devices:**
Samsung Galaxy A23 - Android 12

**Screenshot**
https://user-images.githubusercontent.com/102940764/203737335-a0a093a1-28d8-496d-99a4-9ab21976000b.mp4

**Comment by santhoshsunder** [comment]
verified this issue in qa5 env, the ADD ID is hovering over the screen, and working as expected, iam attaching the screen shot bellow, and closing this bug 

**screenshot :**
![image](https://user-images.githubusercontent.com/102220709/206623145-d6178216-1be4-4fc8-b4f2-39dc9562123a.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736
