### ISSUE TITLE
The ADD ID button is getting stacked down by the VC card

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#217]
**Describe the bug**
The ADD ID button is getting stacked down by the VC card

**To Reproduce**

1. Unlock the app 
2. Go to  home screen and click on Add ID
3. Download more than four VC cards

**Current behavior**
The VC cards stacked one by one below and pushing the ADD id button to the bottom of the screen, to access the button it takes us to scroll down.

**Expected behavior**
As from the previous version of the app the ADD id button used to hover over the screen, so it wont get stacked down

**Screenshots**
https://user-images.githubusercontent.com/102220709/200237741-6c39ad60-b1ab-42fa-9faf-1b36a260fcaa.mp4

**Smartphone (please complete the following information):**

- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Issue in Android is registered https://github.com/mosip/inji/issues/216

**Comment by rakhimosip** [comment]
@kyanthony can we get Walid's input on this?

**Comment by jannahadlaon** [comment]
**Tested on:**
iOS: 0.4.1 (3)

**WORKS AS EXPECTED**
@kyanthony @pmigueld @danicaerediano

**Devices:**
iPhone 11 - iOS 16.1

**Screenshot**

https://user-images.githubusercontent.com/102940764/203737462-48c45bf3-8f14-469b-b2c6-5499a374cc84.MP4

**Comment by Anushree09-N** [comment]
Verified on: 

- **Device**: iPhone 8 & iPhone 11
- **OS**: 16.0.2 (20A380), 15.6.1
- **Inji app version**: 0.4.1 (4) -> Testflight
- **MOSIP Version:** 1.2.0.1
- **MOSIP server**: qa5.mosip.net

Add ID button does not move down as with credential download working as expected, hence closing the bug. 

https://user-images.githubusercontent.com/79500509/207039411-8459e58e-e9d2-4944-83cd-7a04ee165bd6.MP4
