### ISSUE TITLE
No Message to User for asking to enable the internet while sharing VC between devices.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#218]
**Describe the bug**
No Message to User for asking to enable the internet while sharing VC between devices.

**Prerequisite** IOS device A (requesting): Bluetooth enabled
**Prerequisite** IOS device B (sharing): Bluetooth, location and camera access: enabled
VC is downloaded and stored in sharing device and (internet is disabled on both device)

**To Reproduce**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

**Current behavior**
Device B stucks in connecting state while Device A shows up the qrcode screen.

**Expected behavior**
Should intimate the User to enable the internet connection and try again.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/200246350-10d5fa70-c205-4948-9ebb-455a51fa2f77.png)
![image](https://user-images.githubusercontent.com/79500509/200246391-2d747707-e736-4b8d-966f-211098aafb7a.png)

**Smartphone (please complete the following information):**

- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by Anushree09-N** [comment]
Able to replicate issue for below scenario's

1. **Request and share VC between IOS devices**

-    Prerequisite IOS device A (requesting): Bluetooth enabled
-    Prerequisite IOS device B (sharing): Bluetooth, location and camera access: enabled
-    VC is downloaded and stored in sharing device and (internet is disabled on requesting device)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

2. **Request and share VC between IOS devices**

- Prerequisite IOS device A (requesting): Bluetooth enabled
- Prerequisite IOS device B (sharing): Bluetooth, location and camera access: enabled
- VC is downloaded and stored in sharing device and (internet is disabled on sharing device)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

3. **Request and share VC between 2 Android devices [online mode]**

- Prerequisite Android device A (requesting): Bluetooth enabled
- Prerequisite Android device B (sharing): Bluetooth, location and camera access: enabled
- VC is downloaded and stored in sharing device and (internet is disabled on both devices)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

4. **Request and share VC between 2 Android devices [online mode]**

- Prerequisite Android device A (requesting): Bluetooth enabled
- Prerequisite Android device B (sharing): Bluetooth, location and camera access: enabled
- VC is downloaded and stored in sharing device and (internet is disabled on requesting device)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

5. **Request and share VC between 2 Android devices [online mode]**

- Prerequisite Android device A (requesting): Bluetooth enabled
- Prerequisite Android device B (sharing): Bluetooth, location and camera access: enabled
- VC is downloaded and stored in sharing device and (internet is disabled on sharing device)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

6. **Request VC from IOS device and share VC from Andriod device**

- IOS device A (requesting): Bluetooth enabled 
- Prerequisite Android device B (sharing): Bluetooth, location and camera access: enabled 
- VC is downloaded and stored in sharing device and (internet is disabled on both devices)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

7. **Request VC from IOS device and share VC from Andriod device**

- IOS device A (requesting): Bluetooth enabled 
- Prerequisite Android device B (sharing): Bluetooth, location and camera access: enabled 
- VC is downloaded and stored in sharing device and (internet is disabled on requesting devices)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

8. **Request VC from IOS device and share VC from Andriod device**

- IOS device A (requesting): Bluetooth enabled 
- Prerequisite Android device B (sharing): Bluetooth, location and camera access: enabled 
- VC is downloaded and stored in sharing device and (internet is disabled on sharing devices)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

9. **Request VC from Android device[online mode] and share VC from IOS device**

- Prerequisite Android device A (requesting): Bluetooth enabled
- Prerequisite IOS device B (sharing): Bluetooth, location and camera access: enabled
- VC is downloaded and stored in sharing device and (internet is disabled on both the device)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

10. **Request VC from Android device[online mode] and share VC from IOS device**

- Prerequisite Android device A (requesting): Bluetooth enabled
- Prerequisite IOS device B (sharing): Bluetooth, location and camera access: enabled
- VC is downloaded and stored in sharing device and (internet is disabled on requesting device)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

12. **Request VC from Android device[online mode] and share VC from IOS device**

- Prerequisite Android device A (requesting): Bluetooth enabled
- Prerequisite IOS device B (sharing): Bluetooth, location and camera access: enabled
- VC is downloaded and stored in sharing device and (internet is disabled on sharing device)
**steps:**
1. Open qrcode in device A
2. Open qrcode scanner in device B
3. Scan the qrcode from device B

**Comment by kyanthony** [comment]
For retesting by @Anushree09-N

**Comment by jannahadlaon** [comment]
**Tested on:**
INJI 0.4.1 (16)

**WORKS AS EXPECTED**  @pmigueld @kyanthony @Anushree09-N 

**STEPS**
1. Disable internet connection
2. Open app
3. Go to Request tab (third icon from the left)
4. Message below should be displayed instead of QR code:
`Please connect to the internet to enable Online sharing mode`
5. Enable internet connection
6. Verify that QR code appears

**Devices**
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot**

https://user-images.githubusercontent.com/102940764/215397104-088f6abf-4aed-4cb6-9057-f8a55f1fc31b.MOV

https://user-images.githubusercontent.com/102940764/215397163-1c9e4c25-8d02-48ab-b798-da0d417001cb.MOV

**Comment by Anushree09-N** [comment]
This ticket cannot be verified as we are currently running with BLE build . And moreover this issue is specific to Google Nearby sharing and iOS being in online mode for VC share.

Hence ticket can be put on hold

**Comment by Raginikrishnamurthy** [comment]
As GNB is descoped, closing the bug.
