### ISSUE TITLE
Even though requesting credential with VID still we see UIN detials in the app

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#219]
**Describe the bug**
Even though requesting credential with VID still we see UIN detials in the app

**To Reproduce**
1. unlock the app
2. click on Add ID
3. Enter VID number and click on Generate ID
4. VC card will be downloaded 
5. View the downloaded card.

**Current behavior**
Even though requesting credential with VID still we see UIN detials in the app

**Expected behavior**
As VC is requested using VID number the details should be of VID and should not disclose UIN number.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/200252329-b3f847be-f869-428a-be88-ab2c3fd3ff27.png)
![image](https://user-images.githubusercontent.com/79500509/200257107-f9a60de7-0ba5-4aad-bcab-5d2c8ebec9c0.png)

**Smartphone (please complete the following information):**
- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

VID used: 6104608493798138

**Comment by rakhimosip** [comment]
@Anushree09-N after https://mosip.atlassian.net/browse/MOSIP-23106, it is possible to support a VID attribute in policy as well. 

Also, refer to https://github.com/mosip/inji/issues/94
The label in the app UI is determined by the values returned in the VC based on the policy and not by what the user enters as input.

**Comment by Anushree09-N** [comment]
Verified in:

wallet: 
iPhone 8
iOS version 16
BLE 5.0

Verifier:
Redmi 7A 
Android 10
BLE 4.2

Inji app version: 0.4.1 (25) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

Verified features:
-Download VC with VID
-Sharing VC
-Share VC with Selfie
-wallet binding
-QR code login
-History
![image](https://user-images.githubusercontent.com/79500509/224631736-17a7bf5c-ef14-4053-bfd9-2b89a49e2c7a.png)


UIN details are replaced with VID after adding VID attibute in policy and restarting credential service.

Commit Id of verified app: 
![image](https://user-images.githubusercontent.com/79500509/224631346-2f3d9305-f3ec-4c86-92f3-5389c6d742f6.png)

![image](https://user-images.githubusercontent.com/79500509/224631485-d9a1fd70-249a-4055-bfef-bb55b1531ebb.png)
