### ISSUE TITLE
Even though requesting credential with VID still we see UIN detials in the app

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#220]
**Describe the bug**
Even though requesting credential with VID still we see UIN detials in the app

**Steps to Reproduce**
1. unlock the app
2. click on Add ID
3. Enter VID number and click on Generate ID
4. VC card will be downloaded
5. View the downloaded card.

**Current behavior**
Even though requesting credential with VID still we see UIN detials in the app

**Expected behavior**
As VC is requested using VID number the details should be of VID and should not disclose UIN number.

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/200261734-2689d89a-3a99-4074-ab4a-bec03d983d56.png)
![image](https://user-images.githubusercontent.com/102220709/200261755-778c438a-cfdd-4a4d-993b-cdffd2faaaeb.png)

Smartphone (please complete the following information):
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/actions/runs/3287270987

**Comment by rakhimosip** [comment]
@Anushree09-N @santhoshsunder after https://mosip.atlassian.net/browse/MOSIP-23388, it is possible to support a VID attribute in policy as well.

Also, refer to https://github.com/mosip/inji/issues/94
Now the label in the app UI is determined by the ID attribute returned in the VC based on the policy and not by what the user enters as input.

**Comment by Anuranjan14** [comment]
Verified the issue and now VID can be seen in downloaded VC . Hence closing.
![image](https://user-images.githubusercontent.com/120705365/224705435-c159e600-1ce8-4c59-a321-0ffbdcb04017.png)

Device details:
Device: Redmi K20 pro
OS: Android 11
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

CommitId:
![image](https://user-images.githubusercontent.com/120705365/224705592-67e65895-69ef-432f-a81f-945f7c305acf.png)
![image](https://user-images.githubusercontent.com/120705365/224705645-23c29295-dafc-4123-b34d-8cf47b867bb7.png)
