### ISSUE TITLE
Unable to see the version of the app in profile icon due to smaller screen length.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#221]
**Describe the bug**
Unable to see the version of the app in profile icon due to smaller screen length.

**To Reproduce**
1. unlock the app
2. click on profile icon 4 th option

**Current behavior**
As screen size is smaller the version of the is not visible.

**Expected behavior**
Should have scroll bar which can help us to scroll and view the version details.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/200286104-4f2d3aad-ca78-4169-8d25-6cf719a9020a.png)

**Smartphone (please complete the following information):**
Device: iPhone7 
OS: 15.4.1
Inji app version: 0.4.0 (16) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
