### ISSUE TITLE
Rejection of VC request by sharing device should be notified to requesting device.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#222]
**Describe the bug**
Rejection of VC request by sharing device should be notified to requesting device.

**To Reproduce**
 Device A --> Requesting
 Device B --> Sharing

1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. connection is established, Now select VC to share and AcceptRequest.
5. From Device A reject the incoming VC by clicking on Reject button

**Current behavior**
Rejection of VC request by sharing device should be notified to requesting device.

**Expected behavior**
Should notify rejection of VC request by sharing device to requesting device.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/200494020-0fc07a38-2c66-4adc-af24-1f5b22e698c4.png)

https://user-images.githubusercontent.com/79500509/200494110-4b308351-bdb4-4d89-a237-043b329f6818.MP4

**Smartphone (please complete the following information):**
Device: iPhone7 & iPhone XR
OS: 15.4.1
Inji app version: 0.4.0 (16) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Additional context**
Same issue is observed in cross platform sharing as wel.

**Comment by jannahadlaon** [comment]
We are not able to replicate this issue.
@Sujithbn @Anushree09-N
cc: @kyanthony @pmigueld @danicaerediano

**Screenshot**
![20221114_161357 - Trim - frame at 0m37s](https://user-images.githubusercontent.com/102940764/201610076-78617abb-3e75-42d6-ace4-0f027ddfa302.jpg)

**Tested on**: QA4 - 0.4.0 (14.1) -iOS
**MOSIP server**: QA4
**Device**:
Sharing device: iPhone 11
Requesting: Samsung Galaxy A23

@pmigueld @danicaerediano @kyanthony

**Comment by Sujithbn** [comment]
@Anushree09-N Could you please connect with Anthony and reproduce the bug on screen share session.

**Comment by jannahadlaon** [comment]
**Tested on:** 
Android: QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk
iOS: inji 0.4.1 (3) (TestFlight)

**Can replicate issue when conditions are:**
1. Scanning device is Android
2. Receiving device is iOS
3. No reason for sharing is added
4. No ID is selected

**Screenshots** 
Video of issue:
https://user-images.githubusercontent.com/102940764/204211422-e367aa06-da7c-4f52-b152-247d8538c6c0.mov

Videos without issues (reason for sharing and ID was selected)
https://user-images.githubusercontent.com/102940764/204211466-3664d105-3a9f-4803-9880-1f19bc3a8815.mov
https://user-images.githubusercontent.com/102940764/204211503-8bd5b1ff-d3af-41b1-8974-146cf7cfc129.mov

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

**Issue is still present ** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:
Can replicate issue when conditions are:

1. Scanning device is Android
2. Receiving device is iOS
3. No reason for sharing is added
4. No ID is selected

**Test devices:**
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12

**Screenshot** 
https://user-images.githubusercontent.com/102940764/210321222-926f7c98-f2d5-4945-bec7-ef5fadb455cc.mp4

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: [io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc8/io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk)iOS TestFlight -Inji  0.4.1 (12)


**WORKS AS EXPECTED** for  `iOS <->iOS`, `iOS <-> Android`
but **issue is still present** when sharing from `Android <->iOS`
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. Share an ID
2. Scan the QR code on the requesting device
3. Click `Reject `in the sharing device
4. Requesting device should display a popup that sharing was disconnected

**Devices**
Samsung Galaxy A23 - android 12
Samsung Galaxy A20s - android 11
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot**

https://user-images.githubusercontent.com/102940764/213973932-55831139-ea92-4000-94df-bc12ff4acff7.mov


https://user-images.githubusercontent.com/102940764/213973937-d165a3f3-0825-4782-bb28-bbf9023eacf0.mov


https://user-images.githubusercontent.com/102940764/213973939-56eb2be7-6bb6-4297-bbe0-a220d13c4384.mp4

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: io.mosip.residentapp-0.4.1-rc8-dirty-newlogic_20230126_1315_universal.apk
iOS TestFlight -Inji  0.4.1 (15)


**WORKS AS EXPECTED** 
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. Share an ID
2. Scan the QR code on the requesting device
3. Click `Reject `in the sharing device
4. Requesting device should display a popup that sharing was disconnected

**Devices**
Samsung Galaxy A23 - android 12
Samsung Galaxy A20s - android 11
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot**

![IMG_3789](https://user-images.githubusercontent.com/102940764/215010024-4f6be862-b60d-4cbf-aa5a-3a5835a90e52.jpg)


https://user-images.githubusercontent.com/102940764/215010001-4ffd957e-3d68-41be-a3a3-71fc25142852.mov

**Comment by Anuranjan14** [comment]
Verified the issue in the below devices and its working as expected. Hence closed.

**Android to Android:**-
Wallet Device:
Phone make/model: Redmi K20 Pro
OS: Android 11
BLE version : BLE 5.0

Verifier Device:
Phone make/model: Redmi note 10 lite
OS: Android 10
BLE version : BLE 5.0
Inji app version: https://github.com/mosip/inji/actions/runs/4447486079
Video:
https://user-images.githubusercontent.com/120705365/227435391-806d1bd5-793d-4e61-be5f-525d11acb319.mp4

**Cross Platform:-**
Wallet Device:
Phone make/model: iphone 11
OS: ios version 15
BLE version : BLE 5.0

Verifier Device:
Phone make/model: Redmi note 10 lite
OS: Android 10
BLE version : BLE 5.0
Video:
https://user-images.githubusercontent.com/120705365/227435856-bce7fd5c-8fb6-4bdd-ba5c-466bc5c0a59d.mp4

Inji app version: https://github.com/mosip/inji/actions/runs/4447486079
Mimoto version: 1.2.0.1
MOSIP Version: 1.2.0.1
CommitId:
![image](https://user-images.githubusercontent.com/120705365/227436041-d5b85242-1e41-46d7-9aba-6d5fe0d823ba.png)
![image](https://user-images.githubusercontent.com/120705365/227436108-53081e98-90b6-438b-afa7-08f0d960ad21.png)
