### ISSUE TITLE
Name and Device reference number fields are missing in sharing device and also on requesting device

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#226]
**Describe the bug**
Name and Device reference number fields are missing in sharing device

**To Reproduce**
Dvice A --> Requesting
Device B --> Sharing

Open qrcode in Device A
Open scanner in Device B
Scan the qrcode from Device B
connection is established, Now select VC to share screen appears.

**Current behavior**
Name and Device reference number fields are missing in sharing device , We see only requested by and reason for sharing fields.

**Expected behavior**
Sharing Device screen should contain Name and Device reference number field.

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/200561897-82cbe182-6247-481d-8e31-e952a88233ec.png)
![image](https://user-images.githubusercontent.com/102220709/200562330-7a55e90f-a402-40d4-bfdf-cc68ea06498c.png)

Smartphone (please complete the following information):
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/actions/runs/3287270987

Additional information:
this same bug for IOS: https://github.com/mosip/inji/issues/225

**Comment by rakhimosip** [comment]
@kyanthony were these fields removed intentionally? If yes, then we need to ensure that there is no information loss post this change.

**Comment by pmigueld** [comment]
@rakhimosip Yes, the fields were removed [here](https://github.com/idpass/inji/commit/4a57e519375fd0e75645a68d38098a3706bced87#diff-900f23ae5b0715a51d80162db8aa5a257a0cee39c6fe11e05fd78ecd0c2402ceL15-L20). It was discussed before that it could be confusing to have multiple device identifiers on the screen. 

The ones removed were:
- **Name** - this was the user-configurable identifier from the settings page (e.g. Paolo's iPhone)
- **Device ID** - from this function call: [`RNDeviceInfo.getDeviceId()`](https://github.com/react-native-device-info/react-native-device-info#getdeviceid)

The one left:
- **Device Name** - this uses the name that is set on the user's device typically found in the bluetooth settings

**Comment by Sujithbn** [comment]
@Anushree09-N Please verify

**Comment by santhoshsunder** [comment]
verified this issue in qa5 env the app is working as expected, its projecting the bluetooth name of the device, hense closing this bug
