### ISSUE TITLE
Inji app is not prompting the user to grant location access.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#231]
**Describe the bug**
Inji app is not prompting the user to grant location access.

**To Reproduce**
1. Install the app
2. click on the app 

**Current behavior**
Inji app is not prompting the user to grant location access.

**Expected behavior**
App should prompt user with toast asking to grant location access.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/200592352-3c8e4123-5589-4357-a9bc-425e3389d15e.png)

**Smartphone (please complete the following information):**

- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by pmigueld** [comment]
Location access is not needed for Google Nearby Messages so this is not prompted in iOS.

**Comment by Sujithbn** [comment]
@Anushree09-N Could you please verify the comments from Anthony and confirm

**Comment by Anushree09-N** [comment]
Tested in 1.2.0.1, qa5 env, As per the documentation location access is not needed in iOS as Google Nearby Messages (online) is being used.
![image](https://user-images.githubusercontent.com/79500509/206444309-aec1443d-a6ca-49b6-929d-c4ed071e7e00.png)
https://docs.google.com/document/d/1KFoDK0s6tmy3erafPzHaSBGn-L7Rb--UW9Y_3KGUMq8/edit?usp=sharing
Hence closing the ticket
