### ISSUE TITLE
VC detailed layout is not ocupying the spaces properly

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#232]
**Describe the bug**
VC detailed layout is not ocupying the spaces properly

**To Reproduce**
- Open app and head to home page
- click on add ID and download VC
- Go back to home
- Open the downloaded VC card

**Current behavior**
The card layout not occuping the available space properly when data is lengthy.

**Expected behavior**
The layout should occupy the available space properly when data is lengthy.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/200593619-f3fefa27-9e0d-451d-9f03-ddcaca77d7be.png)

**Smartphone (please complete the following information):**

- Device: iPhone7 & iPhone XR
- OS: 15.4.1
- Inji app version: 0.4.0 (16) in test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Additional context**
Android issue is registered https://github.com/mosip/inji/issues/200

**Comment by Anil-kumar-Majji** [comment]
@rakhimosip The above issue was solved by increasing the number of lines in modules VcItem.tsx. I also adjusted the same problem in singleVcItem.tsx I raised PR and sent it to @Sujithbn. The code review was still pending.
[Respective Screenshot](https://user-images.githubusercontent.com/106086523/203721908-9826ea5b-791b-4e9e-8ec9-1eb96d0b00f1.png)

**Comment by Anil-kumar-Majji** [comment]
@Sujithbn @Anushree09-N The above Issue was resolved in android and raised PR(#472) and submitted.
