### ISSUE TITLE
When `Cancel` button is clicked during sharing, no prompt is displayed on the receiving device that the sharing was cancelled.

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#249]
**Describe the bug**
When the `Cancel` button is click in the sharing device (during sharing), no prompt is displayed on the receiving device that the sharing was cancelled. The receiving device can also receive the ID even if it was cancelled during sharing.
`History` on the **receiving device** shows that the ID has been received.
`History` on the **sharing device** does not display the shared ID that was cancelled.

**To Reproduce**

1. Share an ID
2. Scan the QR code on the requesting device
3. Sharing device should be on `Sharing ID` screen - requesting device screen should also display: `Connected to device. Waiting for ID`
4. In the sharing device, add a reason for sharing then click `Accept request and choose ID`
5. Choose and ID and click `Share` - Sharing device should display `Sharing...` 
6. Wait for few seconds until the `Cancel` button appears below `Sharing`
7. `Incoming ID` page should display in the requesting device
8. Click on the `Cancel` button below `Sharing` (Sharing device)
9. **See error on the requesting device** - Requesting device is still on `Incoming ID` page

**Expected behavior**
Prompt about cancelled sharing should appear on the requesting device. No records should show in `History` on the **receiving device** since the transaction was cancelled

**Screenshots**
[https://newlogic.slack.com/archives/C02C22HF541/p1668056830616519?thread_ts=1668056523.294029&cid=C02C22HF541](url)

**Smartphone (please complete the following information):**
MOSIP server: QA4
Devices:
Samsung Galaxy A20S
iPhone 11

**Additional context**
Tested on: 
Android - [QA4_io.mosip.residentapp-0.4.0-rc8-newlogic_20221109_1559.apk](https://github.com/idpass/inji/releases/download/0.4.0-rc8/QA4_io.mosip.residentapp-0.4.0-rc8-newlogic_20221109_1559.apk)
iOS - 0.4.0 (14.2

**Comment by jannahadlaon** [comment]
Tested on:
Android: QA4_io.mosip.residentapp-0.4.1-beta.1-10-d68f577-feature_mosip-55-face-matching-newlogic_20221115_1441.apk
iOS: 0.4.1 (1)

**ISSUE IS STILL PRESENT** 
@kyanthony @pmigueld 

**Screenshot**
https://user-images.githubusercontent.com/102940764/202093884-7986d54e-284f-40ec-b945-c26ab99fd938.mov


Devices:
iPhone 11 - iOS 16.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Comment by jannahadlaon** [comment]
**Tested on:** 
Android: QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk
iOS: inji 0.4.1 (3) (TestFlight)

**Assign back to dev**
Issue is still present. Even if the sharing was cancelled, the ID is received. **Clicking the ID that was received in `Received IDs` crashes the app**

CC: @kyanthony @pmigueld @danicaerediano 

**To Reproduce**
Steps to reproduce the behavior:

1. Share an ID
2. Scan the QR code on the requesting device
3. Sharing device should be on Sharing ID screen - requesting device screen should also display: Connected to device. Waiting for ID
4. In the sharing device, add a reason for sharing then click Accept request and choose ID
5. Choose and ID and click Share - Sharing device should display `Sharing...`
6. Wait for few seconds until the Cancel button appears below Sharing
7. Incoming ID page should display in the requesting device
8. Click on the Cancel button below Sharing (Sharing device)
9. **See error on the requesting device** - Requesting device is still on Incoming ID page
10. Accept the ID on the Requesting device
11. Go to `Received IDs`
12. Click on the ID that was shared - see error: App crashes 

**Screenshot**
https://user-images.githubusercontent.com/102940764/203893591-5e3fe721-2f45-445d-903e-4d2b707698c1.mp4

**Comment by santhoshsunder** [comment]
**Smartphone :**
1. Device: PIXEL 6
2. OS: Android 13
3. MOSIP Version: 1.2.0.1
4. MOSIP server: qa5.mosip.net
5. APP link; https://mosip.atlassian.net/browse/DSD-1816

Able to replicate the issue
https://user-images.githubusercontent.com/102220709/209766984-a1e6ed8e-e5ee-434c-87a3-65f552bc974f.mp4

**Comment by Anushree09-N** [comment]
Unable to verify the ticket due to issue https://github.com/mosip/inji/issues/370

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc7/COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk)
iOS TestFlight -Inji  0.4.1 (11)


**WORKS AS EXPECTED** for `android <-> android`, `iOS <->iOS`, and `android -> iOS`
but **issue is still present** when sharing from `iOS to android`
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. . Share an ID
2. Scan the QR code on the requesting device
3. On the requesting device, wait for the `Cancel` button to appear below `Exchanging device info...`
4. Click `Cancel`
5. Verify that Disconnected popup appears on the sharing device

**Devices**
Samsung Galaxy A23 - android 12
Samsung Galaxy A20a - android 11
iPhone 11 - iOS 16.1.2

**Screenshot**

https://user-images.githubusercontent.com/102940764/212578539-f95c7246-83e3-410c-bc2b-88939ece92fe.mov


https://user-images.githubusercontent.com/102940764/212578549-7d821457-702a-47cd-a1d9-4e221e419159.mp4

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: [io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc8/io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk)iOS TestFlight -Inji  0.4.1 (12)


**WORKS AS EXPECTED** for `android <-> android`, `iOS <->iOS`, and `android -> iOS`
but **issue is still present** when sharing from `iOS to android`
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. Share an ID
2. Scan the QR code on the requesting device
3. On the requesting device, wait for the `Cancel` button to appear below `Exchanging device info...`
4. Click `Cancel`
5. Verify that Disconnected popup appears on the sharing device

**Devices**
Samsung Galaxy A23 - android 12
Samsung Galaxy A20s - android 11
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot**

https://user-images.githubusercontent.com/102940764/213967848-db70fb45-36ef-43d1-927c-72af87c848b5.mp4


https://user-images.githubusercontent.com/102940764/213967856-4b051534-8eb2-461d-a514-7fbdb3716423.mov


https://user-images.githubusercontent.com/102940764/213967860-7bf08a22-590d-4633-9be3-b9593b4a0568.mov


https://user-images.githubusercontent.com/102940764/213967865-cc831452-4f22-40bf-938a-f0b13db7e6c7.mov

**Comment by Sujithbn** [comment]
This issue has been descoped from the beta release.

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
