### ISSUE TITLE
No prompt is displayed on the Sharing device when `Cancel` is clicked on the Receiving device during sharing

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#250]
**Describe the bug**
When sharing and the Receiving device clicked on `Cancel` while `Exchanging device info...` no prompt is displayed on the sharing device that the sharing was cancelled.

**To Reproduce**

1. Share an ID
2. Scan the QR code on the requesting device
3. On the requesting device, wait for the `Cancel` button to appear below `Exchanging device info...` (_see screenshot_)
4. Click `Cancel`
5. See error on the sharing device 

**Expected behavior**
Prompt about cancelled sharing should appear on the sharing device. 

**Screenshots**
![VideoCapture_20221110-152837](https://user-images.githubusercontent.com/102940764/201027814-c7d497ac-a037-42ac-b0c6-cc172a6b91e1.jpg)

**Video**
https://newlogic.slack.com/archives/C02C22HF541/p1668056918180619?thread_ts=1668056523.294029&cid=C02C22HF541

**Smartphone (please complete the following information):**
MOSIP server: QA4
Devices:
Samsung Galaxy A20S
iPhone 11

**Additional context**
Tested on:
Android - [QA4_io.mosip.residentapp-0.4.0-rc8-newlogic_20221109_1559.apk](https://github.com/idpass/inji/releases/download/0.4.0-rc8/QA4_io.mosip.residentapp-0.4.0-rc8-newlogic_20221109_1559.apk)
iOS - 0.4.0 (14.2

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk
iOS: inji 0.4.1 (3) (TestFlight)

**Assign back to dev**
**Issue is still present**. During sharing, when Receiving device clicked on `Cancel` while `Connected to device. Waiting for ID...` or no prompt is displayed on the sharing device that the sharing was cancelled.
The sharing process also continues on the Sharing device, cancelling it crashes the app

CC: @kyanthony @pmigueld @danicaerediano

**STEPS**
1. Share an ID
2. Scan the QR code on the requesting device
3. On the requesting device, wait for the `Cancel ` button to appear below `Connected to device. Waiting for ID...` (_see screenshot_)
4. Click Cancel
5. See error on the sharing device
6. On sharing device, select an ID and share
7. Wait for the `Cancel ` button to appear below the Sharing pop up
8. Click ok `Cancel ` - see error: the receiving device's app crashes (_see screenshot_)


**Screenshot**
https://user-images.githubusercontent.com/102940764/203899658-dbe6c65a-2feb-433c-b68b-c6e04789ff36.mp4
https://user-images.githubusercontent.com/102940764/203900339-ed135010-f8a2-429d-822d-0502caa8b016.mp4

**Comment by Anushree09-N** [comment]
Verified on:

Device : iPhone 8 & OnePlus Nord 2
OS: 16.0.2
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Able to replicate the issue


https://user-images.githubusercontent.com/79500509/209441514-ad310222-75f2-4179-b763-1c0357627ff0.mov

**Comment by santhoshsunder** [comment]
**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

Able to replicate the issue
![image](https://user-images.githubusercontent.com/102220709/209766458-c4749568-11e8-43b5-b2b2-7ba2a1647c46.png)

**Comment by rakhimosip** [comment]
@kyanthony @pmigueld @Anushree09-N @jannahadlaon 

**Cancel button on requesting device**
- this appears when the connection is established but the sharer has not selected a credential to share

**Proposed fix**
- clicking on this should open a new QR code on requesting device
- It should send back status to sharing device that the request has been canceled. The same should be displayed as a message to sharer.

Linked tickets 
https://github.com/mosip/inji/issues/252 
https://github.com/mosip/inji/issues/249

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc7/COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk)
iOS TestFlight -Inji  0.4.1 (11)


**WORKS AS EXPECTED** for `android <-> android`, `iOS <->iOS`, and `android -> iOS`
but **issue is still present** when sharing from `iOS to android`
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. . Share an ID
2. Scan the QR code on the requesting device
3. On the requesting device, wait for the `Cancel` button to appear below `Exchanging device info...`
4. Click `Cancel`
5. Verify that Disconnected popup appears on the sharing device

**Devices**
Samsung Galaxy A23 - android 12
Samsung Galaxy A20a - android 11
iPhone 11 - iOS 16.1.2
iPhone 6s

**Screenshot**

https://user-images.githubusercontent.com/102940764/212578539-f95c7246-83e3-410c-bc2b-88939ece92fe.mov


https://user-images.githubusercontent.com/102940764/212578549-7d821457-702a-47cd-a1d9-4e221e419159.mp4

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: [io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc8/io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk)iOS TestFlight -Inji  0.4.1 (12)


**WORKS AS EXPECTED** for `android <-> android`, `iOS <->iOS`, and `android -> iOS`
but **issue is still present** when sharing from `iOS to android`
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. Share an ID
2. Scan the QR code on the requesting device
3. On the requesting device, wait for the `Cancel` button to appear below `Exchanging device info...`
4. Click `Cancel`
5. Verify that Disconnected popup appears on the sharing device

**Devices**
Samsung Galaxy A23 - android 12
Samsung Galaxy A20s - android 11
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot**

https://user-images.githubusercontent.com/102940764/213967848-db70fb45-36ef-43d1-927c-72af87c848b5.mp4


https://user-images.githubusercontent.com/102940764/213967856-4b051534-8eb2-461d-a514-7fbdb3716423.mov


https://user-images.githubusercontent.com/102940764/213967860-7bf08a22-590d-4633-9be3-b9593b4a0568.mov


https://user-images.githubusercontent.com/102940764/213967865-cc831452-4f22-40bf-938a-f0b13db7e6c7.mov

**Comment by Sujithbn** [comment]
This issue has been descoped from the beta release.

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
