### ISSUE TITLE
Error message should be revised when biometrics is not enrolled in device settings page but still resident use biometric unlock

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#259]
**Describe the bug**
Error message should be revised when biometrics is not enrolled in device settings page but still resident use biometric unlock feature

**To Reproduce**
 **Prerequisite:**  Biometrics is not enrolled in device settings page

**Steps:**
1. Install the inji app
2. click on Get started button
3.  Displays two option 

- **Biometrics unlock**
- **I would rather use passcode**

4. click on biometrics unlock button

**Current behavior**
Displayed error message as "To use Biometrics, please enroll your **fingerprint** in your device settings".

**Expected behavior**
As smart phones supports biometric unlock with face and also with fingerprint , the error message can say user to enroll your "biometrics" in device settings page instead of saying specifically to set **fingerprint**.

**Screenshots**
![Inkedimage (44)](https://user-images.githubusercontent.com/79500509/202636662-a35aa181-db0e-4063-8dc8-4acb60506dcb.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone
- OS: 15.4.1
- Inji app version: 0.4.0
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by jannahadlaon** [comment]
**Tested on**
iOS: Inji 0.4.1 (7)

**WORKS AS EXPECTED** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**Test devices:**
iPhone SE - iOS 15.4

**Screenshot**
![IMG_0074](https://user-images.githubusercontent.com/102940764/208370747-f801f29a-ec6d-4a21-acd0-4e125a8bb50f.png)

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 11
OS: 15.6.1
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Working as expected . Message has been revised with the word biometrics instead of fingerprint while resident is trying to use biometric feature to unlock the app when biometrics are not set in the device settings page.

![image](https://user-images.githubusercontent.com/79500509/208895011-d1012a7f-3108-4cb4-a7fb-261b7db92ea9.png)

![image](https://user-images.githubusercontent.com/79500509/208895057-67701830-0e6a-4703-b62e-ae0c27d9c397.png)
