### ISSUE TITLE
Error message should be revised when biometrics is not enrolled in device settings page but still resident use biometric unlock

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#260]
**Describe the bug**
Error message should be revised when biometrics is not enrolled in device settings page but still resident use biometric unlock feature

**To Reproduce**
Prerequisite : make sure there is no biometrics for authentication where added in the mobile 
1.Install the inji app
2.Click on Get started button
3.Displays two option ---- Biometrics unlock
I would rather use passcode
4.click on biometrics unlock button

**Current behavior**
Displayed error message as "To use Biometrics, please enroll your fingerprint in your device settings".

**Expected behavior**
As smart phones supports biometric unlock with face and also with fingerprint , the error message can say user to enroll your "biometrics" in device settings page instead of saying specifically to set fingerprint.

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/202637719-4e6b2c8c-c67b-4fc8-af27-e1612ecdbb89.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/actions/runs/3287270987

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)

**WORKS AS EXPECTED** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 


**Test devices:**
Samsung Galaxy A23 - Android 12

**Screenshot**
![Screenshot_20221219-151845_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/208370788-37b21eb8-01ee-48e2-94dd-4f4d31310c40.jpg)

**Comment by santhoshsunder** [comment]
Verified this issue in QA5 env, issue is not observed any more, the message is projected as expected, iam attaching the current working screenshot, hense closing this bug

**Screenshot :**
![image](https://user-images.githubusercontent.com/102220709/209271285-d19791ac-b2ee-49f5-9634-d908cd02c753.png)
![image](https://user-images.githubusercontent.com/102220709/209271296-a32d66ec-267b-4e3e-9d24-8e4c8244412a.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by Sujithbn** [comment]
This issue has been descoped from the beta release.
