### ISSUE TITLE
iOS: app should detect if the user’s biometrics changes in the device settings page

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#261]
**Describe the bug**
App should detect if the user’s biometrics changes in the device settings page like added / removed . App should prompt user to re confirm by entering the passcode set in the app.

**To Reproduce**

- Add biometrics to device
- Activate biometrics logon for the resident app
- Log out of the app
- Add a second fingerprint to the device
- Log on to the app

**Current behavior**
App allows you us to log on without additional identification (passcode verification).

**Expected behavior**
App should prompt user to enter passcode in order to re-enable biometric identification.

**Smartphone (please complete the following information):**
Device: iPhone7 & iPhone XR
OS: 15.4.1
Inji app version: 0.4.0 (16) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Additional context**
This the llimitation in iOS app and same is documented here https://drive.google.com/file/d/1Uyx0M2e5_70UCcHJoHC3MouWIuz2oMG7/view

**Comment by pmigueld** [comment]
As noted in the "Additional Context" and in the folowing document:
https://docs.google.com/document/d/1KFoDK0s6tmy3erafPzHaSBGn-L7Rb--UW9Y_3KGUMq8/edit#

It is a current limitation in iOS.

**Comment by Sujithbn** [comment]
This is known bug in the current release and will not be fixed for Beta release.

**Comment by santhoshsunder** [comment]
this issue is a copy of #530, hence closing this issue
