### ISSUE TITLE
Sharing device is not displaying success pop up message after sharing a VC

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#262]
**Describe the bug**
Sharing device is not displaying success pop up message after sharing a VC.

**To Reproduce**
Device A --> Requesting
Device B --> Sharing

- Open qrcode in Device A
- Open scanner in Device B
- Scan the qrcode from Device B
- Connection is established, Now select VC and click on share
- From device A accept the incoming VC request, the VC will be shared successfully

**Expected behavior**
Sharing device should be display success pop up message after sharing a VC

**Observed behavior**
After successful VC share the device B is redirected to home page without any popup message of the sharing.

**Smartphone** (please complete the following information):
Device: iPhone 7 & iPhone XR
OS: 15.4.1
Inji app version: 0.4.0 (16) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Comment by Anushree09-N** [comment]
Android issue is here https://github.com/mosip/inji/issues/238

**Comment by Sujithbn** [comment]
This issue has been descoped from the beta release.

**Comment by santhoshsunder** [comment]
Verified this issue in the BLE build (le730bf), Both devices are giving the success message prompt, hence closing the bug
