### ISSUE TITLE
Inji app crashing while sharing 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#276]
**Describe the bug**
The Inji app is crashing while sharing the VC

**To Reproduce**
prerequisite : Device A --> Requesting
Device B --> Sharing

Open qrcode in Device A
Open scanner in Device B
Scan the qrcode from Device B

**Observed result**
The Device B's app is crashing, after the scan is completed 

**Expected behavior**
The connection should be established, and should able to perform VC sharing 

**Screenshots**
https://user-images.githubusercontent.com/102220709/203906781-5deb20fc-e78a-499d-9f50-31b3352c7267.mp4

**Smartphone (please complete the following information):**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1666

**Comment by srikanth716** [comment]
We have found that the issue is from SingleVcItem.tsx file, It is looping in the same state  (reviewing.selectingVc) in the scan.ts file. It is showing " Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops " in the terminal logs.

**Comment by santhoshsunder** [comment]
When the photo is captured without a face and if we are trying to authenticate it the app is crashing, the a video of performing this action is attached down below

https://user-images.githubusercontent.com/102220709/205267664-28241e8a-0d1c-4a39-9e45-bde2050147ff.mp4

**Comment by pmigueld** [comment]
> When the camera is opened, capture something else without containg a human face

This is an issue with the face-matching SDK (0.1.1). It crashes when no faces are found:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/1631922/205798131-cd8d2f13-2185-4d72-905d-491d295ff374.png">

See here:
https://github.com/mosip/mosip-mobileid-sdk/blob/InjiFaceSdk/android/src/main/java/com/mosipinjifacesdk/MosipInjiFaceSdkModule.java#L104

cc: @MonobikashDas @jannahadlaon

**Comment by santhoshsunder** [comment]
The app is still crashing after the VC is shared and opened in detailed view from the android side, we have raised two bugs according to this issue iam attaching them both bellow 

**Additional context**
https://github.com/mosip/inji/issues/319
https://github.com/mosip/inji/issues/321

**Comment by Anushree09-N** [comment]
Tested in qa5 env, 1.2.0.1 , App crashing issue is resolved which was associated with scanning functionality sharing is working.
Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (5) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

**Comment by santhoshsunder** [comment]
Tested in qa5 env, 1.2.0.1 , App crashing issue is resolved which was associated with scanning functionality sharing is working. hense closing this bug

**screenshot:**
https://user-images.githubusercontent.com/102220709/206678159-c66d1c55-0619-4282-90be-ee0efd4745bf.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736
