### ISSUE TITLE
App crashed after viewing a Received ID

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#280]
**Describe the bug**
After sharing an ID and opening the shared ID in the `Received IDs`, the app crashes. 

**To Reproduce**

1. Share an ID
2. After successfully sharing an ID, the receiving device should land on the `Received IDs` page
3. Open the ID shared in the `Received IDs`

**Expected behavior**
App should not crash and you should be able to open and view the details of the shared ID in the `Received IDs` page

**Additional context**
Tested on builds:
Android: **_QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk_**
iOS: _**inji 0.4.1 (3) (TestFlight)**_

**Smartphone**
- iPhone 11 - iOS 16.1
- iPhone SE - iOS 15.4
- Samsung Galaxy A23 - Android 12

**Screenshots**
https://user-images.githubusercontent.com/102940764/204182590-5f039680-251d-4d4d-8f0c-c5902304dd47.MP4

**Comment by pmigueld** [comment]
Related crashlytics report:
https://console.firebase.google.com/project/mosip-resident-app/crashlytics/app/android:io.mosip.residentapp/issues/ae12e08275f7310db29992f1ef9776f6?time=last-seven-days&sessionEventKey=6385AFC700490001593AA5BE88576146_1749777588287282709

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc3/QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk)
iOS: Inji 0.4.1 (4)

**ISSUE IS STILL PRESENT** 
**Assign back to dev**
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Share an ID
2. After successfully sharing an ID, the receiving device should land on the Received IDs page
3. Open the ID shared in the Received IDs
4. See error

**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

**WORKS AS EXPECTED** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Share an ID
2. After successfully sharing an ID, the receiving device should land on the Received IDs page
3. Open the ID shared in the Received IDs
4. Verify that the app doesn't crash



**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Comment by santhoshsunder** [comment]
Verified this issue in android QA5 env, issue is not observed anymore, we are able to share and view VC in android without any errors, hense the bug is closable from android side

**Screenshot :**
https://user-images.githubusercontent.com/102220709/209133646-7918c9b0-c659-4e2a-8487-25e8da303205.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (4) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

App is not  crashing able to view Received ID.

 Uploading RPReplay_Final1671712517.MP4…
