### ISSUE TITLE
otp generation is failing with the error "while generating otp error is occured"

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#291]
**Describe the bug**
otp generation is failing with the error "while generating otp error is occured"

**To Reproduce**
1. Request otp 
URL: {{url}}/resident/v1/req/otp

**Request:** 
{
  "id": "mosip.identity.otp.internal",
  "individualId": "8920857029",
  "metadata": {},
  "otpChannel": ["PHONE", "EMAIL"],
  "requestTime": "2022-11-25T10:15:24.702Z",
  "transactionID": "1234567890",
  "version": "1.0" 
} 

**Reponse:** 
{
    "id": null,
    "version": "v1",
    "responsetime": "2022-12-01T06:20:06.745Z",
    "metadata": null,
    "response": null,
    "errors": [
        {
            "errorCode": "RES-SER-425",
            "message": "while generating otp error is occured"
        }
    ]
}

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/204981562-ba17b3f7-1152-4766-9250-ded40ed7ae91.png)
![image](https://user-images.githubusercontent.com/79500509/204981612-eb84e297-60ce-4c11-b817-3741d64db22d.png)

**Smartphone (please complete the following information):**

- Device: Android , iOS
- OS: 16.0.2
- Inji app version: 0.4.1 (4) --> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Additional context**
UIN  : 8920857029

**Comment by LoganathanSekar7627** [comment]
@Anushree09-N , please share resident-service and ida-internal service logs, for this error use case.

**Comment by LoganathanSekar7627** [comment]
@Anushree09-N , getting 500 error from IDA on otp request, due to PKCS error on Zero-knowledge decryption, this is an intermittent issue, needs restarts of IDA services. I will raise a DSD for that.

**Comment by LoganathanSekar7627** [comment]
sun.security.pkcs11.wrapper.PKCS11Exception: CKR_SESSION_HANDLE_INVALID
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_SignInit(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.initialize(P11Signature.java:366)
	... 121 common frames omitted

**Comment by LoganathanSekar7627** [comment]
@Anushree09-N raised DSD https://mosip.atlassian.net/browse/DSD-1712, once done, please check.

**Comment by LoganathanSekar7627** [comment]
@Anushree09-N , It is done, please check.

**Comment by santhoshsunder** [comment]
Verified this in qa5 env, issue is not occoring any more, hense closing this bug

**Smartphone**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
APP link; https://mosip.atlassian.net/browse/DSD-1846
