### ISSUE TITLE
Camera is not launched in verifier's phone even after giving the consent from Resident's phone.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#293]
**Describe the bug**
Camera is not launched in verifier's phone even after giving the consent from Resident's phone.

**To Reproduce**
Device A (iOS)-->Requesting 
Device B (iOS)-->Sharing

1. Open qr code in Device A
2. open scanner in Device B
3. Scan the qr code from Device B
4. Check-in the consent and select VC to share from Device B
5. click on **Accept Request and Choose ID**

**Current behavior**
Camera is not launched in verifier's phone even after giving the consent from Resident's phone.

**Expected behavior**
Camera should be launched in verifier's phone and should be able to capture resident's phone.

**Screenshots**

https://user-images.githubusercontent.com/79500509/205216520-76da1616-13a6-482e-8a3b-35f096ffca47.mp4

**Smartphone (please complete the following information):**

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (4) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by jannahadlaon** [comment]
**The issue above is present using the following builds:** @pmigueld @Anushree09-N @kyanthony 
Android: https://drive.google.com/file/d/1SoYlUh6eoFH-q-MG1pgtpcfu1B-sZ2cR/view?ts=63898b52
iOS: mosipInji 0.4.1 (4)

Test devices:
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Screenshots**
iOS
https://user-images.githubusercontent.com/102940764/205226600-a1de0279-e7cc-4792-9a81-4d918c9ea19a.mp4

Android
Uploading IMG_3063.mov…

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc3/QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk)
iOS: Inji 0.4.1 (4)

**WORKS AS EXPECTED** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Screenshots**
https://newlogic.slack.com/archives/C03494036MV/p1670231170329429?thread_ts=1669904641.999229&cid=C03494036MV

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

Working as expected , Able to capture resident face from verifier's phone.

![image](https://user-images.githubusercontent.com/79500509/209126174-c5ef00e7-b6af-4886-a8b1-2d378b27d815.png)

![image](https://user-images.githubusercontent.com/79500509/209126210-1e778dd9-6db1-436d-8dcf-e81ed7fc3129.png)

![image](https://user-images.githubusercontent.com/79500509/209126222-385a229a-6fb5-4003-ba05-8387bc015437.png)
