### ISSUE TITLE
The face authentication is not working as expected 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#296]
**Describe the bug**
The face authentication is not working as expected while sharing credentials

**To Reproduce**
prerequisite : Device A --> Requesting
Device B --> Sharing

1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. In the sharing ID screen in device B, select the UIN card you want share
5. And click on the "Accept request and verify" button
6. When the camera is openned, try to cover your face or wear a helmet and capture your face 

**Expected behavior**
The app should deduct the object covering the face, and should ask to retry again capturing our face with out covering and should not allow sharing VC

**Observed :**
The app is authenticating the image and allowing us to share the credentials 

**Smartphone (please complete the following information):**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1666

**Comment by santhoshsunder** [comment]
tested this issue, the issue is still occurring in the new build, face auth is still not working intermittently on specific devices, iam attaching the device details and the screen shot below, hence reopening this bug again 

Screenshot : 

Tested on : 
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP server : mec.mosip.net
APP link : https://github.com/mosip/inji/actions/runs/4376878070

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26840

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
