### ISSUE TITLE
Unable to get UIN/VID using AID

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#297]
**Describe the bug**
Unable to get UIN/VID using AID

**To Reproduce**
1. Unlock the app
2. click on ADD ID button in home page
3. click on "Don't have your UIN/VID? Get it here " link.
4. Enter valid AID
5. click on Get UIN/VID button

**Current behavior**
User still remains in AID screen without moving navigating to Otp screen and projecting error as no message available

**Expected behavior**
When user clicks on Get UIN/VID button by entering AID number should prompt to enter Otp, After successful Otp match UIN should be auto filled.

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/205281497-f6dc6c55-def5-44d9-ac89-3c172f7626b2.png)

**Smartphone (please complete the following information):**

- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1666

**Comment by Sujithbn** [comment]
We have dependency on the Resident services API and this will not be fixed for beta release

**Comment by Sujithbn** [comment]
Remove AID option

**Comment by santhoshsunder** [comment]
Verified this issue in the new build, the issue is still occurring, we are unable to get UIN/VID with AID, and we are getting "Jason parse error", I am attaching the screenshot and the device details below for reference 

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/223379432-12164444-5445-40ce-b387-884c7e26e059.png)

Device detials :
Phone make/model: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4343056712

**Comment by Anushree09-N** [comment]
Verified in:
Device: Redmi 6A
OS version: Android 9
BLE 4.2
App link: https://github.com/mosip/inji/actions/runs/4374171157
Mosip server: qa-1201-b2.mosip.net

App commit id:
![image](https://user-images.githubusercontent.com/79500509/224308004-d1acc331-ecb4-47bc-acbe-723e5dd324e6.png)

Able to retrieve VID for given application ID hence closing the bug.

![image](https://user-images.githubusercontent.com/79500509/224308806-41e1d680-17c2-4530-a5f0-6b4aa7abd36d.png)
