### ISSUE TITLE
Able to share VC even when camera captures objects / Covered face while verifying presence from Resident's phone.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#298]
**Describe the bug**
Able to share VC even when camera captures objects / Covered face while verifying presence from Resident's phone.

**To Reproduce**
Device A (iOS)-->Requesting
Device B (iOS)-->Sharing

1. Open qr code in Device A
2. open scanner in Device B
3. Scan the qr code from Device B
4. select VC to share from Device B
5. click on **Accept Request and Verify**
6. Camera opens up -->> capture object/ face covered with helmet

**Current behavior**
Able to share VC even when camera captures objects / Covered face while verifying presence from Resident's phone.

**Expected behavior**
Sharing should fail with message **verification failed** message.

**Screenshots**
**Smartphone (please complete the following information):**

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (4) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by Sujithbn** [comment]
@MonobikashDas Please look in to the Paolo comment and update the ticket

**Comment by Sujithbn** [comment]
Feature is not developed, iOS is currently mocked because the face-matching SDK does not support. Please close the bug.

**Comment by Raginikrishnamurthy** [comment]
Currently the SDK is mocked in ios, we will relook when real sdk is implemented for ios. closing the bug for now,
