### ISSUE TITLE
A successful face match is not displaying the message in sharing device.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#302]
**Describe the bug**
A successful face match is not displaying the message in sharing device.

**To Reproduce**
 **Prerequiste:** VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
 Device A - Requesting device (iOS)
 Device B - Sharing device (iOS)
 **steps:**
 1. open qr code in Device A
 2. open scanner in Device B
 3. scan the qrcode from Device B
 4. select VC to share and click on ""verify presence and share"".
 5. camera opens up - captures photo of resident

**Current behavior** 
The message is not displayed in residents phone after successful face match
![image](https://user-images.githubusercontent.com/79500509/205885728-1c999e81-892a-4056-83d1-7a82d0086aca.png)

**Expected behavior**
If photo matches with the VC - displays ""Presence verified"" sharing... should be  displayed in Device B
![image](https://user-images.githubusercontent.com/79500509/205884548-096a04d9-2a79-4e58-a0bd-8593479f2839.png)

**Smartphone (please complete the following information):**

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (4) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

**Comment by santhoshsunder** [comment]
this issue is a copy of issue no. #303 , hence close this issue,
