### ISSUE TITLE
A successful face match is not displaying the message in sharing device

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#303]
**Describe the bug**
A successful face match is not displaying the message in sharing device.

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device 
Device B - Sharing device 

steps:
1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4. select VC to share and click on ""verify presence and share"".
5. camera opens up - captures photo of resident

**Current behavior**
The message is not displayed in residents phone after successful face match

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/205891301-cadbc5f4-78f3-439d-97a2-2b984380a284.png)

**Expected behavior**
If photo matches with the VC - displays ""Presence verified"" sharing... should be displayed in Device B
image

**Smartphone (please complete the following information):**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736

**Comment by hegdenitin** [comment]
Created JIRA ticket and will track in JIRA going forward. Closing the bug.
https://mosip.atlassian.net/browse/INJIMOB-1750
