### ISSUE TITLE
The sharing loading bar UI is not proper

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#304]
**Describe the bug**
while sharing VC, the sharing loading bar UI is not proper

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device
Device B - Sharing device

steps:
- open qr code in Device A
- open scanner in Device B
- scan the qrcode from Device B
- select VC to share and click on share

**Expected behavior**
the sharing loading bar should be proper

**Observed** 
The loading bar has another popup behind it as a shadow as shown in the bellow screenshot 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/205910041-25798b0a-55c3-49e8-9012-c02217b7f4e7.png)

**Smartphone (please complete the following information):**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736

**Comment by Sujithbn** [comment]
@santhoshsunder Please reverify and confirm on this
