### ISSUE TITLE
## Android Verifier

### ISSUE THREAD

**Issue by Sujithbn** [mosip/inji#307]
sub tasks
-
- [x] Implement BLE Verifier spec on android
- [x] Integration: Integrate Tuvali to Inji (Android Verifier)
- [x] Implement Public Key exchange on Android (verifier)
- [x] Implement BLE react native wrapper bridge - Android Verifier

**Comment by krishnakumar-tw** [comment]
Please assign this to @mohammed-strive & @vharsh
