### ISSUE TITLE
Unable to download credentials displayed "Network request failed"  error message

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#315]
**Describe the bug**
Unable to download credential displayed "Network request failed"  error message

**To Reproduce**
1. unlock the inji app
2. click on **Add ID** button
3. Enter valid UIN
4. click on **Get ID** button.

**Current behavior**
Unable to download credential with valid UIN displayed "Network request failed"  error message. Phone was connected to Wi-Fi even then we got above error message.

**Expected behavior**
VC download should be successful in the app

**Screenshots**

https://user-images.githubusercontent.com/79500509/206462738-a799a685-3655-4c37-94f8-d16512e65b1c.MP4
![image](https://user-images.githubusercontent.com/79500509/206463013-aeae2c37-f12f-45a3-80cf-c369351e5dee.png)

**Smartphone (please complete the following information):**

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (4) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

**Comment by pmigueld** [comment]
Could there be an issue with the server this was tested on?

**Comment by Sujithbn** [comment]
@Anushree09-N : This blocker issue(315) is working fine now after certification renewal, please verify and confirm us.

**Comment by Anushree09-N** [comment]
Verified in 
iPhone 11
iOS version 15
BLE 5.0
Commit id of the app: [4c2ca4b](https://github.com/mosip/inji/commit/4c2ca4b0ea400cb29cb59ee6a87106e2542023da)
APK link: https://github.com/mosip/inji/actions/runs/4447486079

![IMG20230321172839](https://user-images.githubusercontent.com/79500509/226599984-20ddf3dc-ff7c-4c8a-a3a0-3c0d4cd0da33.jpg)

 Able to download VC, working as expected.
