### ISSUE TITLE
Intermittently VC share not working (Google near by issue)

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#317]
**Describe the bug**
Android to iPhone VC share didn't work once, was able to share VC in the second attempt.

**To Reproduce**
**Prerequiste:** VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
 **Device A** - Requesting device (iOS)
 **Device B** - Sharing device (Android)
 **steps:**
 1. open qr code in Device A
 2. open scanner in Device B
 3. scan the qrcode from Device B
 4. select VC to share and click on "Accept request and verify".
 5.camera opens up - captures photo of resident

**Current behavior**
Sharing device stuck in sharing state while receiving device was still waiting to receive VC

**Expected behavior**
VC share should be working without failing intermittently

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/206619970-9705a7dc-e49b-4114-b15d-7b14e263e4a4.png)
![image](https://user-images.githubusercontent.com/79500509/206620039-ff5e364f-9efa-405a-b695-05694b36265e.png)

**Smartphone (please complete the following information):**

- Device: iPhone 8 , One plus Nord 2
- OS: 16.0.2, 12
- Inji app version: 0.4.1 (5)->testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Additional context**
Android apk:  https://github.com/mosip/inji/actions/runs/3626503207

**Comment by pmigueld** [comment]
Intermittent issue could be related to the quality of internet connection of the device. Due to how Google Nearby Messages works, the data goes through Google servers temporarily hence the need for an internet connection. I have added an optimization in #375 / #396 that reduces the number of back-and-forth messaging between the devices which could help with this.

**Comment by Sujithbn** [comment]
This issue has been descoped from the beta release.

**Comment by Raginikrishnamurthy** [comment]
google near by is excluded, no more a valid bug, hence closing on github.
