### ISSUE TITLE
Intermittently VC share not working (GNB issue)

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#320]
**Describe the bug**
Android to iPhone VC share didn't work once, was able to share VC in the second attempt.

**To Reproduce**
**Prerequiste:** VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device 
Device B - Sharing device 

**steps:**
1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4.Select VC to share and share (attempt any type of sharing method)

**Current behavior**
Sharing device stuck in sharing state while receiving device was still waiting to receive VC

**Expected behavior**
VC share should be working without failing intermittently

**Screenshots:**
![image](https://user-images.githubusercontent.com/102220709/206626598-b80d7021-8b19-4f5b-ac4d-2e93eed6e2af.png)
![image](https://user-images.githubusercontent.com/102220709/206626615-1475a372-0e21-42fb-9da5-73f5f418b17d.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736

**Comment by Raginikrishnamurthy** [comment]
google near by is excluded, no more a valid bug, hence closing on github.
