### ISSUE TITLE
App is crashing when clicked on Received credentials

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#321]
**Describe the bug**
App is crashing when clicked on Received credentials

**To Reproduce**
**Prerequiste:** VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device 
Device B - Sharing device 

**steps:**
1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4. select VC to share and attempt any type of sharing method
5. Accept incoming VC in Device A
6. in device A the VC will be received under received ID section 
7. open the received ID in detailed view

**Current behavior**
App crashes when clicked on any VC which is received from resident.

**Expected behavior**
We should be able to click and view received VC.

**Screenshot:**
https://user-images.githubusercontent.com/102220709/206627665-e0798d9d-5e02-474d-804d-f29d9c84110a.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

**WORKS AS EXPECTED** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Share an ID
2. After successfully sharing an ID, the receiving device should land on the Received IDs page
3. Open the ID shared in the Received IDs
4. Verify that the app doesn't crash



**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Comment by jannahadlaon** [comment]
Ticket https://github.com/mosip/inji/issues/280 with the same concern is already closed

**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

**WORKS AS EXPECTED** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Share an ID
2. After successfully sharing an ID, the receiving device should land on the Received IDs page
3. Open the ID shared in the Received IDs
4. Verify that the app doesn't crash



**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Comment by Anuranjan14** [comment]
Verified the issue and app is not crashing when clicked on received credentials in verifier. Hence closing.
Added video and device details .

https://user-images.githubusercontent.com/120705365/224720274-a868c37d-1fb8-4ca8-83c4-ebc1d97ac09a.mp4

Device details:-
Verifier:
Device: Redmi 7A
OS: Android 10
BLE version: 4.2
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

Wallet:
Device: Redmi K20 pro
OS: Android 11
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

CommitId:
![image](https://user-images.githubusercontent.com/120705365/224720549-b8cdb4e2-04cf-4108-9ed4-b28aedc311fa.png)
![image](https://user-images.githubusercontent.com/120705365/224720497-3ba7693b-00af-4c52-91ab-242bb5da6a52.png)
