### ISSUE TITLE
The consent was automatically selected while sharing

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#324]
**Describe the bug**
The consent was automatically selected, while sharing the second time, when the first sharing was with consent

**To Reproduce**
prerequisite : Device A --> Requesting
Device B --> Sharing

Steps :
1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. Select give consent and share a VC
5. again open scanner in Device B
6. Scan the qrcode from Device B

**Expected behavior**
The consent should not be selected automatically, untill the user clicks on it 

**Observed**
Once the sharing is done with giving consent, every other time the consent is selected on its own automatically 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/206972769-14de4b59-ca10-4a05-9e4b-314cb418c8b2.png)
https://user-images.githubusercontent.com/102220709/206973738-c4a5bf4d-23fe-4607-9661-05eb33106379.mp4

**Smartphone **
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736

**Comment by jannahadlaon** [comment]
**Tested on:** 
Android build: COLLAB_io.mosip.residentapp-0.4.1-rc5-19-7f194bd-fix_mosip-324-325-reset-user-consent-newlogic_20230106_1727.apk


**WORKS AS EXPECTED**
@pmigueld @kyanthony @santhoshsunder 

**STEPS**
1. Scan QR CODE on the requesting device to initiate sharing
2. On the Sharing device, click on the consent box and share ID (sharing should be successful)
3. Scan QR CODE on the requesting device again
4. Verify that on the SHARE ID page, the consent box is not pre-ticked.

Devices:
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20 - Android 11

**Screenshot**
https://user-images.githubusercontent.com/102940764/211454283-c6e8ebe6-76cb-4350-87be-54176280b427.mp4

**Comment by santhoshsunder** [comment]
Verified this issue on Qa-1201-b2 env, the issue is not observed any more, and working as expected, hense closing the jira

**Video:**
https://user-images.githubusercontent.com/102220709/212134688-b1b2f191-9066-448f-abde-b2eab99417c9.mp4

**Smartphone :**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
APP link; https://github.com/mosip/inji/actions/runs/3854157494
