### ISSUE TITLE
The consent was automatically selected in the second attempt of sharing 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#325]
**Describe the bug**
The consent was automatically selected in the second attempt of sharing 

**To Reproduce**
**prerequisite** : Device A --> Requesting
                            Device B --> Sharing

**Steps :**

1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B 
4. Give consent and share a VC --> verifier captures photo and sharing is successful
5. Repeat step 1,2,3 again

**Current behavior**
Consent is automatically checked-in before even resident selects it.

**Expected behavior**
Consent should only be checked in when resident selects it. 

**Screenshots**

https://user-images.githubusercontent.com/79500509/206977444-d12ddd76-82f4-484a-8e84-0628c14c2da6.MP4

**Smartphone (please complete the following information):**

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (4) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Additional context**
Android bug https://github.com/mosip/inji/issues/324

**Comment by jannahadlaon** [comment]
**Tested on:** 
iOS Build: Inji 0.4.1 (9)  - test flight

**WORKS AS EXPECTED**
@pmigueld @kyanthony @santhoshsunder 

**STEPS**
1. Scan QR CODE on the requesting device to initiate sharing
2. On the Sharing device, click on the consent box and share ID (sharing should be successful)
3. Scan QR CODE on the requesting device again
4. Verify that on the SHARE ID page, the consent box is not pre-ticked.

Devices:
iPhone 11 - iOS 16.1.2

**Screenshot**
https://user-images.githubusercontent.com/102940764/211455711-ecb574ab-fa95-419c-ab45-862c27bf0098.mov

**Comment by Anushree09-N** [comment]
Verified in:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (10) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Working as expected , The consent box is not pre-ticked in the consecutive sharing.

![image](https://user-images.githubusercontent.com/79500509/212601244-862fde38-ed06-48fc-a0a7-712d418d47f3.png)
