### ISSUE TITLE
iOS: "received. Presence verified" message is displayed in history even when verifier captures non face , objects etc

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#326]
**Describe the bug**
"received. Presence verified" message is displayed in history even when verifier captures non face , objects etc

**To Reproduce**
Device A (iOS)-->Requesting
Device B (iOS)-->Sharing

1. Open qr code in Device A
2. open scanner in Device B
3. Scan the qr code from Device B
4. Give consent and select VC to share from Device B
5. click on **Accept Request and choose ID**
6. on Device A click on **Accept Request and verify**

**Current behavior**
"received. Presence verified" message is displayed in history even when verifier captures non face , objects etc

**Expected behavior**
History should display " received. Presence verification failed"..

**Screenshots**

https://user-images.githubusercontent.com/79500509/206985995-4eaee9ff-7bf8-44e9-aea1-c12bebe54d9b.MP4

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (4) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by Sujithbn** [comment]
@Anushree09-N As of now IOS facematch SDK is not available it is mocked. Hence, this will on hold till we complete IOS SDK.

**Comment by Sujithbn** [comment]
@Anushree09-N : This feature is not available now, please close this bug

**Comment by santhoshsunder** [comment]
This issue cant be tested in the current build, since this feature is not implemented yet, we cant test it now, hence we closing this bug for now
