### ISSUE TITLE
Andriod - when the VC sharing is rejected, its not logging in the history

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#329]
**Describe the bug**
While the VC is sharing, if it is getting rejected, its not getting logged in the history

**To Reproduce**
prerequisite : Device A --> Requesting
Device B --> Sharing

Steps :
1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. Select the requird VC to share and perform any type of sharing
5. From device A, click on the reject button

**Expected behavior**
The VC should not be received and this action should be added in history

**Observed**
the VC is getting rejected, but this action is not logged in the history

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/207069721-ebdc691a-c973-4356-9a8c-f2c178e9449c.png)

**Smartphone **

- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1736

**Comment by hegdenitin** [comment]
Created JIRA ticket and will track in JIRA going forward. Closing the bug.
https://mosip.atlassian.net/browse/INJIMOB-1749
