### ISSUE TITLE
iOS : Audit should be logged for rejection of incoming VC by Receiver.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#330]
**Describe the bug** Incoming VC rejection by receiver is not audited.

**To Reproduce**
**Prerequiste**: VC is downloaded and stored in sharing device.
**Device** A - Requesting device (iOS)
**Device** B - Sharing device (iOS)

steps:

1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4. select VC to share and click on "Accept request and choose ID".
5. Device A receives the VC
6. Receiver clicks on **Reject button** on Device A

**Current behavior**
As soon as incoming VC is rejected by receiver we see pop up window with message of VC rejection but history tab does not have history of rejection. 

**Expected behavior**
History tab should have audit for rejection of VC

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/207070859-e17ba1c0-d983-4bca-8d69-bad235cd59ad.png)
![image](https://user-images.githubusercontent.com/79500509/207070921-d8fbde51-839d-4b3a-8617-754a010a08ec.png)
![image](https://user-images.githubusercontent.com/79500509/207070960-d2a096ad-a38f-409c-88e1-c94dfadae714.png)
![image](https://user-images.githubusercontent.com/79500509/207071009-798d3a2e-aeb7-4a37-b720-43ee778a69b0.png)

**Smartphone (please complete the following information):**

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (5) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

**Additional context**
Android bug: https://github.com/mosip/inji/issues/329

**Comment by rakhimosip** [comment]
@kyanthony @pmigueld @Anushree09-N @jannahadlaon 

When the requesting device rejects the credential after viewing it -> log it as '1234567890 received was not saved'

Also, rename the Accept Reject buttons to -> **Save** and **Discard**

No change in logs on the sharer app.

**Comment by jannahadlaon** [comment]
**Tested on:** 
iOS Build: Inji 0.4.1 (9)  - test flight
Android build: COLLAB_io.mosip.residentapp-0.4.1-rc5-19-7f194bd-fix_mosip-324-325-reset-user-consent-newlogic_20230106_1727.apk


**WORKS AS EXPECTED**
@pmigueld @kyanthony @santhoshsunder 

**STEPS**

1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4. select VC to share and click on "Accept request and choose ID".
5. Device A receives the VC
6. Verify that the Accept Reject buttons are renamed to -> `Save` and `Discard`
7. Receiver clicks on Discard button on Device A
8. After rejecting, go to `History`
9.  Verify that the rejected ID was logged as: '1234567890 received was not saved'
10. Verify that there are no changes in History logs in the sharer's device


**Devices:**
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20 - Android 11
iPhone 11 - iOS 16.1.2


**Screenshot**
**iOS**
![IMG_3556](https://user-images.githubusercontent.com/102940764/211484852-21dac775-12f4-49bd-96ff-bef6cc9476d1.jpg)
![IMG_3554](https://user-images.githubusercontent.com/102940764/211484862-e77b2403-5f2f-4acf-8041-59da28fdc3ef.jpg)

**Android**
![Screenshot_20230110-150623_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/211484918-9d87c6fd-85b2-4f0c-baab-78c6407ef70e.jpg)
![Screenshot_20230110-150608_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/211484921-640d18b7-3c21-4d4d-9b51-d18530f9225c.jpg)

**Comment by Anushree09-N** [comment]
Verified in:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (10) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Audit is captured in Receiver's phone when incoming VC is discarded, Buttons are also renamed as per https://github.com/mosip/inji/issues/330#issuecomment-1370858616

![image](https://user-images.githubusercontent.com/79500509/213109186-f719a586-3a4b-435f-b76f-a414db7f6c77.png)

Button names with normal sharing 1. Sharing device 2. Received device.
![image](https://user-images.githubusercontent.com/79500509/213109499-e7618bf8-3d43-4b0b-8f13-af73e7e409ab.png)

![image](https://user-images.githubusercontent.com/79500509/213109542-c37b5106-04de-431f-b12a-a8d544c2e0fe.png)

Button names with Face Auth on Requesting Device 1. Sharing device 2. Received device.

![image](https://user-images.githubusercontent.com/79500509/213109691-049c2365-1ac3-4663-8a61-14fcaad6fabb.png)

![image](https://user-images.githubusercontent.com/79500509/213109747-7610dba3-d373-46f4-9ac8-66e0811055e8.png)
