### ISSUE TITLE
Android - unable to share VC

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#339]
**Describe the bug**
Unable to share VC with other devices 

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device
Device B - Sharing device

steps:
1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4. select VC to share and attempt any method of sharing 

**Expected behavior**
we should able to share VC with other devices without erros

**Observed**  
it is loading for a while and taking back to the camera screen itsell, the VC is not sharing

**Screenshots**
https://user-images.githubusercontent.com/102220709/207839421-f5ab0428-d99f-4a4a-965b-b812c5a595cc.mp4

**Smartphone**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by Anushree09-N** [comment]
Reducing the severity as sharing is working now.

**Comment by santhoshsunder** [comment]
@MonobikashDas yesterday the sharing was completly blocked due to this issue, though several attempts where made we was unable to share VC, but today morning we are seeing that sharing started working, please investigate and let us know the cause for the same

CC: @rakhimosip , @Raginikrishnamurthy

**Comment by santhoshsunder** [comment]
Verified this issue in the new apk, we are unable to share VC because of this same issue, iam submiting the new APK's dsd bellow, and raising the severity to blocker, please look into this issue

**Smartphone**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.mosip.net
- APP link; https://github.com/mosip/inji/actions/runs/3890610244

**Comment by rakhimosip** [comment]
@kyanthony @pmigueld please provide your thoughts here.

**Comment by pmigueld** [comment]
@santhoshsunder Can you re-test with latest build and please make sure both devices have bluetooth and location permissions? Android to Android sharing should be working. 

cc: @kyanthony @rakhimosip @jannahadlaon

**Comment by Sujithbn** [comment]
@santhoshsunder Lets verify this on BLE and share the inputs

**Comment by jannahadlaon** [comment]
**Tested on:** io.mosip.residentapp-0.4.1-rc9-1-bb418e7-develop-newlogic_20230202_1510_universal.apk

I was not able to replicate the issue
@pmigueld @kyanthony @santhoshsunder @rakhimosip 

**Devices**
Samsung Galaxy A23 - Android 12
Samsung Galaxy A20s - Android 11

**Screenshot**

https://user-images.githubusercontent.com/102940764/216268045-58a9c7b9-6bec-4ffc-922c-795e5f5e645b.mov

**Comment by rakhimosip** [comment]
As this is related to GNB, we will deprioritize this.

**Comment by Raginikrishnamurthy** [comment]
GNB is no more a required protocol, this is no more a relevant bug, hence closing it.
