### ISSUE TITLE
Android - while scanning camera is not openning intermittently

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#348]
**Describe the bug**
In the scanning screen the camera is not openning intermittently 

**To Reproduce**
Prerequiste :  camera access should be granted, atleast once VC should be downloaded

steps : 
1. Open the app
2. Open the scan page

**Expected behavior**
The camera should open, and should able to scan requesting phone QR

**Observed**
In the scanning screen the camera is not openning intermittently 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/208597935-93627bf8-ff81-478b-ab39-c642b42f902f.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc5/COLLAB_io.mosip.residentapp-0.4.1-rc5-newlogic_20221216_1728.apk)
iOS: Inji 0.4.1 (7)

**I was not able to replicate this issues** 
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Open app
2. Go to SCAN (second icon from the left)

**Test devices:**
iPhone 11 - iOS 16.1.1
Samsung Galaxy A23 - Android 12

**Screenshot**
https://user-images.githubusercontent.com/102940764/210529871-a8a287b6-1e78-4f3d-b54f-7ba9def8a06d.mp4

**Comment by rakhimosip** [comment]
@jannahadlaon can you please try with a fresh install of the app -> download credential -> then click on the scanner icon?

**Comment by jannahadlaon** [comment]
**Tested on:** 
iOS Build: Inji 0.4.1 (9)  - test flight
Android build: COLLAB_io.mosip.residentapp-0.4.1-rc5-19-7f194bd-fix_mosip-324-325-reset-user-consent-newlogic_20230106_1727.apk


**WORKS AS EXPECTED**
@pmigueld @kyanthony @rakhimosip  @santhoshsunder @Anushree09-N 

**STEPS**
1. Install app
2. download an ID
3. Go to Scanner - If ID is still downloading, `No sharable IDs are available` should appear
4. App should ask permission to access camera - click OK
5. Verify that scanning camera is open and ready to scan.
 
**Devices:**
Samsung Galaxy A23 - Android 12
iPhone 11 - iOS 16.1.2

**Screenshot**
https://user-images.githubusercontent.com/102940764/211744081-3bd56901-b16e-48a4-a9ca-d2fbbea73ce2.mp4
https://user-images.githubusercontent.com/102940764/211744042-5ab97883-41fa-439c-9689-2beccc8f94a4.MP4

**Comment by santhoshsunder** [comment]
verified this issue in the latest build, the issue is not observed anymore, the camera is working properly, and popping up every time in the android, hence closing this bug 

**Smartphone :**
device : redmi k20 pro
ble : 5.0
android : 11
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079
