### ISSUE TITLE
Android - Facing error in scanning page intermittently

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#349]
**Describe the bug**
Facing error intermittently while trying to scan

**To Reproduce**
Prerequiste : camera access should be granted, atleast once VC should be downloaded

steps :
1. Open the app
2. Open the scan page

**Expected behavior**
The camera should open, and should able to scan requesting phone QR

**Observed** 
Facing error intermittently while trying to scan

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/208598981-c55d2ce1-d4e3-4469-b5ab-641f694bd620.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by Anil-kumar-Majji** [comment]
@santhoshsunder I couldn't able to replecate issue like this in app. Recheck it once. Shared screen record in below.

[Screen-record](https://user-images.githubusercontent.com/106086523/210208795-90ff1b9a-75fc-463b-b535-329bce7875d8.mp4)

**Comment by Sujithbn** [comment]
@santhoshsunder : As discussed on triage call, verify this in latest build and keep this bug under observation since we could not replicate and identify the root cause of the issue.

**Comment by santhoshsunder** [comment]
Did not observe this issue on Android devices in (le730bf) BLE build, hence closing the bug
