### ISSUE TITLE
Android - "Use biometrics" button is not working

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#350]
**Describe the bug**
"Use biometrics" button is not working, in the first install

**To Reproduce**
1. Install the apk
2. Open it for the first time 
3. Click on get started
4. Select use bio metrics and authenticate
5. Once the pin page comes, click on back
6. Now again click on the "use biometrics"

**Expected behavior**
The "use biometrics" button should work, and should able to move furthure 

**Observed** 
The "use biometrics" button is clickable but no actions where been performed as shown int the added video below 

**Video**
https://user-images.githubusercontent.com/102220709/208610412-fd8cf28a-a33d-4f49-aa7c-34b2e175b452.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by jannahadlaon** [comment]
**Tested on:** 
Android build: COLLAB_io.mosip.residentapp-0.4.1-rc5-19-7f194bd-fix_mosip-324-325-reset-user-consent-newlogic_20230106_1727.apk

**ISSUE IS STILL PRESENT** 
@pmigueld @kyanthony @santhoshsunder  @Anushree09-N 

**Devices:**
Samsung Galaxy A23 - Android 12

**Screenshot**
https://user-images.githubusercontent.com/102940764/211753840-1b3e01d2-cfcc-499a-af3c-a3d4e14fbff9.mp4

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc7/COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk)

**WORKS AS EXPECTED**
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**

1. Install the apk
2. Open it for the first time
3. Click on get started
4. Select use bio metrics and authenticate
5. Once the pin page comes, click on back
6. Now again click on the "use biometrics"

**Devices**
Samsung Galaxy A23 - android 12

**Screenshot**

https://user-images.githubusercontent.com/102940764/212575681-395dfcf7-e276-4893-b4a4-6173763436e4.mp4

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, now "Use biometrics" button working after install apk first-time, I am attaching the video and the device details below for reference.
Video: -
https://user-images.githubusercontent.com/124761463/224314995-0c457d9e-7a60-4926-9cdd-c30904165053.mp4
![image](https://user-images.githubusercontent.com/124761463/224315321-660bdeb3-50b2-41dc-ab4d-eeb0b018e2aa.png)

Tested in:
Device: Redmi K20 pro
Android Version: 11
BLE version :5.0
Inji app link: https://github.com/mosip/inji/actions/runs/4376878070
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
