### ISSUE TITLE
Inji: Incorrect Naming convention for APK

### ISSUE THREAD

**Issue by Sujithbn** [mosip/inji#362]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional details of the bug**
Description

The application id of the Inji app is 

MOSIP Resident App

It does not follow the naming convention which suggests 

According to [<manifest> | Android Developers](https://developer.android.com/guide/topics/manifest/manifest-element.html#package)

The name should be unique.

The name may contain uppercase or lowercase letters ('A' through 'Z'), numbers, underscores ('_') and period (‘.’).

Individual package name parts may only start with alphabetic letters.

Note : To avoid conflicts with other developers, you should use Internet domain ownership as the basis for your package names (in reverse). For example, applications published by Google start with com.google.

**Comment by santhoshsunder** [comment]
we have changed the App name to Inji. We are changing application Id to io.mosip.inji for Google play store, commit id.
![image](https://github.com/mosip/inji/assets/102220709/6bad69d4-9497-4d4d-a84d-bd28d395aca2)
