### ISSUE TITLE
Accept request and choose ID button in sharing screen should be changed to Accept request and share  

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#364]
**Describe the bug**
Accept request and choose ID button in sharing screen should be changed to Accept request and share  

**prerequisite**: Vc is downloaded and stored in the app 
**Device A** (iOS) : Requesting
**Device B** (iOS) : Sharing

**To Reproduce**
1. unlock the app
2. Open qrcode in Device A
3. Open scanner in Device B 
4. scan qrcode from Device B
5. Select VC in sharing screen

**Current behavior**
Select VC and see that "Accept request and choose ID " button is enabled . As we VC is selected already the word **Choose ID** in the button is not giving the right meaning rather it is making user to assume that VC should be selected in Next step which we selected already.

**Expected behavior**
**Accept request and choose ID** button in sharing screen should be changed to **Accept request and share**  

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/209321554-a726356b-23ce-430e-b508-fde9f975b4cd.png)

**Smartphone (please complete the following information):**

Verified on:

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (7) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by Sujithbn** [comment]
@Anushree09-N This label is invalid and updated in the Purple theme, please verify and close this.

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, in current build 'Accept request and choose ID' button changed to 'Share'. I am attaching the screenshot and the device details below for reference. Hence closing the bug.
Screenshot: -
![image](https://user-images.githubusercontent.com/124761463/225834175-69faf916-86cb-4b27-bca1-1c247baa203d.png)
![image](https://user-images.githubusercontent.com/124761463/225834202-6191f73f-7f89-4589-8464-cbc6df26892d.png)
![image](https://user-images.githubusercontent.com/124761463/225834304-86691fdc-f868-439c-b291-305158d9d5b4.png)
Tested In: -
Device: iPhone 11
OS: 15.6.1
Inji app version: 0.4.1 (24) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
