### ISSUE TITLE
Android - Accept request and choose ID button in sharing screen should be changed to Accept request and share

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#365]
**Describe the bug**
Accept request and choose ID button in sharing screen should be changed to Accept request and share

**prerequisite:** Vc is downloaded and stored in the app
Device A  : Requesting
Device B  : Sharing

**To Reproduce**
1. unlock the app
2. Open qrcode in Device A
3. Open scanner in Device B
4. scan qrcode from Device B
5. Select VC in sharing screen

**Current behavior**
Select VC and see that "Accept request and choose ID " button is enabled . As we VC is selected already the word Choose ID in the button is not giving the right meaning rather it is making user to assume that VC should be selected in Next step which we selected already.

**Expected behavior**
Accept request and choose ID button in sharing screen should be changed to Accept request and share

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/209335581-70d041e7-a665-4a6a-9256-5d536330fb10.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by adityankannan-tw** [comment]
This issue is not valid as new label changes are requested and picked up and merged as part of 28-02-2023 release in issue #589 - https://github.com/mosip/inji/issues/589.

The new changes are,
--> "Accept request and choose ID" to "Share".
--> "Accept request and verify" to "Share with Selfie".

**Comment by ravikp** [comment]
@santhoshsunder - Re-assigning it to you, as this defect isn't applicable you are free to close.

**Comment by santhoshsunder** [comment]
The issue is not applicable in the new build, the button has been removed, hence closing the bug
