### ISSUE TITLE
No prompt is displayed on the Sharing device when Cancel is clicked on the Receiving device during sharing

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#366]
**Describe the bug**
When sharing, the Receiving device clicked on Cancel while Exchanging device info... no prompt is displayed on the sharing device that the sharing was cancelled.
 
**Prerequisite:** VC is downloaded and stored in sharing device.

Device A (iOS): Requesting
Device B (Android): Sharing
 
To Reproduce

- unlock the app
- Scan the QR code on the requesting device from Device B
- On the requesting device, wait for the Cancel button to appear below Exchanging device info... (see screenshot)
- Click Cancel

**Current behavior:** Requested device details are still retained on sharing device even after cancelling the request from Requested Device. 

**Expected behavior**
Prompt about cancelled sharing should appear on the sharing device.

**Screenshots**

![image](https://user-images.githubusercontent.com/79500509/209443810-43654000-3c57-43de-9b2c-6210bd059d64.png)

![image](https://user-images.githubusercontent.com/79500509/209443820-5d37184f-da36-44ef-b3b4-fb5abc734e30.png)

**Smartphone (please complete the following information):**

Verified on:
Device : iPhone 8 & OnePlus Nord 2
OS: 16.0.2
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

**Additional context**
Issue is also replicated on iOS <-> iOS sharing.

Related bug: https://github.com/mosip/inji/issues/250

**Comment by santhoshsunder** [comment]
Tested this issue in the BLE build (le730bf), and the user is intimated with the disconnect pop-up in the wallet, hence closing the bug
