### ISSUE TITLE
Message in sharing device is dismissed automatically with delay in accepting incoming VC .

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#370]
**Describe the bug**
Message in sharing device is dismissed automatically with delay in accepting incoming VC .

Prerequisite: VC is downloaded and stored in sharing device.

Device A (iOS): Requesting
Device B (iOS): Sharing

**To Reproduce**

1. unlock the app
2. Scan the QR code on the requesting device from Device B
3. Select VC and share
4. On the requesting device, Do not accept the incoming VC
5. See the issue on sharing device

**Current behavior**
If receiver delays to accept the incoming VC the message on sharing device is dismissed automatically.

**Expected behavior**
If receiver delays to accept the incoming VC, the **CANCEL** button should be added to sharing message so that Resident will have an option to Cancel the sharing request.

**Screenshots**

https://user-images.githubusercontent.com/79500509/209829701-790dea81-698e-467f-9f0d-87ea51319404.mp4

**Smartphone (please complete the following information):**

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (7) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by jannahadlaon** [comment]
tested on:
iOS: Inji version 0.4.1 (12)

**WORKS AS EXPECTED**
@pmigueld @santhoshsunder @kyanthony 

**Steps** 

1. unlock the app
2. Scan the QR code on the requesting device from Device B
3. Select VC and share
4. On the requesting device, Do not accept the incoming VC
5. See the issue on sharing device

**Devices**
iPhone 11 - iOS 16.1.2
iPhone SE - iOS 15.4

**Screenshot** 

Uploading 20230123_110328 - Trim.mp4…


https://user-images.githubusercontent.com/102940764/213960479-1d2321db-f078-4837-9f0d-440e0c931665.mp4

**Comment by Raginikrishnamurthy** [comment]
This bug cannot be retested as we have limitation in ble to test between iphone as wallet as well as verifier. We can test this once the spec changes are made and ble functions between iphones.
