### ISSUE TITLE
iOS - "Use biometrics" button is not working when resident attempts to set biometric and navigates back without setting passcode

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#371]
**Describe the bug**
"Use biometrics" button is not working when resident attempts to set biometric and navigates back without setting passcode

**To Reproduce**

1. Install the app 
2. click on Get started button
3. click on **use biometrics** and place finger on sensor
4. App prompts to set passcode 
5. Navigate back to previous screen without setting passcode
6. Now click on "Use biometrics" button.

**Current behavior**
"Use biometrics" button is not working when resident attempts to set biometric and navigates back without setting passcode

**Expected behavior**
Use biometrics button should still be clickable and resident to should be able to use this button to set biometrics unlock again

**Screenshots**

https://user-images.githubusercontent.com/79500509/209939396-e7f63747-9a0b-4017-af9f-11a19cab61c9.MP4

**Smartphone (please complete the following information):**

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (7) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Additional context**
Android issue: https://github.com/mosip/inji/issues/350

**Comment by jannahadlaon** [comment]
**Tested on:** 
iOS Build: Inji 0.4.1 (9)  - test flight

**Cannot replicate this issue on iPhone 11**
After biometrics is confirm, there is no way to go back to the `Use biometrics` page
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**Devices:**
iPhone 11 - iOS 16.1.2

**Screenshots**
https://user-images.githubusercontent.com/102940764/211754854-6108d911-8373-4721-9149-a417c2b6d404.MP4

**Comment by Sujithbn** [comment]
@Anushree09-N Please verify this issue again and confirm Jannah on this

**Comment by Anushree09-N** [comment]
@jannahadlaon I was able to replicate this issue . We can get into to call if required.

**Comment by jannahadlaon** [comment]
Tested on:
iOS Build: Inji 0.4.1 (11)

**WORKS AS EXPECTED**
@Anushree09-N @pmigueld @Sujithbn @kyanthony 

**Devices:**
iPhone 11 - iOS 16.1.1
iPhone 6s - iOS 15.7.2

**Screenshots**

https://user-images.githubusercontent.com/102940764/213379476-e1f551cd-f3d1-46ce-90fe-b2b53a4571dd.mov

https://user-images.githubusercontent.com/102940764/213379492-fa831a59-6cc8-410a-a800-f1705ba575e3.MP4

**Comment by Anuranjan14** [comment]
Verified this issue and its working as expected ie Use biometrics button is working when resident attempts to set biometric and navigates back without setting passcode. 
Adding video and device details for the reference.
https://user-images.githubusercontent.com/120705365/224695160-60303c86-4727-40a0-b8be-575cc8c5c5db.MP4
https://user-images.githubusercontent.com/120705365/224695137-b05be18f-289f-4a96-938e-9d8c3a4bdd23.MP4

Device details :
Device: iphone 8
OS: Android 16
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

CommitId:
![image](https://user-images.githubusercontent.com/120705365/224696013-7adc83ef-5615-40d4-80d0-1b004dfa6b4e.png)
![image](https://user-images.githubusercontent.com/120705365/224696058-789f9ad7-a36f-4ae6-a5b0-f1fcc0314151.png)
