### ISSUE TITLE
iOS - Able to unlock the inji app just with biometrics without passcode as a fallback.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#373]
**Describe the bug**
Able to unlock the inji app just with biometrics without passcode as a fallback.
 **prerequisite:**  biometrics is registered in device settings page.

**To Reproduce**

1. Install the app
2. Click on get started
4. click on **use biometrics** place finger on sensor
5. Force quit the app
6. Now reopen the app and click on "unlock application"
7. unlock the app with biometrics

Expected behavior
App should mandate passcode to use biometric unlock feature.

Observed
Able to unlock the inji app just with biometrics without passcode as a fallback.

VIdeo

https://user-images.githubusercontent.com/79500509/209974282-1fee8da3-7fdb-41df-a32e-9492df297435.MP4

Smartphone :

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (7) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by Anushree09-N** [comment]
Android issue: https://github.com/mosip/inji/issues/351

**Comment by jannahadlaon** [comment]
**Tested on:** 
iOS Build: Inji 0.4.1 (9)  - test flight

**WORKS AS EXPECTED**
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**

1. Install the apk
2. Open it for the first time
3. Click on get started
4. Select use bio metrics and authenticate
5. Force quit the app
6. Now reopen the app and click on "unlock application"
7. Authenticate with bio metrics
8. Verify that pin has to be set up

Devices:
iPhone 11 - iOS 16.1.2

**Screenshot**
Uploading RPReplay_Final1673336477.MP4…

**Comment by Anushree09-N** [comment]
Verified in :

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Working as Expected. It prompts to set pin when app is closed forcefully after clicking on "Use biometrics" button.


https://user-images.githubusercontent.com/79500509/212615865-6496fb55-6dbf-476c-8e02-7dd9565891e6.MP4
