### ISSUE TITLE
Android - APk became slower 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#375]
**Describe the bug**
The Inji app became slower to use

**Observed:**
The APK used to be fast before the sharing online and offline feature is implemented, then from that the APK became slower and slower, and sharing VC takes more thean 30 sec to share

**Expected behavior**
The APK should be fast as before

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by ravikp** [comment]
@santhoshsunder - what is the commit or github tag of the build?

**Comment by Sujithbn** [comment]
@kyanthony  : Please review and share your thoughts on this bug

**Comment by Sujithbn** [comment]
@santhoshsunder, @Anushree09-N : Is it still taking 30 Sec to share the VC, please run the test case for few times and share the Average time taken in this window.

**Comment by pmigueld** [comment]
I've done all that I can and I think this slowness is on Google Nearby Messages itself.

**Comment by jannahadlaon** [comment]
**Tested in:**
Android: [io.mosip.residentapp-0.4.1-rc8-newlogic_20230123_1650_universal.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc8/io.mosip.residentapp-0.4.1-rc8-newlogic_20230123_1650_universal.apk)
iOS: INJI 0.4.1 (15)

**WORKS AS EXPECTED** @pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**Screenshots**

https://www.loom.com/share/207e516122c64fc98837b951b79d6f1c?t=10

**Comment by santhoshsunder** [comment]
Tested this issue in the BLE build (le730bf), and did not observe the APK being slower now, hence closing the bug
