### ISSUE TITLE
Android - mosip logo is blur in APK

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#376]
**Describe the bug**
mosip logo is blur in inji APK

**To Reproduce**
1.Open the app
2.Wait on the "Unlock application" button screen

**Expected behavior**
The mosips logo should be in good clarity and sharp

**Observed :** 
The mosip logo is blur on that screen, as shown in the screen shot below 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/210203653-fb511e63-e571-40a1-9226-6856da795e29.png)

**Smartphone (please complete the following information):**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by krishnakumar4a4** [comment]
The Logo blur is fixed as part of this issue https://github.com/mosip/inji/issues/397. Please confirm and close accordingly.

**Comment by santhoshsunder** [comment]
Tested this issue in the BLE build (le730bf), the logo is sharp now, hence closing the bug
