### ISSUE TITLE
Android - orange elements still in purple theme apk

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#377]
**Describe the bug**
Orange theme elements still visible in purple theme apk

**Expected behavior**
The orange elements should not be present in the purple theme apk 

**Observed:**
observed few orange theme elements is still present in the purple APK

**Screenshots**
the curser still in orange colour 
![image](https://user-images.githubusercontent.com/102220709/210223978-2e220b11-f9a5-40b7-b9e2-ced47e4fe066.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by srikanth716** [comment]
Fixed by changing the input selection color in purple theme. Pr(https://github.com/mosip/inji/pull/418) raised

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/49f9ae3d-3ffc-45d9-aa78-6b22aa2d8c60)
