### ISSUE TITLE
Android - Try again button is missing when giving concern is failing 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#379]
**Describe the bug**
Try again button is missing when giving concern is failing while sharing 

**To Reproduce**
prerequisite : Device A --> Requesting
Device B --> Sharing

Steps :
1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. In the sharing ID screen in device B, select the UIN card you want share
5. And click on the "I give concernt" click box and share 
6. Now from the Device B try to scan someone else photo, who's photo is not provided
7. wait till the face fails it will pop up error message

**Expected behavior**
We should able to see try again button in the error message

**Observed :**
Try again button is missing when giving concern is failing while sharing 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/210352294-ded3a8bd-baed-4ed3-823b-4f34d6d5a553.png)

**Smartphone (please complete the following information):**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Additional context**
we are receiving try again button while "accept and verify" feature is used 
![image](https://user-images.githubusercontent.com/102220709/210352606-fc46dce5-7016-4d96-9498-e57bd9984bbd.png)

**Comment by pmigueld** [comment]
@rakhimosip can you confirm if presence check via the receiver phone is allowed to retry? According to the spec [here](https://github.com/mosip/inji/issues/55) if the verification fails we still save the VC but log in the audit as "received. Presence verification failed"

**Comment by rakhimosip** [comment]
@kyanthony @santhoshsunder yes it will be good to give the option of 'Retry' to the verifier as well. 
On click of Retry -> the camera can open again and let the requestor capture the face image.

**Comment by jannahadlaon** [comment]
tested on:
Android: [io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc8/io.mosip.residentapp-0.4.1-rc8-newlogic_20230120_1937_universal.apk)

**WORKS AS EXPECTED**
@pmigueld @santhoshsunder @kyanthony 

**Steps** 
1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. In the sharing ID screen in device B, select the UIN card you want share
5. And click on the "I give concernt" click box and share
6. Now from the Device B try to scan someone else photo, who's photo is not provided
7. wait till the face fails it will pop up error message

**Devices**
Samsung Galaxy A23 - android 12
Samsung Galaxy A20s - android 11

**Screenshot** 

https://user-images.githubusercontent.com/102940764/213957681-4ca4b89a-7a5f-4320-8d0a-44a8a047ee24.mov

**Comment by santhoshsunder** [comment]
Verified this issue QA-1201-b2 env, the "try again" button is coming in the receivers end as expected, hense closing the bug

**Screenshot :**
![image](https://user-images.githubusercontent.com/102220709/216964768-3e0c83b7-8e5a-4cba-9785-1fab4f4848e4.png)

**Smartphone :**
Device: Pixel 6
OS: Android 13
BLE version: 5.2
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4062244892
