### ISSUE TITLE
Android - Error message is not proper when the face auth is failing 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#380]
**Describe the bug**
Error message is not proper when the face auth is failing while sharing

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device
Device B - Sharing device

steps:
1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4. select VC to share and attempt any two face auth method of sharing
5. Now from the Device B try to scan someone else photo, who's photo is not provided
6. Wait till the face fails it will pop up error message

**Expected behavior**
The error message should be proper and should be understandable by public 

**Observed**
 Error message is not proper when the face auth is failing while sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/210355254-ae87a858-d1e0-43f5-bff8-407091d520f2.png)
![image](https://user-images.githubusercontent.com/102220709/210355265-00b2e55a-1ca2-4f7a-af49-b9b66a0f5a00.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by vijay151096** [comment]
@santhoshsunder , we are currently showing the below message when the face auth is failed.
<img width="414" alt="Screenshot 2023-04-13 at 3 53 33 PM" src="https://user-images.githubusercontent.com/94220135/231732744-1c8acddc-6ac7-4b44-a621-62e600e7fd53.png">
please do check if the error message is fine, and close the issue

**Comment by santhoshsunder** [comment]
Tested this issue in the BLE build (le730bf), we are seeing the user-friendly message when the face auth is failed in android, hence closing the bug
