### ISSUE TITLE
Android - spelling mistake in the tips/user guide note

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#383]
**Describe the bug**
spelling mistake in the tips note in the first install

**To Reproduce**
1. Install the APK and the open it
2. Add the Authentication method 
3. Head to the home page
4. Once the tip page pop-up, move to easy sharing 

**Expected behavior**
All the spelling should be correct every where

**Observed :**
The word swiftly is spelled wrongly in the tips note in the first install

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/210765630-d4eec3db-ac45-4b8e-8957-4ca2bf296d32.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by Anil-kumar-Majji** [comment]
The above issue was fixed and submitted respective PR #391.

**Comment by Anushree09-N** [comment]
Verified in:

Device: iPhone 8 
OS: 16.0.2 (20A380)
Inji app version: 0.4.1 (10) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Spelling is now corrected.

![image](https://user-images.githubusercontent.com/79500509/212653941-306663f4-a986-49f7-a47f-56815a5a15c2.png)
