### ISSUE TITLE
Android - The biometrics button is not working properly 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#384]
**Describe the bug**
The biometrics button is not working properly in the profile page

**To Reproduce**
1. Open the app
2. Go to the profile section 
3. Click on the bio-metric button multiple times 

**Expected behavior**
The button should work properly, how ever times attempts is attempted

**Observed :**
When the button is clicked multiple times, the button getting stuck in off

**Video :**
https://user-images.githubusercontent.com/102220709/210767916-fb466940-8467-45a9-b862-d1c54fb52f3a.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: [COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc7/COLLAB_io.mosip.residentapp-0.4.1-rc7-newlogic_20230113_1728.apk)

**WORKS AS EXPECTED**
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. Install the app
2. set the passcode and login
3. click on profile icon
4. click on biometrics toggle button to enable biometrics unlock
5. Disable the biometrics unlock / disable the toggle button and try to enable again

**Devices**
Samsung Galaxy A23 - andriod 12

**Screenshot**

https://user-images.githubusercontent.com/102940764/212575148-b16e9808-d25f-4378-a7f5-b10372da8ceb.mp4

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, now "Biometrics unlock" toggle button working as expected, I am attaching the video and the device details below for reference.

Video:
https://user-images.githubusercontent.com/124761463/224325206-fcfd4139-66d1-47e2-b257-776114b27f5a.mp4
![image](https://user-images.githubusercontent.com/124761463/224326157-e44154d3-f3fa-4971-a727-1d82b084ff63.png)

Tested in:
Device: Redmi K20 pro
Android Version: 11
BLE version :5.0
Inji app link: https://github.com/mosip/inji/actions/runs/4376878070
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
