### ISSUE TITLE
Android - The VC Edit tag/Rename option should have limitation to user inputs

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#385]
**Describe the bug**
The VC retag should have limits, the tag is streching the whole VC

**To Reproduce**
1. Download a VC
2. Open the VC in detailed view
3. Click on the 3 buttons in the right top corner
4. Click on the rename button
5. Enter a hugh amount values(ex. few paragraphs) and click save 

**Expected behavior**
The VC retag should have limits

**Observed :**
Seems like there is no limits to the retag, and its streching the VC card and making the edges blur as shown in the screenshot added bellow 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/210772694-13fb30d1-5f58-4198-a4de-db7d398d207c.png)
![image](https://user-images.githubusercontent.com/102220709/210772897-16144eb5-e382-4c56-96c4-9b576644d5f2.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by Sujithbn** [comment]
This is not prioritized for beta release.

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
