### ISSUE TITLE
Android - VC stuck at loading state in Mobile ID app

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#393]
**Describe the bug**
Unable to download VC from mobile APK, VC stuck at loading state

**To Reproduce**
1.Unlock app
2.Enter valid UIN and request for VC

**Expected behavior**
without any errors we should be able to download VC

**Current behavior**
Unable to download VC, VC stuck in loading state

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/211017430-eb48e0c7-dce5-4e9a-90e5-8cd64a18c195.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://github.com/mosip/inji/actions/runs/3854157494

**Additional context :** 
UIN used : 8527487298, 3509652451

**Comment by Raginikrishnamurthy** [comment]
@Sujithbn Please provide the root cause for this issue to be verified.

**Comment by santhoshsunder** [comment]
we dont have UIN download anymore, with VID we don't face this issue, hence closing this
