### ISSUE TITLE
iOS: Unable to enable the biometric using toggle in the profile from second attempt.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#394]
**Describe the bug**
Unable to enable the biometric using toggle in the profile from second attempt.

**To Reproduce**
1. Install the app
2. set the passcode and login
3. click on profile icon
4. click on biometrics toggle button to enable biometrics unlock
5. Now disable the biometrics unlock / disable the toggle button and try to enable again 

**current behavior**
Able to enable biometric unlock in profile section only once it's failing in second attempt.

**Expected behavior**
Resident should not have restriction to enable biometric unlock in profile section 

**Screenshots**

https://user-images.githubusercontent.com/79500509/211040309-e181bde9-2fa6-4260-a6a7-70c63bf38ddf.MP4

**Smartphone (please complete the following information):**

- Device: iPhone 8
- OS: 16.0.2 (20A380)
- Inji app version: 0.4.1 (7) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Additional context**
Android issue: https://github.com/mosip/inji/issues/384

**Comment by jannahadlaon** [comment]
**Tested on:**
iOS TestFlight -Inji  0.4.1 (11)

**WORKS AS EXPECTED**
@pmigueld @kyanthony @santhoshsunder @Anushree09-N 

**STEPS**
1. Install the app
2. set the passcode and login
3. click on profile icon
4. click on biometrics toggle button to enable biometrics unlock
5. Disable the biometrics unlock / disable the toggle button and try to enable again

**Devices**
iPhone 11 - iOS 16.1.2

**Screenshot

https://user-images.githubusercontent.com/102940764/212575213-88118c93-bba6-4d3f-9ed2-82c2c4ea766f.MP4

**

**Comment by Anuranjan14** [comment]
Verified this issue and now user is able to enable biometrics toggle button multiple times. Hence closing.

Screen recording:
iphone 11:-
https://user-images.githubusercontent.com/120705365/225920575-7c6fae9e-e3e2-499d-8a2e-e16b6788b262.MP4
iphone 8:-
Uploading CYDC1309.MP4…

Device details:
Device: iphone 8
OS: Android 16
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

Device: iphone 11
OS: Android 15
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

CommitId:
![image](https://user-images.githubusercontent.com/120705365/225920381-b8d13d11-2d02-438f-b6af-9288ab012e64.png)
