### ISSUE TITLE
iOS : The VC Edit tag/Rename option should have limitation to user inputs

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#395]
**Describe the bug**
The VC retag should limit the user inputs, the tag is stretching the whole VC

**To Reproduce**

1. Download a VC
2. Open the VC in detailed view
3. Click on the ellipses in the right top corner
4. Click on the **Rename button**
5. Enter a ample amount text (ex. few paragraphs) and click save

**Observed :**
As input text increases the VC card  is stretching out and making the edges blur (text hidden)  as shown in the screenshot added below

**Expected behaviour:**
Rename field should limit the input character from user.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/211046159-dce893ba-fd28-4818-b21e-7ea711ed5c41.png)

![image](https://user-images.githubusercontent.com/79500509/211046201-2c3b9a04-04cf-4b12-8a0c-c963b4415135.png)

**Smartphone :**

- Device: iPhone 11
- OS: 15.6.1
- Inji app version: 0.4.1 (7) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

Android issue : https://github.com/mosip/inji/issues/385

**Comment by ravikp** [comment]
Waiting for input from @nayakrounak

**Comment by vijay151096** [comment]
Added the limitation to VC Tag Characters length in the Rename Option, and confirmed the same with @nayakrounak.
So the Tags can have a Maximum of 12 Characters. 

Here are the screenshots: 

**Tags in VC Details Screen :** 
<img width="412" alt="Screenshot 2023-03-22 at 11 45 58 AM" src="https://user-images.githubusercontent.com/94220135/226817964-b0739fb9-202e-486a-b820-8adf5b2f83d6.png">

**Tags in VC Listing :** 
<img width="405" alt="Screenshot 2023-03-22 at 11 46 15 AM" src="https://user-images.githubusercontent.com/94220135/226818020-97ddd6c6-a71c-4104-a206-ea4ccf67ce47.png">

**Tags character Length cannot Exceed Beyond 12 Characters :** 
<img width="419" alt="Screenshot 2023-03-22 at 11 47 23 AM" src="https://user-images.githubusercontent.com/94220135/226818213-70128a7a-6764-415c-89a8-3aed5b3d9b9e.png">

**Comment by krishnakumar4a4** [comment]
> Added the limitation to VC Tag Characters length in the Rename Option, and confirmed the same with @nayakrounak. So the Tags can have a Maximum of 12 Characters.
> 
> Here are the screenshots:
> 
> **Tags in VC Details Screen :** <img alt="Screenshot 2023-03-22 at 11 45 58 AM" width="412" src="https://user-images.githubusercontent.com/94220135/226817964-b0739fb9-202e-486a-b820-8adf5b2f83d6.png">
> 
> **Tags in VC Listing :** <img alt="Screenshot 2023-03-22 at 11 46 15 AM" width="405" src="https://user-images.githubusercontent.com/94220135/226818020-97ddd6c6-a71c-4104-a206-ea4ccf67ce47.png">
> 
> **Tags character Length cannot Exceed Beyond 12 Characters :** <img alt="Screenshot 2023-03-22 at 11 47 23 AM" width="419" src="https://user-images.githubusercontent.com/94220135/226818213-70128a7a-6764-415c-89a8-3aed5b3d9b9e.png">

Quoting previous reply from @vijay151096 about the fix details. Fix is done as part of 24-03-2023 release.

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by Anushree09-N** [comment]
**Verified in :**
iphone 7 | iphone 15.6 BLE 4.2

 **app commit id:** 
![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

Renaming text field is restricted to 12 characters . Working as expected .

Uploading BTRW2129.MP4…
