### ISSUE TITLE
Unable to download credentials displayed "Network request failed" error message

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#399]
**Describe the bug**
Unable to download credential displayed "Network request failed" error message

**To Reproduce**

1. Install the inji app from Testflight
2. click on Add ID button
3. Enter valid UIN
4. click on Get ID button.
 
**Current behavior**
Unable to download credential with valid UIN displayed "Network request failed" error message. Phone was connected to Wi-Fi even then we got above error message.

**Expected behavior**
VC download should be successful in the app

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/211813797-a45630ab-ad63-4608-ba4a-179f89f45220.png)

**Smartphone (please complete the following information):**

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (7) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
UIN : 8527487298

**Comment by Sujithbn** [comment]
@Anushree09-N While generating the IOS build proper environment URL was not updated due to which it was not pointing to the right environment and displayed error. Post updating the URL https://api.qa-1201-b2.mosip.net/residentmobileapp while generating the build, issue is resolved.

**Comment by Anushree09-N** [comment]
Verified in :

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (10) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Able to download and share credentials

![image](https://user-images.githubusercontent.com/79500509/212089488-9b01bbd7-73c1-4e67-80d9-ba3e82164a0a.png)
