### ISSUE TITLE
A resident should be able to use their phone and prove their presence using the resident mobile app - SCOPE: Using real SDK

### ISSUE THREAD

**Issue by rakhimosip** [mosip/inji#42]
**Problem statement:**

A resident should be able to use their phone and prove their presence using the mobile app (selfie-based auth)

**Prerequisite:**

- The resident should have a smartphone with secure hardware

- The resident installs and sets up the mobileID app on their smartphone
 

**Proposed solution:**

- The resident installs the mobile app on their smartphone and downloads credentials (VC)

- After initiating share by scanning the QR code on relying party’s phone and accepting the request to share, the resident chooses the 'Verify presence and share' option

- The app brings up the camera and captures the resident’s picture automatically and then initiates a match with the picture in the selected credential using the SDK.

    - ~~On a successful match, the app creates a verifiable presentation and also signs it.~~
    
    - A successful match and sharing initiated message also will be shown
     
    - A failed match will be conveyed by a corresponding message
     
    - The resident should be able to try again in case of a failed match
     

- This info should also be displayed in the history tab
  - The audit log for verification and sharing should be different from a normal sharing flow.  
  - The audit can be
     -  _'9721931281 verified and shared'_ -> when face-auth successful and sharing complete
     -  _'9721931281 verification failed'_ -> when face-auth fails and no sharing happens

**NOTE: Creating a `Verifiable Presentation` when a successful auth happens has been removed from the scope of this feature.**

**Process flow:**
![image-20220409-023120](https://user-images.githubusercontent.com/86289097/177299526-8d8a727e-764e-476b-a196-f1cfd70bc997.png)

**Proposed UI of resident’s phone:**

This is similar to the workflow when the resident shares VC with an added step of selfie auth.

![image-20220409-022758](https://user-images.githubusercontent.com/86289097/177299418-bed98c45-bc82-479e-906b-e1a79d2eb164.png)

**Open questions**

- Where will the auth status be stored? In VC?

- How will additional metadata be stored and VC signed?

**Tech Notes:**

- Re-use already available SDKs for selfie auth

**Comment by rakhimosip** [comment]
As per discussion today, -> Creating a Verifiable Presentation when a successful auth happens has been removed from the scope of this feature.

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk
iOS: inji 0.4.1 (3) (TestFlight)

**Assigned back to dev**
@pmigueld @kyanthony @danicaerediano 

**Issue**:
If consent is not ticked, clicking the button `Accept request and choose ID` will not do anything, 

**Expected**:
`Accept request and choose ID` should still function even if consent is not ticked

**Screenshot**
https://user-images.githubusercontent.com/102940764/203708986-eab428f4-5d5f-4ebf-acd7-0a6a66b290e7.mov

**Comment by rakhimosip** [comment]
@pmigueld @Anushree09-N based on our discussion today, I have updated the story with the following note:

- This info should also be displayed in the history tab
  - The audit log for verification and sharing should be different from a normal sharing flow.  
  - The audit can be
     -  _'9721931281 verified and shared'_ -> when face-auth successful and sharing complete
     -  _'9721931281 verification failed'_ -> when face-auth fails and no sharing happens

**Comment by Anushree09-N** [comment]
> * The audit log for verification and sharing should be different from a normal sharing flow.
> * The audit can be
>   
>   * _'9721931281 verified and shared'_ -> when face-auth successful and sharing complete
>   * _'9721931281 verification failed'_ -> when face-auth fails and no sharing happens

@rakhimosip The history of verification should be stored in the device that verify's the presence or both Sender and Receiver phone should have history of verification ?

**Comment by rakhimosip** [comment]
@Anushree09-N 
If verification happened on the resident's phone -> it should be logged as an activity on that phone
For the other flow please refer to https://github.com/mosip/inji/issues/55

**Comment by Raginikrishnamurthy** [comment]
Scope of testing has been around only for Android apk using real SDK. The ios has been tested only with mock.
