### ISSUE TITLE
A resident should be able to setup biometric unlock feature on their app

### ISSUE THREAD

**Issue by rakhimosip** [mosip/inji#44]
**Proposed solution**
- During the first installation and setup, the user should be able to select between passcode and bio unlock options for the app.

- If the user selects bio to unlock, an option to record biometrics is presented based on the device setting and model.

- After the biometric is recorded the app prompts the user to set a passcode to unlock. This is a fallback mechanism in case bio unlock is disabled.

- A user can enable/disable bio unlock at any point. They can use the 'Biometric unlock' option in the Profile section of the app.

**Implementation Notes:** 
- While setting up biometric unlock the app only stores a flag that says this feature is enabled (no actual biometric data is stored in the app).

- For bio unlock the app uses Expo's Local Authentication module (https://docs.expo.dev/versions/latest/sdk/local-authentication/). It uses the same biometric configuration that the user setup for unlocking their phone.

**Linked Issues:**
https://github.com/idpass/idpass-mosip-resident-app/issues/16
https://github.com/idpass/inji/issues/27

**Linked Bugs**
https://github.com/idpass/inji/issues/167
https://github.com/idpass/inji/issues/196

**Comment by Raginikrishnamurthy** [comment]
The below activities are completed for the biometric unlock feature:
1. test case development and review completed
2. test case execution completed
3. no blocker and critical bugs open
Hence, closing the story.
