### ISSUE TITLE
Refactor Tuvali Gatt Service characteristics to match the Spec

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#444]
**Is your feature request related to a problem? Please describe.**
In Tuvali, Names and structure of Gatt Characteristics are not matching to Spec names. Which is creating confusion for Spec Admins to map it to Tuvali

**Describe the solution you'd like**
Refactor following recognized items and anything else that makes Tuvali match updated Spec changes
1. Rename Characteristic names to names specified in Spec
2. Split Semaphore Characteristic to Transfer Summary Request and Transfer Summary Report

**Additional context**
Look at the Spec Draft for required context: https://mosip.atlassian.net/wiki/spaces/ENGG/pages/962461697/Bluetooth+DRAFT+BLE+Transfer

**Comment by PuBHARGAVI** [comment]
- Unused properties and permissions of characteristic uuid's has been removed part of this issue only
- issue #485 is covered in this issue
- changes related to this issue are commited in rename-uuid branch and it's commit id is: 2d02b17ae4f91f81713a940a6fb7dae91bb553db

**Comment by PuBHARGAVI** [comment]
This task changes are merged into develop

**Comment by krishnakumar4a4** [comment]
This task changes were released on 14/15th Feb release on INJI. 
Commit id for the same https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12

**Comment by Sujithbn** [comment]
Please verify the BLE sharing functionality as a part of testing.

**Comment by damodarguru** [comment]
Multiple attempts of sharing is working. I attached screenshots for reference.

Screenshots: -
![image](https://user-images.githubusercontent.com/124761463/226614582-5bbaf4c6-82e2-47ba-a292-aba80d6236b0.png)
![image](https://user-images.githubusercontent.com/124761463/226614652-33b457eb-1d0b-4396-92b5-1961530005f1.png)
![image](https://user-images.githubusercontent.com/124761463/226614697-b0cee0aa-dd9b-47e9-9bc8-31a734a239e1.png)

Verified in: -
Device A: Vivo Y73
Android Version: 12
BLE version: 5.0
Inji app link: https: https://github.com/mosip/inji/actions/runs/4447486079

Device: Redmi 10 lite
Android Version: 10
BLE version :5.0
Inji app link: https://github.com/mosip/inji/actions/runs/4447486079
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
