### ISSUE TITLE
Android - History timings could be more precise

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#445]
**Describe the bug**
History timings could be more precise 

**To Reproduce**
1. Authenticate the app and enter into it
2. perform any action (like: downloading VC, sharing VC)
3. go to the history page

**Expected behavior**
If the audits are marked with exact time as when the action is performed, it will be more user friendly 

**Observed behavior** 
The audits are logged as hours ago format which is hard to have track 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/213620519-4307aff6-4b9c-4b06-87c0-1aefe1c80d8b.png)

**Smartphone (please complete the following information):**

- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://github.com/mosip/inji/actions/runs/3854157494

**Comment by hegdenitin** [comment]
Created JIRA ticket and will track in JIRA going forward. Closing the bug.
https://mosip.atlassian.net/browse/INJIMOB-1748
