### ISSUE TITLE
iOS : unable to activate VC for online login.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#450]
**Describe the bug**
unable to activate VC for online login.

**To Reproduce**
1. Install the app
2. Download VC
3. click on "**Activation pending for online login**" button -> User will be taken to detail view page which has **activate** button
4. click on **Activate** button
5. pop up displayed with confirm button
6. click on confirm button

**Current behavior**
 unable to activate VC for online login after giving confirmation in detail view page.

![image](https://user-images.githubusercontent.com/79500509/213634072-293f7c8a-eb02-4324-8d48-d083cf44a835.png)

**Expected behavior**
VC Activation for online login should be successful.

**Smartphone (please complete the following information):**

Device: iPhone 8 
OS: 16.0.2 (20A380)
Inji app version: 0.4.1 (12) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

**Screen Recording**
https://user-images.githubusercontent.com/79500509/213635152-ae6561d8-5b0c-4747-88b4-edf1210f108d.MP4

------------------------------------------------------------------------------------------------------
Unable to activate VC in all available iOS devices.

Device: iPhone 11 , iPhone 7
OS: 15.6.1,  15.6
Inji app version: 0.4.1 (32) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

**commit id of the app :**
![IMG20230327113117](https://user-images.githubusercontent.com/79500509/227854180-3b522fdf-d91a-44f4-b73d-0cce50988ee1.jpg)

**commit id:** 1e730bf

![IMG20230327113726](https://user-images.githubusercontent.com/79500509/227854918-4fe5034a-1ce7-402c-8c8e-398ae9d1007a.jpg)

**Note** : Indian time was set in all devices.

**Comment by santhoshsunder** [comment]
this issue is occuring in android too, i am linking that bug below
https://github.com/mosip/inji/issues/452

**Comment by Anushree09-N** [comment]
wallet binding feature is still blocked with below error:

https://user-images.githubusercontent.com/79500509/213752929-3961b55f-0947-41b4-a396-80e3881b6e69.MP4

![image](https://user-images.githubusercontent.com/79500509/213753173-3aa417f6-eb83-4902-b0db-ed74a85cf32f.png)

**Comment by srikanth716** [comment]
I was not able to replicate this issue from the latest code in android. Activation for online login is working fine. Find the attachment below
![Screenshot_1674472264](https://user-images.githubusercontent.com/97477121/214025976-075b59a1-4e0d-46d7-addc-e7f4946c0ace.png)
![Screenshot_1674472398](https://user-images.githubusercontent.com/97477121/214026050-97f7c181-e33b-4d43-b66a-4036a74e8d87.png)

**Comment by Anushree09-N** [comment]
@MonobikashDas @srikanth716 Able to replicate the issue in latest iOS build 0.4.1 (12) . 
![image](https://user-images.githubusercontent.com/79500509/214553441-de43dd13-d027-43e0-a846-37af99a12127.png)

**Comment by Anushree09-N** [comment]
Unable to activate VC for online login 

iOS app version:

![image](https://user-images.githubusercontent.com/79500509/222720152-398f1aae-447b-4dd4-9c1d-73b9d1660dfa.png)

Android app version:

![image](https://user-images.githubusercontent.com/79500509/222720442-79b8910b-bc05-43ea-a773-e50ef36afff8.png)


https://user-images.githubusercontent.com/79500509/222719810-ecb508a3-5ba1-4c6f-8bdb-33928dfdb82a.mp4

![image](https://user-images.githubusercontent.com/79500509/222720646-4176d4c3-0efb-46cc-9bff-ad80eb1c6624.png)
 VID used: "3719087217936915".

**Comment by Anushree09-N** [comment]
Reducing the severity of the ticket as the issue is only specific in iPhone 8

**Comment by lsivanand** [comment]
@MonobikashDas IMO it has to work irrespective device time zone, as it will be a global app..

**Comment by vijay151096** [comment]
Here is the Screen Shots for the Error We faced while Binding the VC when the Time Zone is set to Washington DC and TimeFormat is 24 Hours. 

**iOS :**  - Failing in the binding-otp 

<img width="1608" alt="Screenshot 2023-03-30 at 11 03 17 AM" src="https://user-images.githubusercontent.com/94220135/228752340-74d7c788-4bad-4ac6-92fc-21444eda4cb7.png">
<img width="1708" alt="Screenshot 2023-03-30 at 11 04 49 AM" src="https://user-images.githubusercontent.com/94220135/228752367-3e296e93-d553-444c-8410-3760d2a7015c.png">


**Android :**  - successfully binding otp
<img width="1665" alt="bindingVC_TZ_4_Android" src="https://user-images.githubusercontent.com/94220135/228752405-74594d51-3cfa-42e0-95c3-7c06e0fcd28a.png">
<img width="1640" alt="bindingVC_TZ_3_Android" src="https://user-images.githubusercontent.com/94220135/228752438-4df0c7f2-710c-4318-bf0e-d52f4a81b7a1.png">

As Discussed Please Check into this Issue. @ase-101

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/d6282f4f-9761-43e4-8d3d-4e808a7ea079)
