### ISSUE TITLE
Android - subsequent VC share not working.

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#451]
**Describe the bug**
subsequent VC share not working in this new ble apk 

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device
Device B - Sharing device

steps:
1. open qr code in Device A
2. open scanner in Device B
3. scan the qrcode from Device B
4. Select VC to share and share (attempt any type of sharing method)

**Expected behavior**
The VC should be sharable with other devices with out fail

**Current behavior**
subsequent VC share not working in this new ble apk 

**Video**
https://user-images.githubusercontent.com/102220709/213643402-ab089317-5909-4591-bdfa-ad4a32727285.mp4

**Smartphone:**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://mosip.atlassian.net/browse/DSD-2033

**Comment by ravikp** [comment]
This isn't a BLE build. Next time onwards please add the commit information that you see at the bottom of the profile page. To confirm whether it is a BLE build or not, check the profile page and it should have "Powered by message....".

**Comment by rakhimosip** [comment]
We will not be addressing GNB issues for beta release

**Comment by Raginikrishnamurthy** [comment]
GNB is no more a relevant protocol. Since sharing is working in ble build, closing this bug.
