### ISSUE TITLE
Android - unable to activate VC for online login.

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#452]
**Describe the bug**
Unable to activate VC for online login.

**To Reproduce :**
1. Install the app
2. Download VC
3. click on "Activation pending for online login" button -> User will be taken to detail view page which has activate button
4. click on Activate button
5. pop up displayed with confirm button
6. click on confirm button

**Current behavior**
unable to activate VC for online login after giving confirmation in detail view page.

**Expected behavior**
VC Activation for online login should be successful.

**Screenshot :**
![image](https://user-images.githubusercontent.com/102220709/213646121-3b47bd40-7b29-4d74-b172-f4eee9bc6627.png)

**smartphone:**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://mosip.atlassian.net/browse/DSD-2033

**Comment by ravikp** [comment]
Not related to the BLE.

**Comment by srikanth716** [comment]
I was not able to replicate this issue from the latest code in android. Activation for online login is working fine. Find the attachment below
![Screenshot_1674472264](https://user-images.githubusercontent.com/97477121/214025976-075b59a1-4e0d-46d7-addc-e7f4946c0ace.png)
![Screenshot_1674472398](https://user-images.githubusercontent.com/97477121/214026050-97f7c181-e33b-4d43-b66a-4036a74e8d87.png)

**Comment by Sujithbn** [comment]
@santhoshsunder : If you are not able to replicate this in the latest build, can you close this defect.

**Comment by Raginikrishnamurthy** [comment]
@Sujithbn Once a bug has been surfaced irrespective of being intermittent, we need to analyze to the root cause. Without having the issue debugged, we will not be able to close the bug. Lets have it open for analysis until release.

**Comment by santhoshsunder** [comment]
Verified this issue in the new build, and the issue is still replicable intermittently, iam attaching the screenshot and the other details bellow 

Screenshot :
![image](https://user-images.githubusercontent.com/102220709/223077472-c731a4bb-2001-48cf-bab4-cde18a9de969.png)

Mobile details : 
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4293687772

**Comment by santhoshsunder** [comment]
Tested this issue in the new build, and the issue is still occurring, the binding is failing still intermittently, hence reopening this bug

**Comment by santhoshsunder** [comment]
Verified this issue in the new build, and the issue is still replicable and totally blocked in all android devices, I am changing the severity to blocker, I am attaching the screenshot and the other details bellow

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/227846414-324cfcb1-5205-44d0-93f7-4d821b952a59.png)

Mobile details :
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Comment by santhoshsunder** [comment]
Verified this in the new build, the issue is not observed anymore, we are able to activate the VC successfully, hence closing this bug

Screenshot :
![image](https://user-images.githubusercontent.com/102220709/228520953-7977ae68-09d5-419f-8d6a-3112dabbf36c.png)
![image](https://user-images.githubusercontent.com/102220709/228521090-cbc2e160-71a5-402c-add9-2dd98f15b7dc.png)

Tested on :
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622
