### ISSUE TITLE
Android - Unable to scan the IDP QR code 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#453]
**Describe the bug**
Unable to scan the IDP QR code from scanner

**To Reproduce**
Prerequiste: one VC should be downloaded and binded,  have idp compatable login with qr portal ready

1. Authenticate app and get into it
2.  Go to scanner page
3.  Scan the IDP portal QR code log-in

**Expected behavior**
App should able to scan the QR code, and should able to login success fully

**Observered**
The app is unable to dedect the QR code and showing error as Invalid  QR code

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/213757422-3d9f48e6-bf58-494b-bbe4-97f0cd4ad532.png)

**Smartphone:**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://mosip.atlassian.net/browse/DSD-2033

**Comment by Sujithbn** [comment]
@santhoshsunder Please verify and confirm

**Comment by santhoshsunder** [comment]
Tested this issue in the new build, the issue is not observed anymore, able to scan and login into IDP portal success fully, iam attaching the screenshot and the remaining details below, hence closing this bug

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/223085819-2f7b3f3e-ee0f-4c9b-bc2c-cf33ab9e9baa.png)

Mobile details :
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4293687772
