### ISSUE TITLE
Android - Sharing is blocked when near by device feature is disabled 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#456]
**Describe the bug**
Sharing is blocked when the near by device feature is disabled 

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device
Device B - Sharing device

steps:
1. Disable google near by permisions in Device B
2. open qr code in Device A
3. open scanner in Device B
4. scan the qrcode from Device B
5. Select VC to share and share (attempt any type of sharing method)

**Expected behavior**
The sharing should work fine with out google near by's permision 

**Observed**
The app is stuck in loading screen, and unable to connect with the another device

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/213971409-90584f1b-0acf-4cfa-8bdd-245de9045223.png)

**Smartphone:**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://mosip.atlassian.net/browse/DSD-2033

**Comment by ravikp** [comment]
The permissions are unified for both google nearby and ble. These permissions are baked together in the application manifest file of the release(commit: e9bbfa252941fcbce62e9361fe0a9024b7e51746). So we would request you to test the happy path with google nearby permission to be turned on. In the next build for Jan 27th release, we shall see how we can exclude these permissions.

**Comment by ravikp** [comment]
The nearby permissions are required for the BLE sharing. Hence permissions can't be blocked.

**Comment by ravikp** [comment]
The BLE requires the nearby permissions for an operational requirement based on the android documentation. Kindly refer to the following [article](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions).

**Comment by rakhimosip** [comment]
@santhoshsunder can you please attach a screenshot or video of how nearby was disabled? And add verifier and wallet details clearly.

**Comment by lsivanand** [comment]
I think in/from Android 12, with BLUETOOTH_SCAN and BLUETOOTH_CONNECT permission, an app can scan for nearby devices without also requesting the location permission.

**Comment by Raginikrishnamurthy** [comment]
Near by permissions and google near by permissions are 2 different features. The app is looking for near by permissions only which is relevant, @santhoshsunder hence we should be able to close the bug. if there are any issues related to the message display, raise another ticket.

**Comment by santhoshsunder** [comment]
As we discussed, tested this issue in the current build, the issue is not occurring the same way, hence closing this bug
