### ISSUE TITLE
Android - Receiving is blocked when nearby device feature is disabled.

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#457]
**Describe the bug**
Reciving is blocked when near by device feature is disabled, and the app is crashing

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device and downloaded VC should contain photo of resident.
Device A - Requesting device
Device B - Sharing device

steps:
1. Disable near by devices permisions in Device A
2. open qr code in Device A
3. open scanner in Device B
4. scan the qrcode from Device B

**Expected behavior:**
The app should able to receive VC without crashing

**Observed:**
The app is crashing when the QR code is got scanned, as shown in the bellow video

**Video**
https://user-images.githubusercontent.com/102220709/213973090-d60b04ac-5905-4c43-9f69-589648273ef7.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://mosip.atlassian.net/browse/DSD-2033

**Comment by ravikp** [comment]
The permissions are unified for both google nearby and ble. These permissions are baked together in the application manifest file of the release(commit: https://github.com/mosip/inji/commit/e9bbfa252941fcbce62e9361fe0a9024b7e51746). So we would request you to test the happy path with google nearby permission to be turned on. In the next build for Jan 27th release, we shall see how we can exclude these permissions.

**Comment by ravikp** [comment]
The nearby permissions are required for the BLE sharing.

**Comment by rakhimosip** [comment]
@santhoshsunder can you please attach a screenshot or video of how nearby was disabled? And add verifier and wallet details clearly.

**Comment by lsivanand** [comment]
@ravikp as GNB and BLE are different supported communications in Inji, the permissions sets have to be different for each

**Comment by ravikp** [comment]
Nearby permissions are required for BLE to work.

**Comment by Raginikrishnamurthy** [comment]
@gsasikumar Please provide your inputs here as GNB and BLE are 2 different protocols, are we going to live with this for beta release or for the rest of the functionality ?

**Comment by Raginikrishnamurthy** [comment]
Near by permissions and google near by permissions are 2 different features. The app is looking for near by permissions only which is relevant, @santhoshsunder hence we should be able to close the bug. if there are any issues related to the message display, raise another ticket.

**Comment by santhoshsunder** [comment]
As we discussed, tested this issue in the current build, the issue is not occurring the same way, hence closing this bug
