### ISSUE TITLE
Android - Unable to login into idp portal from QR code login 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#461]
**Describe the bug**
Unable to login into idp portal from QR code login 

**To Reproduce**
Prerequiste: one VC should be downloaded and binded, have idp compatable login with qr portal ready

1. Authenticate app and get into it
2. Go to scanner page
3. Scan the IDP portal QR code log-in
4. select the binded UIN and perform the authentication method
5. select the requird atributes on the consent page

**Expected behavior**
We should able to login in successfully with out any errors

**Observed**
We unable to login and getting error as "auth factor mismatch" as shown in the below screen shot

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/214058770-065f6c57-1e4c-410f-8f6c-7d640007d27b.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by Sujithbn** [comment]
@MonobikashDas This issue is fixed, add the root cause and assign it back to QA

**Comment by Sujithbn** [comment]
@santhoshsunder Please verify this issue and confirm

**Comment by santhoshsunder** [comment]
Tested this issue in the new  build, the issue is not observed anymore, able to login into IDP portal success fully, iam attaching the screenshot and the remaining details below, hence closing this bug 

Screenshot :
![image](https://user-images.githubusercontent.com/102220709/223082648-240274f8-4710-496a-983f-d6c058eb7aba.png)

Mobile details :
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4293687772
