### ISSUE TITLE
Android - VC card activation ellipsis are not clickable 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#479]
**Describe the bug**
VC card activation ellipsis (three dot buttons) are not clickable 

**To Reproduce**
1. Authenticate app and enter inside
2. click on ADD ID and download a VC

**Expected behavior**
the three dots (ellipsis) on the VC card, should be clickable and usable 

**Observed**
the three dots (ellipsis) on the VC card are disabled and not clickable

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/214494978-caee3291-f5ab-445d-88c0-e54e7de35f4e.png)

**Smartphone:**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by Sujithbn** [comment]
@MonobikashDas : Please check this issue.

**Comment by adityankannan-tw** [comment]
There is no clickable functionality added for the ellipsis button this was the root cause. This issue has been fixed.

**Comment by krishnakumar4a4** [comment]
> There is no clickable functionality added for the ellipsis button this was the root cause. This issue has been fixed.

Quoting previous reply from @adityankannan-tw about the fix details. Fix is available as part of 24-03-2023 release.

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

@Anushree09-N @Sujithbn regarding the additional behaviour required on clicking ellipsis (three dots). Please create a separate functional story/issue

**Comment by santhoshsunder** [comment]
Verified this issue in the new build, the issue is not clickable anymore, VC card activation ellipsis is clickable now, hence closing this bug 

Screenshtot : 
https://user-images.githubusercontent.com/102220709/228135987-bef3d525-e0bd-4bcc-8cc7-584054c25309.mp4

Tested on :
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622
