### ISSUE TITLE
[Spec Impl] Cleanup un necessary permissions and properties for characteristics

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#485]
## Background

Currently there are some additional permissions and properties associated with each characteristic in Tuvali Gatt service declaration. Here is a table created on 24-01-2023

Char Name | SIG UUID | Properties | Permissions | Remarks
-- | -- | -- | -- | --
Identify Char | 2030 | Write, Write no response | Write | Write no response should be enough, should check removing Write property
Request Size Char | 2031 | Read, Indicate | Read | Not used today
Request Char | 2032 | Read, Indicate | Read | Not used today
Response Size Char | 2033 | Write, Write no response | Write | Is Write property needed? I guess not
Response Char | 2034 | Write, Write no response | Write | Is Write property needed? I guess not
Transfer Report Request | 2035 | Write, Write no response, Read, Indicate | Read, Write | Can remove Read, Indicate and Write properties I think
Transfer Report Response | 2036 | Indicate | Read |  
Verification status Char | 2037 | Read, Indicate | Read | Can remove one of the property Read if notification is Okay here
Disconnect Char | 2038 | Read, Indicate | Read | Can remove one of the property Read if notification is Okay here

## What to do
Referring to above table remarks, cleanup and test vigorously all scenarios.

**Comment by PuBHARGAVI** [comment]
This task changes are merged into develop

**Comment by krishnakumar4a4** [comment]
This task changes were released on 14/15th Feb release on INJI.
Commit id for the same https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12

PR merged to develop: https://github.com/mosip/inji/pull/562

**Comment by Sujithbn** [comment]
@Anushree09-N : Please verify this this is not breaking existing functionality and close it today

**Comment by Anuranjan14** [comment]
Verified the sharing , subsequent sharing, wallet binding, qr code login, face authentication features on below devices and its working as expected .Hence closing.
Device details:

Android to Android:-
Wallet Device:
Phone make/model: Redmi note 10 lite
OS: Android 10
BLE version : BLE 5.0

Verifier Device:
Phone make/model: Vivo Y 73
OS: Android 12
BLE version : BLE 5.0
Inji app version: https://github.com/mosip/inji/actions/runs/4447486079

Cross Platform:-

Wallet Device:
Phone make/model: iphone 11
OS: ios version 15
BLE version : BLE 5.0

Verifier Device:
Phone make/model: Galaxy A03 core
OS: Android 11
BLE version : BLE 4.2
Inji app version: https://github.com/mosip/inji/actions/runs/4447486079

Mimoto version: 1.2.0.1
MOSIP Version: 1.2.0.1
commitId:
![image](https://user-images.githubusercontent.com/120705365/227179167-80802887-c404-4e76-a0f3-22330204cab6.png)
![image](https://user-images.githubusercontent.com/120705365/227179998-0b6331a2-d265-4612-be2b-b6b6ad7a8a42.png)
