### ISSUE TITLE
Android - VC is not downloaded as activated when it is already binded

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#486]
**Describe the bug**
VC is not downloaded as activated when it is already binded

**To Reproduce**
prerequisite : download a VC and bind it

1. Authenticate app and enter it
2. Click on ADD ID and download the same binded VC

**Expected behavior**
When the UIN is already binded, if we again try to download the VC, The VC should be dowloaded as binded

**Observed**
When the VC is downloaded for the second time, which is already binded, it is not dowloaded as binded

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/214507990-92c13110-fd6e-41cd-9f3b-44f17b8eef44.png)

**Smartphone:**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by hegdenitin** [comment]
Created JIRA ticket and will track in JIRA going forward. Closing the bug.

https://mosip.atlassian.net/browse/INJIMOB-1740
