### ISSUE TITLE
Android - same binded UIN is showed up twice in the Select ID 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#490]
**Describe the bug**
Same binded UIN is showed up twice in the Select ID, while login via QR code 

**To Reproduce**
Prerequiste : download two VC from same UIN, and bind them 

1. Authenticate app and get into it
2. Go to scanner page
3. Scan the IDP portal QR code log-in
4. Verify the login site and click on conform

**Observed**
We are seeing two diffrent VC cards which are downloaded from same VC

**Expected behavior**
In this page we should see only one VC card from one UIN, which is recently got binded

**Screenshots**
https://user-images.githubusercontent.com/102220709/214549399-c06e99fb-5ec2-4e11-ac60-25cdff59de05.mp4

**Smartphone:**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by Sujithbn** [comment]
@santhoshsunder Please check with Rakhi for the usecase.

**Comment by Sujithbn** [comment]
@rakhimosip please confirm is this is a priority bug

**Comment by vijay151096** [comment]
Fixed the Issue for Showing the Same VC multiple Times in the Share VC Screen, when scanned QR Code the IDP Portal. 

**Steps To Reproduce:** 

1. Open the App.
2. Add a VC and activate it.
3. Add a Tag to the VC to differentiate.
4. Repeat the step 2 and 3 multiple Times using same VC.
5. Goto IDP Portal
6. Scan the QR Code.
7. **Should see only 1 VC Which is recently Added.**


**Same VC Added Multiple times and Activated it :** 
<img width="427" alt="Screenshot 2023-04-05 at 10 59 16 AM" src="https://user-images.githubusercontent.com/94220135/229989133-5c8951a4-6528-4fe3-902f-d823ceb3af4c.png">



**Now, We can see distinctly added VC only once which is recent** 
<img width="424" alt="Screenshot 2023-04-05 at 10 58 00 AM" src="https://user-images.githubusercontent.com/94220135/229988998-e0de87ee-8177-41df-a602-468f29ec969e.png">

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26889

**Comment by santhoshsunder** [comment]
tracking this bug from https://mosip.atlassian.net/browse/INJIMOB-51, hence closing the bug.
