### ISSUE TITLE
Android - we cant download more than 29 VCs in the INJI app

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#492]
**Describe the bug**
We cant download more than 29 VCs in the INJI app

**To Reproduce**
prerequisite : dowload 29 VCs in the app 

1. Authenticate and enter the app
2. click on ADD ID and download a 30th VC

**Expected behavior**
Should able to download suucessfully or proper limit message should be said

**Observed**
we are able to download and audit for that is loagged, but once the app is closed and reopened, the VCs which are downloaded after 29 th VC all gone back to loading state

**Video**
Uploading screen-20230125-164217.mp4…

**Smartphone:**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by rakhimosip** [comment]
Need to understand if this is a configured number.

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26841

**Comment by Raginikrishnamurthy** [comment]
No more a valid bug as the limitation on hte number of VCs are based on the phone storage limit and not on the count of the VC downloaded, hence closing the bug on github.
