### ISSUE TITLE
[Spec Impl] Change the references of the word IV to nonce

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#495]
## What to do
In Tuvali, wherever we are referring to IV, we need to change references to nonce. 
However the exception to use IV is where we do encrypt. In encrypt/decrypt function, we can use the term IV as it makes sense in the context of AES GCM encryption.

**Comment by vharsh** [comment]
The following change aligns the code implementation's variable name to match the spec.

PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/29
PR for mosip/inji: https://github.com/mosip/inji/pull/615

The PRs have been merged in 06-03-2023 Release and the latest commit id on mosip/inji/develop is https://github.com/mosip/inji/commit/8867f3cc2dda5fb19c003f85524a8f5cfce61303
