### ISSUE TITLE
[Spec Impl] [Spike] Check encryption output for AAD data

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#498]
## What to do

1. Check AES GCM encryption gives same output if the AAD is not set and if AAD is set to empty string. Based on the outcome, update the specification to use Empty string for AAD or an explicit NULL value.

**Comment by Alka1703** [comment]
I have added tests to verify what happens when we pass empty string as a parameter(associated text) in the AEADParameters instead of null. We get the exact same encrypted text.
