### ISSUE TITLE
Android Verifier disconnects Android wallet immediately after connection established

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#500]
**Describe the bug**
Sometimes Verifier disconnects the wallet connection before identify transfer happens.(Suspected to be an Anrdoid BLE issue).
When this happens wallet is stuck on scanning screen. 

**To Reproduce**
Steps to reproduce the behavior[Happens randomly]:

1. Do multiple VC transfers.
2. Whenever wallet gets stuck on scanning screen. Check logs for disconnection.

**Additional context**
As Scanner stops scanning immediately after connecting to first device. Reconnection doesn't happen.

**Comment by ravikp** [comment]
In the 20th Feb, 2023 release contains error handler for the screen on the wallet side to get stuck upon disconnect.

**Comment by krishnakumar4a4** [comment]
In the 24th Feb release, we have started handling disconnect event even before the Identify characteristic is written. Hence we will be able to get disconnect if it happens before the write and the Wallet will not be stuck anymore.
