### ISSUE TITLE
Android - We are able to activate received VCs

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#512]
**Describe the bug**
We are able to activate received VCs and login through IDP with received VCs

**To Reproduce**
Prerequiste: download a VC and dont bind, receive a VC

1. Authenticate the app and enter it
2. Go to received id section, click on the received IDs
3. select the received VC and bind it
4. click on the scan page, and scan the idp portal 
5. manually verify the site and click on continue

**Expected behavior**
We should not able to bind received VCs and should not able to login with it

**Observed**
we are able to bind received VCs and able to login with it

**Video**
https://user-images.githubusercontent.com/102220709/215513078-120ff9c3-a011-4c4d-8f39-b4a061d6df53.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by rakhimosip** [comment]
We will be creating a separate Verifier app. Hence any verifier-related bugs/issues will not be considered a priority for Beta release. Will be picked up only after addressing all blockers and critical bugs if capacity is available with the team.

CC @Sujithbn @MonobikashDas @Raginikrishnamurthy @Anushree09-N @santhoshsunder @ravikp

**Comment by PuBHARGAVI** [comment]
Removed Activation status info of VC on the receiver side:
**Removed it in received Id's Tab:**
<img width="288" alt="Screenshot 2023-02-27 at 11 00 07 PM" src="https://user-images.githubusercontent.com/46226958/221638708-81ecaa59-879e-4ac4-abab-6f008160752c.png">
**Removed in detailed view of VC on receiver side:**
<img width="323" alt="Screenshot 2023-02-27 at 11 01 54 PM" src="https://user-images.githubusercontent.com/46226958/221639274-ff247426-c702-4055-9cc5-0d866c42b39b.png">
**Removed in Incoming VC screen:**
<img width="681" alt="Screenshot 2023-02-27 at 11 21 54 PM" src="https://user-images.githubusercontent.com/46226958/221643840-39d2f531-965f-4e65-a600-fef718a92b6a.png">

**Comment by ravikp** [comment]
Issue merged in the PR - https://github.com/mosip/inji/pull/595

**Comment by Alka1703** [comment]
The following PRs implements restrictions for verifier to not activate the received VC and do any actions on it. 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/28
PR for mosip/inji: https://github.com/mosip/inji/pull/595, https://github.com/mosip/inji/pull/597

The PRs have been merged in 28-02-2023 Release and the latest commit id on mosip/inji/develop is [7cdee82](https://github.com/mosip/inji/commit/7cdee829c4c0fb5da4ed75a4d68a52ed8ca36934)

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, now removed Activation status info of VC on the receiver side, so we can not bind received VCs and should not be able to login with it. I am attaching the video and the device details below for reference. Hence closing the bug.
Video: -Uploading Untitled (1).mp4…
![image](https://user-images.githubusercontent.com/124761463/225261979-4f4360e0-6305-4bb8-a40b-157694feecf0.png)

Tested in: -Tested in:
Device: Redmi 7A
Android Version: 10
BLE version :4.2
Inji app link: https://github.com/mosip/inji/actions/runs/4376897206
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
