### ISSUE TITLE
Android - downloaded VC stuck at loading state

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#514]
**Describe the bug**
Unable to download VC from mobile APK, VC stuck at loading state

**To Reproduce**
1.Unlock app
2.Enter valid VID and request for VC

**Expected behavior**
without any errors we should be able to download VC

**Current behavior**
Unable to download VC, VC stuck in loading state

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/215675368-5c5183dc-a6cd-4179-8ecd-c3d13af35c37.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by rakhimosip** [comment]
To monitor and test post platform hotfix changes

**Comment by Raginikrishnamurthy** [comment]
@rakhimosip please elaborate on the hotfix changes, are they into qa environment?

**Comment by Anuranjan14** [comment]
Verified the issue in the new build and its working as expected. Hence closing.

Device details :
Phone make/model: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4343056712

Screenshot:
![image](https://user-images.githubusercontent.com/120705365/223381080-d100e888-c8ab-4308-8862-232624d08d98.png)
