### ISSUE TITLE
Android - app crashing intermittently while connecting 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#515]
**Describe the bug**
INJI app crashing intermittently while connecting on only specific device (device details added at at last) 

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device 
Device A - Requesting device
Device B - Sharing device

steps:
1. open qr code in Device A
2. open scanner in Device B

**Expected behavior**
The app should able to connect properly and share VC with out any intermittent issues in all devices

**Observed**
App is crashing and not connecting on specific device (device details added bellow)

**Video**
https://user-images.githubusercontent.com/102220709/215695949-f6c9fb83-d9ce-4396-a837-46f210c0e796.mp4

**Smartphone:**

**Sender device :** 
Android version : 10
BLE version : BLE 5.0
device name : redmi note 10 lite

**Receiving device :**
Android version : 12
BLE version : 5.0
device name : vivo Y73

**Remaining details :**
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by santhoshsunder** [comment]
This issue is observed in our another set of tedting devices too, and observed in the new APk, iam mentioning its details below

Receiving device :
Android version : 9
BLE version : 4.2
device name : Redmi 6A

sender device : 
Android version : 10
BLE version : BLE 5.0
device name : redmi note 10 lite

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by santhoshsunder** [comment]
closed it by mistake reopening it now

**Comment by krishnakumar4a4** [comment]
Here are some more details about analysis mentioned in other channels

```
2023-02-01 15:00:48.501 19230-25563 AndroidRuntime          pid-19230                            E  FATAL EXCEPTION: CentralHandlerThread
                                                                                                    Process: io.mosip.residentapp, PID: 19230
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattCharacteristic android.bluetooth.BluetoothGattService.getCharacteristic(java.util.UUID)' on a null object reference
                                                                                                    	at io.mosip.tuvali.ble.central.impl.GattClient.subscribe(GattClient.kt:259)
                                                                                                    	at io.mosip.tuvali.ble.central.impl.Controller.subscribe(Controller.kt:55)
                                                                                                    	at io.mosip.tuvali.ble.central.state.StateHandler.handleMessage(StateHandler.kt:205)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
```

We have done a quick verification of provided stack trace. It’s pointing to a code from Jan 20th release. This stack is not relevant to latest build (Jan 30th or Feb 7th) as the debug symbols don’t match.

We also think the chances of this crash happening in latest build will be less as we have incorporated retry strategy (in Jan30th build) which will ensure services are discovered before doing subscription.

As mentioned in the previous message. Please revalidate with latest version https://github.com/mosip/inji/commit/c75f8f16ce4a7a39d92c6a9f9b8bc0c9e4c39529

**Comment by santhoshsunder** [comment]
The #542 issue is not related to this issue, unable to delete it

**Comment by santhoshsunder** [comment]
Verified this issue in the new build, and the issue is not observed anymore, instead of crashing we are facing an error message, which is expected as we all discussed over the call, I am attaching the current working flow video, and device details below

screenshot : 
https://user-images.githubusercontent.com/102220709/225245370-c9c55944-5d60-4ce9-a4b3-7ffe88cd3e14.mp4

Tested on : 

- Wallet : 
Phone make/model: Apple iphone 7
OS: IOS 15.6
BLE version : 4.2

- Verifier :
Phone make/model: Pixel 6
OS: Android 13
BLE version : 5.2 

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
App link : 
IPA Testflight version : 0.4.1 (25)

**Comment by santhoshsunder** [comment]
what is the solution for the crash issue. our inference was disconnect pop-up will be displayed to handle crashes gracefully. but if our inference is wrong, can you please explain how is this handled? please add comments to reverify, hence re opening the bug.

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/INJI-72

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![Uploading image.png…]()
