### ISSUE TITLE
Android: Able to see binding details in receiver's phone

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#517]
**Describe the bug**
Able to see binding details in receiver's phone

**To Reproduce**
1. unlock the app
2. download VC
3. Activate VC for online login
4. Share the activated VC 

**Actual behavior**
If resident share's a activated VC (binded VC), the activation details are shown in receiving device. 

**Expected behavior**
Receiver should not know VC binding details.

**Screenshots**

https://user-images.githubusercontent.com/79500509/215728117-3076a088-247c-4ecb-b809-0567b26841ef.mp4

**Smartphone (please complete the following information):**

**Verified in:**

Device: Redmi 7A (sender)
OS: Android 10
Inji app link: https://github.com/mosip/inji/actions/runs/3986424542
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version : 4.2

Device: Redmi 6A (requestor)
OS: Android 9
Inji app link: https://github.com/mosip/inji/actions/runs/3986424542
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version : 4.2

**Comment by rakhimosip** [comment]
We will be creating a separate Verifier app. Hence any verifier-related bugs/issues will not be considered a priority for Beta release.

**Comment by PuBHARGAVI** [comment]
Removed Activation status info of VC on the receiver side:
**Removed it in received Id's Tab:**
<img width="288" alt="Screenshot 2023-02-27 at 11 00 07 PM" src="https://user-images.githubusercontent.com/46226958/221638708-81ecaa59-879e-4ac4-abab-6f008160752c.png">
**Removed in detailed view of VC on receiver side:**
<img width="323" alt="Screenshot 2023-02-27 at 11 01 54 PM" src="https://user-images.githubusercontent.com/46226958/221639274-ff247426-c702-4055-9cc5-0d866c42b39b.png">
**Removed in Incoming VC screen:**
<img width="681" alt="Screenshot 2023-02-27 at 11 21 54 PM" src="https://user-images.githubusercontent.com/46226958/221643840-39d2f531-965f-4e65-a600-fef718a92b6a.png">

**Comment by Anushree09-N** [comment]
Verified in: 
Device: Redmi 7A (wallet)
OS: Android 10
Inji app link: https://github.com/mosip/inji/actions/runs/4374183074
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version : 4.2

Device: Redmi 6A (Verifier)
OS: Android 9
Inji app link: https://github.com/mosip/inji/actions/runs/4374171157
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version : 4.2

**Commit id:**
![image](https://user-images.githubusercontent.com/79500509/225599867-e447a862-3f92-4f48-a99a-e59d5a7543e5.png)

Binding details are not shared to verifier , Working as expected.
