### ISSUE TITLE
Android - app is not connecting in the second attempt of sharing 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#519]
**Describe the bug**
app is not connecting in the second attempt of sharing in the devices which has bluetooth version bellow V5.2

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device
Device A - Requesting device
Device B - Sharing device

steps:
1. Authenticate app and enter it
2. Attempt a successfull VC sharing method
3. Again open qr code in Device A
4. open scanner in Device B

**Expected behavior**
The app should connect how ever time required by the user

**Observed**
The devices are not connecting with each other in the second attempt of sharing, on the devices which has bluetooth version less than V5.2

**Video**
https://user-images.githubusercontent.com/102220709/215747684-ddf3bc17-395e-425b-a428-eb6991750e6d.mp4

**Smartphone (please complete the following information):**
Device: Redmi Note 10 Lite
OS: Android 10
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Additional informaton**
we have tested this issue in multiple manufactures device, this issue is not occuring with specific manufactures, what ever device has less than bluetooth version 5.0 its not working in the second attempt

**Comment by ravikp** [comment]
Please share the details of the other device.

**Comment by ravikp** [comment]
Issue fixed in c75f8f16ce4a7a39d92c6a9f9b8bc0c9e4c39529.

**Comment by santhoshsunder** [comment]
Verified this issue in the new build, verified in all our testing devices and in multiple flows, unable to replicate this issue, sharing on the second attempt is working as expected, hence closing the jira 

new build link : https://github.com/mosip/inji/actions/runs/4123991786
