### ISSUE TITLE
Android - Unable to bind VC in inji app

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#520]
**Describe the bug**
Unable to bind VCs in specific devices (device details added at at last)

**To Reproduce**
Prerequisite:
 1. VC is downloaded in inji app (UIN)
 2. IDP is configured
 
 Steps:
 1. unlock the app
 2. clicks on enabling verification link
 3. Otp is prompted to enter
 4. enter received Otp -> Otp matched

**Expected behavior**
All VC's should be able to bind without any errors 

**Observed**
Unable to bind VC, projecting error message on specific device (device details added bellow)

**Screenshots**
![Screenshot_2023-02-01-10-56-07-992_io mosip residentapp](https://user-images.githubusercontent.com/102220709/215961908-2fe72a75-5a38-4cf8-b1ac-73bc4581b8ed.jpg)

**Smartphone :**
Device 1 :
Android version : 10
BLE version : BLE 5.0
device name : redmi note 10 lite

Device 2 :
Android version : 12
BLE version : 5.0
device name : vivo Y73

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by rakhimosip** [comment]
Unable to replicate this issue anymore.

NO CODE fix made from dev team.

Please retest with the latest build.

**Comment by santhoshsunder** [comment]
Tested this issue on the new APK, and we are able to replicate this issue again, but its working intermittently and occurs in only a set of specific devices

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/217779284-29457620-0b5b-45f6-8593-77b3769b300e.png)

Smartphone :
Android version : 10
BLE version : BLE 4.2
device name : redmi 7A

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4123991786

**Comment by santhoshsunder** [comment]
Tested this issue in the new APK,  unable to replicate the issue currently, I have tested it on devices where I was facing this issue since I am unable to replicate this issue iam closing right now

Smartphone :
Device 1 :
Android version : 10
BLE version : BLE 5.0
device name : redmi note 10 lite

Device 2 :
Android version : 12
BLE version : 5.0
device name : vivo Y73

Android version : 10
BLE version : BLE 4.2
device name : redmi 7A

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4123991786
