### ISSUE TITLE
Cross platform: Unable to share VC 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#526]
**Describe the bug**
unable to share VC

**To Reproduce**
**Prerequisite:**

1. iOS (sharing device) --> VC is downloaded and stored
2. Android (requesting device)

**steps:**
1. Scan the qr code from iOS
2. select VC to share
3. click on "Accept request and choose ID" button

**Current behavior**
Device stucks in sharing and receiving state and displays " connection interruption" message and requesting device 

Expected behavior
VC sharing should be successful

Screenshots

https://user-images.githubusercontent.com/79500509/216593992-7de09157-c7f5-4e07-9d8a-ef37c5ab3f12.mp4

**Smartphone (please complete the following information):**

Verified in:

Sharing device
Device: iPhone 11
OS: 15
Inji app version: 0.4.1 (15) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

Requesting device
Device: vivo Y73
OS: Android 12
Inji app version : https://github.com/mosip/inji/actions/runs/4062244892
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

**Comment by rakhimosip** [comment]
**Tested on** 
iOS(Wallet) - iPhone 14 Promax
Android (Verifier) - Redmi 9i sport

**Commit ID:** https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12

We were able to execute this test case successfully.

**Comment by rakhimosip** [comment]
@krishnakumar4a4 to add root cause and fix details

**Comment by Alka1703** [comment]
We don't observe this issue on the device combinations we have. Since we have implemented the disconnection/cancel flow of ios, this issue should not appear on your device combinations with this commit(https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12).

If you are able to see the issue with this commit(https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12), please attach the logs as well.

**Comment by Anushree09-N** [comment]
Verified in :
Wallet
Device: iPhone 11
OS: 15
Inji app version: 0.4.1 (21) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

![image](https://user-images.githubusercontent.com/79500509/223151468-e766521c-3a7b-439f-9aa8-c149fa0a6dbb.png)


Verifier
Device: vivo Y73
OS: Android 12
Inji app version : 

![image](https://user-images.githubusercontent.com/79500509/223151682-fd3c6b71-18c7-4c7d-840d-54b8e2c24015.png)

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

Sharing worked without disconnect issue . hence closing
