### ISSUE TITLE
Android - On sharing screen, downloaded VC was hidden down

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#527]
**Describe the bug**
The phones which has screen size less then 5.45, on the sharing screen downloaded VC where hided

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device
Device A - Requesting device, verifier device
Device B - Sharing device, wallet device

steps:
1. open qr code in Device A
2. open scanner in Device B

**Expected behavior**
The app should align proper to the small screen, and should be user friendly 

**Observed**
The phones which has screen size less then 5.45, on the sharing screen downloaded VC where listed down, and the buttons where hiding the VC, to access the VC we have to scroll and see, it dont look user friendly 

**Video**
https://user-images.githubusercontent.com/102220709/216309906-24f704f2-1228-48ba-9907-b3438d496c9f.mp4

**Smartphone :**
Device: Redmi 6a
OS: Android 9
BLE version: 4.2
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4062244892

**Comment by Sujithbn** [comment]
@santhoshsunder Please verify and close it today

**Comment by santhoshsunder** [comment]
Tested this issue in the build, and the issue is not observed anymore, we are able to see VC in that screen, even the small APK, attaching the screenshot and device details below, hence closing this bug

**Screenshot :** 
![Screenshot_2023-03-16-12-45-37-734_io mosip residentapp](https://user-images.githubusercontent.com/102220709/225544844-97edca31-9858-4e3f-aec5-13dc68e075ca.jpg)

**Smartphone :**
Device: Redmi 6a
OS: Android 9
BLE version: 4.2
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link: https://github.com/mosip/inji/actions/runs/4376878070
