### ISSUE TITLE
Android - VC binding button is getting disappeared

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#531]
**Describe the bug**
VC binding button is getting disapeared in specific device (device details where listed down below)

**To Reproduce**
Prerequisite:
 1. VC is downloaded in inji app (VID)
 2. IDP is configured
 
 Steps:
1. unlock the app
2. open the downloaded VC in detailed view
3. click on the activate button

**Expected behavior**
The all buttons should be present and should work propely in all devices

**Observed**
VC binding button is getting disapeared in specific device (device details where listed down below), as show in the below screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/216615117-e90af609-9e8e-4e71-9fe6-c2cdd8ca48d4.png)

**Smartphone:**
Device: Samsung galaxy A03 core
OS: Android 11
BLE version: 4.2
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4062244892

**Additional context**
Faced this issue only on this device

**Comment by Anushree09-N** [comment]
@Sujithbn  Please mention the root cause of the issue fixed to identify the pattern to retest and close.
