### ISSUE TITLE
Fixing Labels issue in INJI App

### ISSUE THREAD

**Issue by Sujithbn** [mosip/inji#533]
**Details:**
Due to a code merging issue, it was noticed that labels that were working properly were broken. This was noticed during the feature demo of the 30th Jan build.
This was fixed by addressing the code merge issue.

**Test scope:** All the labels in the app should work as before.

**Comment by Raginikrishnamurthy** [comment]
@Sujithbn this is a task, qa team will not be verifying/closing the tasks.
