### ISSUE TITLE
Able to download VC with UIN even after restricting UIN in the configuration

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#534]
**Describe the bug**
Able to download VC with UIN 

Below is set in the config https://github.com/mosip/mosip-config/blob/qa-1201-B2/id-authentication-default.properties

## Allowed ID Types (allowed values : UIN/VID/USERID) to be supported for Authentication/KYC/OTP Requests
request.idtypes.allowed=VID

![image](https://user-images.githubusercontent.com/79500509/216609313-a97f4cf4-ad57-4ad5-a09e-c4f58f61d034.png)

**To Reproduce**
1. Click on Add ID
2. Enter UIN 
3. Otp is prompted Enter OTP
4. Navigate to HOME screen

**Current behavior**
Able to Download VC with UIN 

**Expected behavior**
Inji app should support only VID download as per the configuration

**Screenshots**

https://user-images.githubusercontent.com/79500509/216607698-4ca7b779-e827-4f61-a970-51579046f85c.MP4

**Smartphone (please complete the following information):**

Verified in:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (15) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Device: On all Android versions
OS: 11, 10, 12, 9
Inji app version: https://github.com/mosip/inji/actions/runs/4062244892
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

![image](https://user-images.githubusercontent.com/79500509/216608829-fcc9c232-c271-4647-8fe2-7b17d98dc833.png)

**Additional context**
Add any other context about the problem here
The issue is across all the platform

**Comment by rakhimosip** [comment]
@Anushree09-N @santhoshsunder @lsivanand @Raginikrishnamurthy 

I had a discussion with @LoganathanSekar7627 and have provided inputs below:

In this case, **Mimoto calls -> Resident Services that calls -> IDA**

Resident Services uses `request.idtypes.allowed.internalauth` config from [id-authentication-default.properties](https://github.com/mosip/mosip-config/blob/qa-1201-B2/id-authentication-default.properties)

![image](https://user-images.githubusercontent.com/86289097/217206348-c89c87cb-15ae-4a10-9732-d8e791d61434.png)
Please change the value of the same to `VID `and try.

**Comment by lsivanand** [comment]
IMO - Inji should use external allowed Idtypes. Our stack should behave (allow or not allow, UIN/VID) based based on request.idtypes.allowed... 

@gsasikumar @LoganathanSekar7627

**Comment by rakhimosip** [comment]
> IMO - Inji should use external allowed Idtypes. Our stack should behave (allow or not allow, UIN/VID) based based on request.idtypes.allowed...
> 
> @gsasikumar @LoganathanSekar7627 @MonobikashDas @nayakrounak

@lsivanand Inji is viewed as an independent module -> it should not be concerned with platform configs like the one that determines if VID or UIN should be used for auth. That logic should remain in the platform side of the code which in this case is resident services.

**Comment by Sujithbn** [comment]
@Anushree09-N Please retest with the configuration that are mentioned by Rakhi and confirm.

**Comment by gsasikumar** [comment]
@nayakrounak This should be moved as a enhancement request. We want the `mimoto` to work more closely with `esignet` so these settings are followed. 

Also, we should isolate all kind of resident service access from `mimoto` to a specific library. This will allow us to deploy and use `mimoto` with `esignet` without resident service. Resident service functionality should be treated independent.

**Comment by Raginikrishnamurthy** [comment]
As this will be considered as an enhancement, it will not be tested for beta release.

**Comment by Pragya279** [comment]
This ticket has been moved to Jira as an enhancement.
Link to Jira story: https://mosip.atlassian.net/browse/MOSIP-26855
