### ISSUE TITLE
Android - no consent page coming for success full binding 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#535]
**Describe the bug**
The consent page is not coming when the VC successfully geting binded

**To Reproduce**
Prerequisite:
 1. VC is downloaded in inji app (VID)
 2. IDP is configured
 
 Steps:
 1. unlock the app
 2. clicks on enabling verification link
 3. Otp is prompted to enter
 4. enter received Otp -> Otp matched

**Expected behavior**
we should able to see successful message to be projected as a consent page

**Observed**
The consent page is not coming when the VC successfully geting binded

**Video**
https://user-images.githubusercontent.com/102220709/216616885-8cc9d194-717c-4c00-8706-b9aec9db866d.mp4

**Smartphone :**
Device: Samsung galaxy A03 core
OS: Android 11
BLE version: 4.2
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4062244892

**Comment by Anushree09-N** [comment]
@Sujithbn Please let us know if there was any design discussion for removal of status screen which was projecting success message with green icon after binding.

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.Version: untagged_b72c96f_release-0.10.0Tuvali-version: v0.4.6-9c5df99
