### ISSUE TITLE
Implement disconnect/cancel handling in iOS when android raises disconnect event

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#547]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Alka1703** [comment]
The following PR implements handling DISCONNECT_CHAR on the iOS wallet(similar to android wallet) as per the spec.
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/24
PR for mosip/inji: https://github.com/mosip/inji/pull/573

The PRs have been merged in 20-02-2023 Release and the latest commit id on mosip/inji/develop is 6df8076
