### ISSUE TITLE
Create Error Handling Setup on Inji and tuvali android

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#549]
**Is your feature request related to a problem? Please describe.**
As BLE has edge cases where transfer has to be cancelled and restarted. Create a new event for error case and show it to user.

**Comment by Alka1703** [comment]
The following PR will display an error popup on any exception from the lower layer(ex: #550, #551). 
The device on which the exception occurs will display the message: "Something went wrong while transferring id. Please try again." while the other device shows the disconnect message.
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/24
PR for mosip/inji: https://github.com/mosip/inji/pull/573
The PRs have been merged in 20-02-2023 Release and the latest commit id on mosip/inji/develop is 6df8076

**Comment by tilak-puli** [comment]
Hi QA team,

Please add translations for overlay message whenever you deploy to a new env.

Thank you.
