### ISSUE TITLE
[Android] Throw and error to disconnect when MTU size is less than(<) 64 or unknown

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#550]
**Is your feature request related to a problem? Please describe.**
Some devices might not supports 517 MTU which will force android to use 23 MTU which is not supported as Identify requests is more than 44 bytes excluding checksum. From word sizes perspective, the nearest powers of 2 is 64.

**Describe the solution you'd like**
Throw an exception on error event when this happens on android tuvali

** Out of scope **
- Throwing of error when the iOS negotiates any MTU value less than 64 bytes is not included in the scope.

**Comment by Alka1703** [comment]
The following PR will display an error pop up on both wallet and verifier if the MTU size negotiated is less than 64 bytes.  
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/24
PR for mosip/inji: https://github.com/mosip/inji/pull/573
The PRs have been merged in 20-02-2023 Release and the latest commit id on mosip/inji/develop is 6df8076
