### ISSUE TITLE
[Android] Throw an error event when failure rate of chunk transfer more than 70% in VC transfer

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#551]
**Is your feature request related to a problem? Please describe.**
If transfer failure rate is more than 70%, it can be cause of MTU issue which will eventually fail on decryption. So do a early failure before it happens

**Describe the solution you'd like**
Throw an error event with required message when error rate is more 70%

** Out of scope **
- This story needed to be played on iOS verifier, when the feature comes in.

**Comment by Alka1703** [comment]
The following PR will display an error pop up on both wallet and verifier if the failure rate of chunk transfer  is more than 70% in VC transfer
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/24
PR for mosip/inji: https://github.com/mosip/inji/pull/573
The PRs have been merged in 20-02-2023 Release and the latest commit id on mosip/inji/develop is 6df8076
