### ISSUE TITLE
VID support for INJI

### ISSUE THREAD

**Issue by MonobikashDas** [mosip/inji#555]
**Describe the bug**
When the vid is used to download cred its not being shown.

**To Reproduce**
download credential using vid.

**Expected behavior**
VID should be shown in VC.

**Smartphone (please complete the following information):**
All android and ios

**Comment by Anushree09-N** [comment]
Verified the bug working as expected details added here: https://github.com/mosip/inji/issues/219#issuecomment-1465622821

Hence closing.
