### ISSUE TITLE
iOS: No Audits logged for success and failure cases of wallet binding.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#559]
**Describe the bug**
No Audit for successful attempt of  "Activation of VC"
No Audit for failure attempt of wallet binding

**To Reproduce**
 **Prerequisite :** Download VC and store in app

**For successful attempt:**

1. Unlock the app
2. click on Add ID
3. Enter VID
4. click on Generate ID
5. Click on on the link "**Activation pending for online login** " on the card.
6. Click on **Activate** button.
7. Click on "Yes I confirm"
8. Enter Otp which is prompted
--- VC will be activated for online login

**Current behavior**
VC activated for successful login but no history captured in history Tab 

**Expected behavior**
As per the story https://github.com/mosip/inji/issues/278

Enabling verification for a VC should be captured in the audit/history
Success scenario message -> 'Verification was enabled for 9876543210'
Failure scenario message -> 'Enabling verification for 9876543210 failed'

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/218462805-e0c58f6b-b51f-44dc-91dd-8aec7a7dc8da.png)

![image](https://user-images.githubusercontent.com/79500509/218462923-e9e50527-991f-4147-a7af-b271c7f366c3.png)

**Smartphone (please complete the following information):**

Device: iPhone 11
OS: 15.6.1
Inji app version: 0.4.1 (15) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE : 5.0

**Additional context**
Failure case : Json Parse error which was caused due to pod down 
https://github.com/mosip/inji/issues/554
https://github.com/mosip/inji/issues/522
https://github.com/mosip/inji/issues/450

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, now we get activate or failure message of wallet binding in audit log. I attached the video for reference. hence closing the Bug.

Video:
Uploading Untitled (5).mp4…
![image](https://user-images.githubusercontent.com/124761463/226599370-d462215c-db92-4ecf-b998-a5c7f923b259.png)

Tested in: -
Device: iPhone 8
OS:16.0.2
BLE version: 5.0
Inji app version:0.4.1 (29) -> TestFlight
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
