### ISSUE TITLE
Handle remaining disconnect scenarios when iOS rejects vc transfer

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#565]
## TODO
- Reject VC transfer from IOS Wallet

**Comment by Alka1703** [comment]
The following PR will handle the reject scenario from iOS wallet and show disconnected message on verifier
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/24
PR for mosip/inji: https://github.com/mosip/inji/pull/573
The PRs have been merged in 20-02-2023 Release and the latest commit id on mosip/inji/develop is 6df8076
