### ISSUE TITLE
Implement Android to Android dynamic MTU negotiation with 250ms timeout

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#566]
## What to do
- Attempt request MTU from Android Wallet with 512
- If we don't receive callback in 250ms, attempt same with 185 and 100.
- If we don't receive callback from 100 as well, then we should show error to user with proper disconnection.

**Comment by Alka1703** [comment]
The following PRs implement dynamic mtu negotiation for android to android communication with a timeout of 250 ms for each negotiation. We will see an error pop up if it fails to negotiate even after 3 attempts. 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/26
PR for mosip/inji:https://github.com/mosip/inji/pull/584

The PRs have been merged in 24-02-2023 Release and the latest commit id on mosip/inji/develop is `cb47493`

**Comment by Alka1703** [comment]
The following PRs implements incrementing the delay time between android to android mtu negotiation to 500 ms.
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/28
PR for mosip/inji: https://github.com/mosip/inji/pull/595, https://github.com/mosip/inji/pull/597

The PRs have been merged in 28-02-2023 Release and the latest commit id on mosip/inji/develop is [7cdee82](https://github.com/mosip/inji/commit/7cdee829c4c0fb5da4ed75a4d68a52ed8ca36934)

**Comment by krishnakumar4a4** [comment]
### More context about bumping up negotiation timeout to 500ms for each MTU size

We have observed in most of the scenarios, MTU negotiation is happening quite quickly. Whereas in some device combinations, the MTUChanged callback is returning consistently after 250ms. Hence, having 250ms will only exclude those devices from leveraging the dynamic MTU negotiation implementation as all three MTU negotiation attempts with various sizes will fail. So the call was made to bump up the wait time to 500ms.

Bumping up wait time does't mean the transfer will be waiting for 500ms even if the callback is received sooner than 500ms. The wait time will be a function of `min(callbackWaitTime, 500ms)`. Hence, having the value bumped to 500ms should not affect the device combinations that were able to negotiate quickly.
