### ISSUE TITLE
[IOS] Throw and error to disconnect when MTU size is less than(<) 64 or unknown

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#569]
Is your feature request related to a problem? Please describe.
Some devices might not supports 517 MTU which will force android to use 23 MTU which is not supported as Identify requests is more than 44 bytes excluding checksum. From word sizes perspective, the nearest powers of 2 is 64.

Describe the solution you'd like
* Create custom error handling in IOS Tuvalu
* Throw an error event when this happens on IOS tuvali wallet

Out of scope:
* Handling Uncaught internal IOS Exceptions

**Comment by vharsh** [comment]
> Additionally, an error needs to be implemented for VC transfer when 70% of the VC chunks by count are corrupted. This is already implemented in Android.

[Update: 11:40AM IST] This additional feature isn't required for now as Verifier on iOS is not available today.

**Comment by Alka1703** [comment]
The following PRs implement displaying an error pop up when the negotiated mtu is less than 64 bytes on the iOS wallet side. 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/26
PR for mosip/inji:https://github.com/mosip/inji/pull/584

The PRs have been merged in 24-02-2023 Release and the latest commit id on mosip/inji/develop is `cb47493`
