### ISSUE TITLE
Android - unable to login in into IDP portal 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#571]
**Describe the bug**
Unable to scan IDP login QR code page properly 

**To Reproduce**
Prerequiste: one VC should be downloaded and binded, have idp compatible login with qr portal ready

1. Authenticate app and get into it
2. Go to scanner page
3. Scan the IDP portal QR code log-in

**Expected behavior**
The app should able to scan the IDP portal screen and should able to login successfully 

**Observed:**
Once the QR code is scanned, we are getting "invalid link code" error

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/219655497-81bfdf35-3853-4bcf-af57-c28e1f2bb0eb.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://mosip-team.slack.com/files/U04KHL40S3X/F04QEC4SCQY/io.mosip.residentapp-0.2.1-858-5fa5c9b-develop-dirty-mosip_20230215_1516_universal.apk?origin_team=TQFABD422&origin_channel=D03581C1Q2K

**Comment by santhoshsunder** [comment]
@Sujithbn, please add the rootcause and assign it back to testing

**Comment by ravikp** [comment]
The e-signet url has been updated in the app and in the backend. Kindly test with a new build.

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, we able to scan the IDP portal screen and able to login successfully, I am attaching the video and the device details below for reference. Hence closing the bug.
Video: -
https://user-images.githubusercontent.com/124761463/225294118-c9b8e306-4a77-4826-86b2-f75d093772ae.mp4
![image](https://user-images.githubusercontent.com/124761463/225294274-f9562ea7-8664-4974-8907-7bc606aa9d1c.png)
![image](https://user-images.githubusercontent.com/124761463/225294318-6d6c81ca-030d-4500-acf9-4db2b5c1726d.png)
![image](https://user-images.githubusercontent.com/124761463/225294532-9de08340-e81e-4a2e-be53-bec002062e5a.png)
Tested in: -
Device: Redmi 7A
Android Version: 10
BLE version :4.2
Inji app link: https://github.com/mosip/inji/actions/runs/4376897206
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
