### ISSUE TITLE
Auth token lifecycle management in mimoto for IDA token

### ISSUE THREAD

**Issue by MonobikashDas** [mosip/inji#574]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot."C:\Users\ADMIN\Downloads\image.png"
