### ISSUE TITLE
Show Tuvali commit or tag information in Profile screen

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#576]
### What to do
- Show Tuvali version on Profile screen
- Add commit/tag information in Tuvali logs [Android Only]

**Comment by Alka1703** [comment]
The following PRs implement displaying the latest commit id and version tag information on profile screen both on android and iOS devices. It also displays the tag information in the logs of android. 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/26
PR for mosip/inji:https://github.com/mosip/inji/pull/584

The PRs have been merged in 24-02-2023 Release and the latest commit id on mosip/inji/develop is `cb47493`

**Comment by Alka1703** [comment]
The following PRs implements displays the tag information along with class name in the logs of android.
"Accept request and choose ID" to "Share"
"Accept request and verify" to "Share with Selfie"
PR for mosip/tuvali: #28
PR for mosip/inji: #595, #597

The PRs have been merged in 28-02-2023 Release and the latest commit id on mosip/inji/develop is 7cdee82

**Comment by Kratitva** [comment]
This is fixed as part of release v0.9.1
