### ISSUE TITLE
Remove the check box in the credential share screen 

### ISSUE THREAD

**Issue by nayakrounak** [mosip/inji#588]
**Describe the bug**
Remove the check box to provide consent to authenticate from the credential share screen.

**Pre-requisite**
The application should have at least one credential to share.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open the application
2. Click on the QR code scanner
3. Scan the verifier QR code to connect with the verifier application
4. Share credential screen is shown below

**Expected behaviour**
The check box to provide consent to authenticate from the credential share screen should be removed.

**Screenshots**

![image](https://user-images.githubusercontent.com/44160407/221483286-1daf2540-1ff9-4044-a602-1892035e9e65.png)

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Enhancement as discussed with Sasi on 24th Feb 2023

**Comment by PuBHARGAVI** [comment]
"consent to have my photo taken for authentication" check box is removed from sharing vc screen
<img width="293" alt="Screenshot 2023-03-01 at 3 49 17 PM" src="https://user-images.githubusercontent.com/46226958/222111252-5aeb3f97-7da5-4602-b552-cd9d828c1efa.png">

**Comment by krishnakumar4a4** [comment]
@vijay151096 and @PuBHARGAVI is working on this issue.

**Comment by Anushree09-N** [comment]
@nayakrounak As consent on sharing screen is removed , We don't have an option to perform face authentication on Verifier phone. 

Please confirm if this is expected .

**Comment by nayakrounak** [comment]
This is the expectation @Anushree09-N

**Comment by Anushree09-N** [comment]
Verified in:

wallet -
Device: iPhone 8
OS: 16
Inji app version: 0.4.1 (23) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

verifier
Device: Redmi 6A
OS: Android 9
Inji app version : https://github.com/mosip/inji/actions/runs/4343056712
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

Observation: Consent on sharing screen is removed.

![image](https://user-images.githubusercontent.com/79500509/223735317-4b02e05a-7b70-493a-81c3-508a5ff05d7c.png)

**Comment by Kratitva** [comment]
This is fixed as part of release v0.9.1
