### ISSUE TITLE
Update the labels for buttons to "Share" and "Share with Selfie" in credential share screen

### ISSUE THREAD

**Issue by nayakrounak** [mosip/inji#589]
**Describe the bug**
The labels in the credential share screen need to be modified.
* "Accept request and choose ID" to "Share"
* "Accept request and verify" to "Share with Selfie"

**Pre-requisite**
The application should have at least one credential to share.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open the application
2. Click on the QR code scanner
3. Scan the verifier QR code to connect with the verifier application
4. Share credential screen is shown below

**Expected behaviour**
The labels for sharing credentials buttons need to be modified.
* "Accept request and choose ID" to "Share"
* "Accept request and verify" to "Share with Selfie"

**Screenshots**

![image](https://user-images.githubusercontent.com/44160407/221484650-c209725c-2dcb-4e98-9c86-8a0a1cf711c3.png)

**Smartphone (please complete the following information):**

Not Applicable

**Additional context**
Enhancement as discussed with Sasi on 24th Feb 2023.

**Comment by PuBHARGAVI** [comment]
Labels are changed to "share" and "share with Selfie" in english language.
Translation for other languages required apart from english

**Comment by ravikp** [comment]
Issue merged in the PR - https://github.com/mosip/inji/pull/595

**Comment by Alka1703** [comment]
The following PRs implements  text change on the button labels on the consent page: 
- "Accept request and choose ID" to "Share"
- "Accept request and verify" to "Share with Selfie"

PR for mosip/tuvali: [#28](https://github.com/mosip/tuvali/pull/28)
PR for mosip/inji: https://github.com/mosip/inji/pull/595, https://github.com/mosip/inji/pull/597

The PRs have been merged in 28-02-2023 Release and the latest commit id on mosip/inji/develop is [7cdee82](https://github.com/mosip/inji/commit/7cdee829c4c0fb5da4ed75a4d68a52ed8ca36934)

**Comment by Kratitva** [comment]
This is fixed as part of release v0.9.1
