### ISSUE TITLE
Resident receiving multiple credential status issuance emails when they download VC using Inji

### ISSUE THREAD

**Issue by rakhimosip** [mosip/inji#59]
**Describe the bug**
When a resident uses Inji to download a VC they are currently receiving 4 email notifications. Out of that ->
3 emails are sent for credential issuance status
1 email is sent for confirming credential issuance 
Totally the resident receives 4 emails

**To Reproduce**
1. Enroll a resident with an emailID to which you have access and generate UIN
2. Install and setup the Inji app on your smartphone
3. Use the above UIN to download a VC on the app
4. You will receive 4 emails to the configured emailID. Out of that ->
    3 emails are sent for credential issuance status
    1 email is sent for confirming credential issuance 
    The resident receives 4 emails in total.

**Expected behavior**
The resident should receive 2 emails only - 1 email for credential issuance status and 1 email for confirming credential issuance.

**Comment by Sujithbn** [comment]
As of now this issue is not targeted to fix before Beta release.

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/a33e3a65-94fe-42b3-9735-6c1b36c8fa70)
