### ISSUE TITLE
Modify the credential selection process during credential share

### ISSUE THREAD

**Issue by nayakrounak** [mosip/inji#590]
**Describe the bug**
The credential selection process needs to change during credential share.
* The first credential should be auto selected
* The selected credential should be highlighted in green (colour may change based on theme)
* The radio button from the credentials should be removed 

**Pre-requisite**
The application should have at least one credential to share.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open the application
2. Click on the QR code scanner
3. Scan the verifier QR code to connect with the verifier application
4. Share credential screen is shown below

**Expected behaviour**
* The first credential should be auto selected
* The selected credential should be highlighted in green (colour may change based on theme)
* The radio button from the credentials should be removed 

**Screenshots**

![image](https://user-images.githubusercontent.com/44160407/221485425-b959dabb-a2c4-40af-9c9c-a22b2e3ef393.png)

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Enhancement as discussed with Sasi on 24th Feb 2023.

**Comment by nayakrounak** [comment]
Hi @ravikp ,

For this ticket.

We need the auto-selection of the first credential to be fixed by Tomorrow.

The modification for highlighting the selected credential and removal of the radio button can come in later versions of the app.

**Comment by Alka1703** [comment]
The following PRs implements auto selection of first VC on the consent page: 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/28
PR for mosip/inji: https://github.com/mosip/inji/pull/595, https://github.com/mosip/inji/pull/597

The PRs have been merged in 28-02-2023 Release and the latest commit id on mosip/inji/develop is [7cdee82](https://github.com/mosip/inji/commit/7cdee829c4c0fb5da4ed75a4d68a52ed8ca36934)

**Comment by vharsh** [comment]
The following UI enhancement improves UX by highlighting the selected VC with green border and eliminates the radio button from the VCs on share-screen.

PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/29
PR for mosip/inji: https://github.com/mosip/inji/pull/615

The PRs have been merged in 06-03-2023 Release and the latest commit id on mosip/inji/develop is https://github.com/mosip/inji/commit/8867f3cc2dda5fb19c003f85524a8f5cfce61303

**Comment by vharsh** [comment]
> The selected credential should be highlighted in green (colour may change based on theme)

@krishnakumar4a4 Right now the agreed upon colour is green for the VC border let me know if a change has been requested for the same.

**Comment by Anuranjan14** [comment]
The selected credential is getting highlighted in green for both orange and purple themes and radio button from VC is removed.
Attaching the screenshot for the reference.
![image](https://user-images.githubusercontent.com/120705365/227189957-57690020-553d-4c4e-96f4-f3e34782068d.png)

**Comment by Kratitva** [comment]
This is fixed as part of release v0.9.1
