### ISSUE TITLE
Disconnect when transfer complete

### ISSUE THREAD

**Issue by shreeThaanuTw** [mosip/inji#593]
**Describe the bug**
Disconnect connection must happen when transfer complete and UI responds happen in iOS.

**Expected behavior**
Disconnect connection happens when transfer complete.

**Actual behavior**
Disconnect connection not happening.

**Screenshots**

**Add the screenshot of the profile page with commit id**

**Smartphone (please complete the following information):**

- Wallet Device: [e.g. iPhone6]
  - Phone make/model: [e.g. :Vivo Y73]
  - BLE version : [e.g. 4.2]

- Verifier Device: [e.g. iPhone6]
  - Phone make/model: [e.g. :Vivo Y73]
  - BLE version : [e.g. 4.2]

- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]

**Where does the issue occur: Wallet/Verifier?**

**Logs of wallet and verifier:**

**Additional context**

**Comment by Alka1703** [comment]
The following PRs implements disconnection of the verifier and wallet after the VC is transferred and accepted/rejected on the iOS side. 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/28
PR for mosip/inji: https://github.com/mosip/inji/pull/595, https://github.com/mosip/inji/pull/597

The PRs have been merged in 28-02-2023 Release and the latest commit id on mosip/inji/develop is [7cdee82](https://github.com/mosip/inji/commit/7cdee829c4c0fb5da4ed75a4d68a52ed8ca36934)

**Comment by ravikp** [comment]
Closing since issue as it was delivered.
