### ISSUE TITLE
MIMOTO : renew auth token after expiry

### ISSUE THREAD

**Issue by MonobikashDas** [mosip/inji#596]
**Describe the bug**
The current auth token has expiry of 1 day. So every day the wallet binding call will fail once. To handle this system will try once more to renew token automatically.

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what factually occurred.

**Screenshots**

**Add the screenshot of the profile page with commit id**

**Smartphone (please complete the following information):**

- Wallet Device: [e.g. iPhone6]
  - Phone make/model: [e.g. :Vivo Y73]
  - BLE version : [e.g. 4.2]

- Verifier Device: [e.g. iPhone6]
  - Phone make/model: [e.g. :Vivo Y73]
  - BLE version : [e.g. 4.2]

- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]

**Where does the issue occur: Wallet/Verifier?**

**Logs of wallet and verifier:**

**Additional context**

**Comment by Raginikrishnamurthy** [comment]
@MonobikashDas Please let us know the testing strategy to verify this issue.

**Comment by santhoshsunder** [comment]
We took devops help and tried the auto-renewal of the token, but the wallet binding did not work.

screenshot: 
![image](https://user-images.githubusercontent.com/102220709/227178598-e762dba8-82ff-42a2-abdc-9e21b28a99fa.png)

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26845

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed on jira https://mosip.atlassian.net/browse/INJI-41 , hence closing on Github.
