### ISSUE TITLE
Back button implementation on the consent screen 

### ISSUE THREAD

**Issue by Alka1703** [mosip/inji#599]
When we click on the back button(label: SCAN) in the consent page, the wallet goes to the scan page but does not open the scanner and the verifier still shows "Connected to the device. Waiting for ID". We have to disconnect the devices properly and redirect verifier to QR code page and wallet to Scanner page with the camera on.

**Comment by vharsh** [comment]
<img width="782" alt="Screenshot 2023-02-28 at 4 43 58 PM" src="https://user-images.githubusercontent.com/9304050/222048724-8b1db92f-cb58-4f5f-aae3-b0feff3a9d5c.png">

**Comment by ravikp** [comment]
@nayakrounak - Is it possible provide your perspective on how to go about this issue?

**Comment by Sujithbn** [comment]
@ravikp Please remove the back button on the consent screen

**Comment by Anuranjan14** [comment]
We have observed this issue in qa-1201-b2 in below devices:
![image](https://user-images.githubusercontent.com/120705365/225625241-b26c7b45-50a5-40d3-a06a-87e27ce9a3da.png)

Screenshot:
![image](https://user-images.githubusercontent.com/120705365/225626261-ba18b7d6-aa85-489a-b905-2c10f3679310.png)

CommitId:
![image](https://user-images.githubusercontent.com/120705365/225626036-22fed07b-5a0e-46eb-8d7e-a6ab6e7c4ddd.png)
![image](https://user-images.githubusercontent.com/120705365/225626120-6f11c53b-b698-4571-8c18-0db845f3c10c.png)

**Comment by PuBHARGAVI** [comment]
Removed App Back button and also disabled the phone's back button on the consent screen
<img width="376" alt="Screenshot 2023-03-24 at 12 15 39 PM" src="https://user-images.githubusercontent.com/46226958/227445754-1c29d3ce-4a3d-43bf-8f17-46702e435f9e.png">

**Comment by PuBHARGAVI** [comment]
When we are on the consent screen and click on scanner icon of the bottom navigator we are getting the white screen and this is being handled as part of this issue https://github.com/mosip/inji/issues/663

**Comment by krishnakumar4a4** [comment]
> **Removed App Back button and also disabled the phone's back button on the consent screen** On Andorid: <img alt="Screenshot 2023-03-24 at 12 15 39 PM" width="376" src="https://user-images.githubusercontent.com/46226958/227445754-1c29d3ce-4a3d-43bf-8f17-46702e435f9e.png"> On Iphone: ![image](https://user-images.githubusercontent.com/46226958/227454218-81901a09-febb-4076-a7b8-ed40ece82b73.png)

Quoted reply from @PuBHARGAVI for fix details, the fix for this on Verifier side is done as part of 24-03-2023

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by santhoshsunder** [comment]
Verified this issue in the new build, after @Anuranjan14 tested the back button is removed now, and it is working as expected now, now App Back button is removed and the phone's back button also disabled on the consent screen

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/228199224-d3871c6f-820e-4b6e-9c1a-e752b2e783da.png)

Tested on :
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622
