### ISSUE TITLE
iOS Code Refactoring from SIngleton

### ISSUE THREAD

**Issue by shreethaanu** [mosip/inji#603]
**Is your feature request related to a problem? Please describe.**
This task is to remove singleton code from iOS Tuvali repo.

**Describe the solution you'd like**
The singleton class can be removed and can be replaced with normal classes with initialisation

**Comment by vharsh** [comment]
The following change is available on branch=0.9 & on branch=develop as part of the 17th March, 2023 release.

PR for mosip/inji(branch=develop): https://github.com/mosip/inji/pull/655,
commit: https://github.com/mosip/inji/commit/aff1c4f7b96d27f1c8f54e62d3f03a7086473f35
PR for mosip/inji(branch=0.9): https://github.com/mosip/inji/pull/653
commit: https://github.com/mosip/inji/commit/4c2ca4b0ea400cb29cb59ee6a87106e2542023da

**Comment by Anushree09-N** [comment]
Verified in:
- Wallet Device: iPhone 11
  - Phone make/model: iPhone 11
  - OS: 15
  - BLE version : 5.0

- Verifier Device: Galaxy A03 core
  - Phone make/model: Galaxy A03 core
  - OS: Android 11 
  - BLE version : 4.2

- Inji app version: 
![IMG20230320115926](https://user-images.githubusercontent.com/79500509/226296135-08b3a12c-4ba5-43dc-98e0-3e93510aa6ec.jpg)

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

Multiple attempts of sharing is working.
![IMG20230320161252](https://user-images.githubusercontent.com/79500509/226317111-42ba3ef8-98d2-4f05-b95c-86c8306d6ef6.jpg)
