### ISSUE TITLE
Language selection in Inji

### ISSUE THREAD

**Issue by nayakrounak** [mosip/inji#606]
**Problem Statement**

The language selection in Inji is not properly handled in the current version.

**Resolution**

* Remove the language selection option from the header section of the application.
* The language option in the profile section looks like a subheading.
    * Add a language logo in front of the language option.
* The language options shown in the list of languages should be in native languages example - Hindi should be represented in English.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/44160407/222504290-3bb4b13a-2806-4e45-88e8-07fb294257d9.png)

![image](https://user-images.githubusercontent.com/44160407/222505051-cab26d16-9e9b-4239-b280-21d712d8988d.png)

**Comment by vijay151096** [comment]
Removed language selection icon from header and Updated the languages labels in the profile with native labels

- Removed the language selection icon from header in all the screens

<img width="426" alt="Screenshot 2023-03-03 at 4 14 08 PM" src="https://user-images.githubusercontent.com/94220135/222700995-cc4b2622-7a30-4d0a-8f4e-c77920626f57.png">


<img width="427" alt="Screenshot 2023-03-03 at 4 15 04 PM" src="https://user-images.githubusercontent.com/94220135/222700938-a421b739-2307-4970-92be-a478660dd734.png">


<img width="430" alt="Screenshot 2023-03-03 at 4 14 56 PM" src="https://user-images.githubusercontent.com/94220135/222700954-34bf9e38-7b2f-4437-8227-c7dca781791f.png">

- Added language selection icon besides Languages in Profile Screen

<img width="428" alt="Screenshot 2023-03-03 at 4 14 36 PM" src="https://user-images.githubusercontent.com/94220135/222700984-b7deb4b3-2e25-4a4c-8680-9f9b94bbc6cb.png">

- Updated the languages labels in the profile with native labels

<img width="431" alt="Screenshot 2023-03-03 at 4 14 45 PM" src="https://user-images.githubusercontent.com/94220135/222700977-7b2c1e95-36d2-4e46-82b6-b6b83036b0b7.png">

**Comment by vharsh** [comment]
The following UI enhancement shows the native language in corresponding language scripts and not in english. It also removes language changer icon from the top of the screen and keeps the one in the profile page.

PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/29
PR for mosip/inji: https://github.com/mosip/inji/pull/615

The PRs have been merged in 06-03-2023 Release and the latest commit id on mosip/inji/develop is https://github.com/mosip/inji/commit/8867f3cc2dda5fb19c003f85524a8f5cfce61303

**Comment by Kratitva** [comment]
This is fixed as part of release v0.9.1
