### ISSUE TITLE
Add a "About App" Option in Settings Page

### ISSUE THREAD

**Issue by nayakrounak** [mosip/inji#608]
**Problem Statement**

Information like "Powered By BLE", "Version" and "tuvali-version" are application meta information that can be grouped together and in a new section.

**Resolution**

Create a new Option in the Settings Screen called "About Inji".
* Add a very brief note on Inji.
* Add Version details
* Add Tuvali Version details
* Add Powered By BLE

**Comment by nayakrounak** [comment]
@SwatiPeriwal, Please share a short note on Inji here.

**Comment by SwatiPeriwal** [comment]
@PuBHARGAVI    Inji is a mobile app that can be used as a digital wallet to store credentials. It also allows verification of identity in both offline and online modes, at any place and time.    @nayakrounak please approve!

**Comment by PuBHARGAVI** [comment]
**Added About inji Screen in the UI:**
Profile Screen:
<img width="393" alt="Screenshot 2023-03-23 at 6 02 52 PM" src="https://user-images.githubusercontent.com/46226958/227204703-9d4541c0-8a95-49b7-a02c-eaf1d08df646.png">

Orange Theme:
<img width="386" alt="Screenshot 2023-03-23 at 6 00 54 PM" src="https://user-images.githubusercontent.com/46226958/227204303-be24b58f-1d60-4539-acda-27b2fa96d1ac.png">

Purple Theme:
<img width="391" alt="Screenshot 2023-03-23 at 6 01 39 PM" src="https://user-images.githubusercontent.com/46226958/227204459-5c9e0aa5-0e09-4038-a1f2-fcb024959e73.png">

**Comment by PuBHARGAVI** [comment]
- Translations are added for the About Inji screen header title
- Translations are not added for the content it is available only in english and the text is not configurable right now

**Comment by krishnakumar4a4** [comment]
> **Added About inji Screen in the UI:** Profile Screen: <img alt="Screenshot 2023-03-23 at 6 02 52 PM" width="393" src="https://user-images.githubusercontent.com/46226958/227204703-9d4541c0-8a95-49b7-a02c-eaf1d08df646.png">
> 
> Orange Theme: <img alt="Screenshot 2023-03-23 at 6 00 54 PM" width="386" src="https://user-images.githubusercontent.com/46226958/227204303-be24b58f-1d60-4539-acda-27b2fa96d1ac.png">
> 
> Purple Theme: <img alt="Screenshot 2023-03-23 at 6 01 39 PM" width="391" src="https://user-images.githubusercontent.com/46226958/227204459-5c9e0aa5-0e09-4038-a1f2-fcb024959e73.png">

Quoted reply from @PuBHARGAVI for fix details, the fix is done as part of 24-03-2023 release

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by Anushree09-N** [comment]
**Verified in :**
iphone 8	| iphone 16 BLE 5.0
k20 pro | Android 11 BLE 5.0

 **app commit id:** 
![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

New field is added "About Inji" in settings page and below details are added as part of info in the screen.

- A very brief note on Inji.
- Version details
- Tuvali Version details


**Android orange theme:** 

![IMG20230328115420](https://user-images.githubusercontent.com/79500509/228147291-ea5c790f-6279-49b4-b4f1-91f369dd2803.jpg)


**iOS purple theme:** 

![IMG20230328115430](https://user-images.githubusercontent.com/79500509/228147369-43336bdf-9edb-4f80-a986-687b1bd5695e.jpg)


- Powered By BLE is not added 
@ravikp conveyed that Powered by BLE will not be seen in the app anymore.
