### ISSUE TITLE
iOS - Allow user to recover when Bluetooth permission is denied

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#613]
## TODO

1. When Bluetooth permission is denied, the user should be shown a text about the missing permission.
2. Provide a way to enable Bluetooth permission again
3. Once the permission is provided, the user should be able to move to next state

**Comment by krishnakumar4a4** [comment]
@Alka1703 will be looking into this.

**Comment by krishnakumar4a4** [comment]
Dhivya is looking into this.

**Comment by dhivya0413** [comment]
Kindly provide the error message text regarding the bluetooth permission and action button text. 

@nayakrounak

**Comment by nayakrounak** [comment]
Hi @dhivya0413 , Please find the messages below:

* Bluetooth Permission not available: "Please enable bluetooth permissions to support local sharing"
* Bluetooth is turned off: "Please turn on bluetooth to support local sharing."
* Action Button: "Allow Bluetooth Permissions"

**Comment by Anushree09-N** [comment]
As per @krishnakumar4a4  the behaviour/ changes are  only applicable in iOS platform
