### ISSUE TITLE
Handling DB limits for Save VC

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#616]
**Is your feature request related to a problem? Please describe.**
When clicking on Save button, Sometime Save button is not doing anything. 

**Describe the solution you'd like**
* Change the default Max size to reasonable size[30mb]
* Show Error on screen if failed to save
* Remove older received VC’s when size limit hits

**Additional context**
React Native AsyncStorage has a default limit of 6mb for total storage allowed and 2mb for each individual item.

**Comment by ravikp** [comment]
The following two items

* Show Error on screen if failed to save
* Remove older received VC’s when size limit hits

shall be taken as an enhancement. The increase from 6MB to 30MB shall be done to unblock.

**Comment by tilak-puli** [comment]
Increased the DB Limits to 30MB in https://github.com/ravikp/inji/pull/12

Yet to be merged to mosip/Inji

**Comment by ravikp** [comment]
We shall take the 

* Show Error on screen if failed to save
* Remove older received VC’s when size limit hits

into a different issue.

**Comment by krishnakumar4a4** [comment]
## Summary of the changes
- We have increased the Sqlite DB limit to 30MB for Android. The default size was 6MB.

This change is delivered as part of 09-03-2023 release 
INJI PR link: https://github.com/mosip/inji/pull/630

**Comment by santhoshsunder** [comment]
Verified the bug with the size less than 30 MB, below are the observations:

1. Save button is getting disabled after first click.
2. Able to share multiple unique VCs and save the same in the Verifier phone without any hassle.
3. Able to download VC too.

When the size crosses 30 MB, we are facing issues which will be tracked in the issue #625
Hence closing the bug.

Screenshot of the build : 
![image](https://user-images.githubusercontent.com/102220709/225628627-90d93520-9997-4dfb-aed4-f0296181acf4.png)

- Wallet Device: Device B

Phone make/model: Redmi Note 10 lite
OS: Android 10
BLE version : 5.0

- Verifier Device: Device A

Phone make/model: Vivo Y73
OS: Android 12
BLE version : 5.0

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4374171157
