### ISSUE TITLE
Remove Accept/Discard Buttons on Verifier

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#617]
* Enhance VC review UI flow to save without need of button clicks.
* Automatically Accept the received VC.
* Add a button `View Received ${ID}s` to go to received tab in place save button.

**Comment by vharsh** [comment]
The following UI enhancement is available on branch=0.9 & on branch=develop as part of the 17th March, 2023 release.

PR for mosip/inji(branch=develop): https://github.com/mosip/inji/pull/655,
commit: aff1c4f
PR for mosip/inji(branch=0.9): https://github.com/mosip/inji/pull/653,
commit: 4c2ca4b

**Comment by Anushree09-N** [comment]
Verified in:
- Wallet Device: iPhone 11
  - Phone make/model: iPhone 11
  - OS: 15
  - BLE version : 5.0

- Verifier Device: Galaxy A03 core
  - Phone make/model: Galaxy A03 core
  - OS: Android 11 
  - BLE version : 4.2

- Inji app version: 
![IMG20230320115926](https://user-images.githubusercontent.com/79500509/226296135-08b3a12c-4ba5-43dc-98e0-3e93510aa6ec.jpg)

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

Save ID and Discard buttons are no more seen and Verifier have an option to directly navigate to received cards section by click of "Review received cards" button.
![IMG20230320143626](https://user-images.githubusercontent.com/79500509/226297505-34f7ce3c-5d90-464b-87ad-81e65298aa9d.jpg)
