### ISSUE TITLE
UIN should be removed from the Add ID screen dropdown

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#620]
**Describe the bug**
UIN should be removed from the Add ID screen dropdown

**To Reproduce**
Inji app is installed on the any device.

1. Click on Add ID

**Expected behavior**
As UIN details are removed from the mobile policy hence UIN label in the dropdown and UIN refering words from AID screen has to be removed

**Actual behavior**
UIN label is still present in the ADD ID screen dropdown and AID screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/223390308-0115df45-1067-47ee-876c-3039a370e693.png)

![image](https://user-images.githubusercontent.com/79500509/223391321-bf96344c-97f7-4a54-ad76-867eef5a4749.png)

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/79500509/223392158-4481f5d8-72e3-4f32-b095-9897c607122a.png)

**Smartphone (please complete the following information):**
 This issue is not device specific

    Device: Redmi 7A
  - Phone make/model: Redmi 7A
  - OS: Android 10
  - BLE version : 4.2

- Mimoto version: 1.2.0.1
- MOSIP Version: 1.2.0.1 
- MOSIP Server: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
Issue is applicable for both wallet and verifier.

**Logs of wallet and verifier:**
N/A

**Additional context**
Open question: Is these dropdown labels are configurable? If yes please link the config path here.

**Comment by ravikp** [comment]
@Sujithbn - Is there any enhancement planned on what is being reported as a bug? Can someone link me to the story/enhancement?

**Comment by santhoshsunder** [comment]
This bug is not valid anymore, hence closing the bug.
