### ISSUE TITLE
Fix android crash on app launch after app upgrades

### ISSUE THREAD

**Issue by vharsh** [mosip/inji#622]
**Describe the bug**

In most cases the app works as normal, but after a series of use-and-appUpgrades, the app fails to start and always crashes as soon as the app is launched by tapping on it's icon, no splash screen is visible, just the Android system dialog box pops up specifying that the app has crashed.

**To Reproduce**

1. Install an older version of Inji app
2. Use the app to transfer VCs
3. Upgrade the app
4. Repeat steps 1-3 until the app crashes on launch

_I installed release apps from these release dates to reproduce this bug_; `20th Feb --> 28th Feb --> 20th Feb --> 28th Feb --> 6th March`.

**Expected behavior**

On app upgrades the app should not crash.

**Actual behavior**

After usage & upgrades of the app, the app fails to start and this is a known issue for a certain range of React native versions as documented [here](https://github.com/facebook/SoLoader/issues/77).

**Add the screenshot of the profile page with commit id**

The bug applies to all versions of Android app on Android 9, 10, 11 as documented by the issue on SoLoader repository

**Smartphone:**

This has been successfully reproduced on Nokia 6.1 Plus(_Android 10, BLE 5.0_). Since this bug is a react native issue, wallet & verifier details are not relevant here as the app fails to start. This is a React Native issue, so it applies to more devices.

**Further relevant details:**

React Native version: 0.64.4
Original issue: https://github.com/facebook/SoLoader/issues/77

**Logs:**

[android-onlaunch-crash.txt](https://github.com/mosip/inji/files/10909628/android-onlaunch-crash.txt)

**Comment by vharsh** [comment]
@ravikp please attach relevant labels

**Comment by santhoshsunder** [comment]
verified this issue on the new build, I tried to install 3 different old builds back again and again, just like @vharsh mentioned in above, the issue is not observed anymore, the task is able to close

Tested on : 

device : pixel 6
ble : 5.2
android : 13 

device : redmi k20 pro
ble : 5.0
android : 11

device : vivo y73
ble : 5.0
android : 12

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079

**Comment by vharsh** [comment]
@Anushree09-N @santhoshsunder Can this issue be closed now?

**Comment by santhoshsunder** [comment]
@vharsh the issue can be closed, issue is not replicating, hence closing this issue
