### ISSUE TITLE
Android - app stuck after success full IDP login 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#623]
**Describe the bug**
The app is stuck in a loading state after successful IDP login 

**To Reproduce**
Prerequisite: one VC should be downloaded and binded, have idp compatible login with qr portal ready

1. Authenticate app and get into it
2. Go to the scanner page
3. Scan the IDP portal
4. Select a binded VC and perform a successful login attempt
5. in the last successful full log in, on the acknowledgment page
6. click on the okay button 

**Expected behavior**
It should load successfully and should take to history screen  

**Actual behavior**
The device is stuck in the loading state, but its successfully logged in the web screen 

**Screenshots**
<img width="956" alt="image" src="https://user-images.githubusercontent.com/102220709/223441460-8c141d38-e04a-4660-941b-2326a70abbf8.png">

**Device detials :**
Phone make/model: Redmi note 10 lite 
OS: Android 10
BLE version : 5.0
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4343056712

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/8bb348d9-2140-437c-b07e-11bdf6334c45)
