### ISSUE TITLE
Increase and set failure frame limit for VC transfer

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#627]
### TODO
Android:
- At present, Android only does one failure frame. We need to increase it a pre-configured number of frames

IOS:
- At present, IOS does failure frames without any limit. We need to set a limit and make it consistent with Android implementation

**Comment by vharsh** [comment]
The following change is available on branch=0.9 & on branch=develop as part of the 17th March, 2023 release and now the iOS will now only request for transmission report only for 5 times, this is a good sufficiently high number we've come up with and if this number is breached, it'd be better if the user re-transmits the VC instead.

PR for mosip/inji(branch=develop): https://github.com/mosip/inji/pull/655,
commit: aff1c4f
PR for mosip/inji(branch=0.9): https://github.com/mosip/inji/pull/653
commit: 4c2ca4b

**Comment by ravikp** [comment]
Normal BLE sharing should work.

**Comment by Anushree09-N** [comment]
Verified in:
- Wallet Device: iPhone 11
  - Phone make/model: iPhone 11
  - OS: 15
  - BLE version : 5.0

- Verifier Device: Galaxy A03 core
  - Phone make/model: Galaxy A03 core
  - OS: Android 11 
  - BLE version : 4.2

- Inji app version: 
![IMG20230320115926](https://user-images.githubusercontent.com/79500509/226296135-08b3a12c-4ba5-43dc-98e0-3e93510aa6ec.jpg)

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

Multiple attempts of sharing is working.
![IMG20230320161252](https://user-images.githubusercontent.com/79500509/226317111-42ba3ef8-98d2-4f05-b95c-86c8306d6ef6.jpg)
