### ISSUE TITLE
Android - Button are not aligned properly in purple APK

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#631]
**Describe the bug**
verify ID buttons are not aligned properly in the purple theme APK, while IDP login

**To Reproduce**
Prerequisite: one VC should be downloaded and binded, have idp compatible login with qr portal ready

1. Authenticate the app and get into it
2. Go to the scanner page
3. Scan the IDP portal

 **Expected behavior**
The app should be aligned properly based on all different phones 

**Observed**
The button is hidden behind the phones navigation bar, but still clickable 

**Screenshots**
![Screenshot_2023-03-09-19-42-54-271_io mosip residentapp](https://user-images.githubusercontent.com/102220709/224054932-6579ae46-3b1e-4d13-8d96-a756ca4f5aa1.jpg)

**Smartphone :**
Device : redmi note 10 lite 
OS : android 10 
APP link : https://github.com/mosip/inji/actions/runs/4374183074
BLE version : 5.0
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net

**Comment by vharsh** [comment]
The following change is available on branch=0.9 & on branch=develop as part of the 17th March, 2023 release and it has been fixed and it can be confirmed post it's verified on the original device where it was seen first.

PR for mosip/inji(branch=develop): https://github.com/mosip/inji/pull/655,
commit: https://github.com/mosip/inji/commit/aff1c4f7b96d27f1c8f54e62d3f03a7086473f35
PR for mosip/inji(branch=0.9): https://github.com/mosip/inji/pull/653
commit: https://github.com/mosip/inji/commit/4c2ca4b0ea400cb29cb59ee6a87106e2542023da

**Comment by ravikp** [comment]
This defect can be tested on purple build only.

**Comment by santhoshsunder** [comment]
Verified this issue, the issue is not observed, the button is aligned properly now, as shown in the below screenshot, hence closing this bug

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/226523711-6f26cc75-b02b-4312-a476-c71d2b3942f6.png)

Device : redmi note 10 lite
OS : android 10
APP link : https://github.com/mosip/inji/actions/runs/4447486079
BLE version : 5.0
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
