### ISSUE TITLE
Android - we are able login through IDP QR code login using received ID's

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#634]
**Describe the bug**
Android - we are able login through IDP QR code login using the received ID's, only on the purple apk

**To Reproduce**
Prerequisite: one VC should be downloaded and binded, have VC's in the received id screen, have idp compatible login with qr portal ready

1. Authenticate the app and get into it
2. Go to the scanner page
3. Scan the IDP portal
4. manually verify the link id and continue to the next screen

**Expected behavior**
We shouldn't see downloaded VC's in the, select ID screen while logging in to QR code login 

**Actual behavior**
We are observing received id inside select ID screen

**Screenshots**
https://user-images.githubusercontent.com/102220709/224642362-a9a21ae0-939b-4abb-8bfb-ae50557f1ee8.mp4

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/224642476-90a00ccd-8d41-403d-a171-5e1787ddbab2.png)

**Smartphone :**
Device : Pixel 6
OS : android 13
APP link : https://github.com/mosip/inji/actions/runs/4376897206
MOSIP server : mec.mosip.net

**Comment by Sujithbn** [comment]
Assigned this to Mono to add the root cause of the issue.

**Comment by vijay151096** [comment]
Fixed the Issue of Showing the Received VC's in the Sharing Screen When IDP Portal QR Code is Scanned. 

**Steps To Reproduce :**

1. Have a VC in the myVCs tab
2. Activate the VC in the myVC.
3. Get a Binded VC shared from another device.
4. Make sure you have VC activated in the MyVC and Received VC and Both are Binded.
5. Goto IDP Portal
6. Scan the QR Code
7. you can see the VC that are available in myVC's and received VC's.

**Here is the Screen Shots :**

**Current State of the Application before Sharing VC :** 
<img width="419" alt="Screenshot 2023-03-21 at 9 46 12 AM" src="https://user-images.githubusercontent.com/94220135/226516073-c32a76a8-f0b2-4dc8-a059-e1dd703d8c7f.png">
<img width="417" alt="Screenshot 2023-03-21 at 9 46 18 AM" src="https://user-images.githubusercontent.com/94220135/226516089-a297e325-6d06-4177-b97c-4dd4d8f551ac.png">


**VC Sharing Screen After Scanned the IDP Portal QR Code** 
<img width="423" alt="Screenshot 2023-03-21 at 9 45 50 AM" src="https://user-images.githubusercontent.com/94220135/226516146-38e7c0fd-b192-41ab-b9dd-c8573d27fd9f.png">

We can see only cards in MyVCs Tab is shown not the Received VC's.

**Comment by santhoshsunder** [comment]
Verified this issue in the new purple build, and the issue is not occurring anymore, we are not seeing received VC's while QR ode login, attaching screenshots below and hence closing this bug

Screenshot : 
https://user-images.githubusercontent.com/102220709/228258817-9a7bff28-7072-401a-9023-af8d95213d9d.mp4

Tested on:
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511543895
