### ISSUE TITLE
Green border missing on purple theme 

### ISSUE THREAD

**Issue by krishnakumar4a4** [mosip/inji#635]
### TODO
- In purple theme, Missing green border on selected VC on consent screen. Whereas it is available in Orange theme.

**Comment by PuBHARGAVI** [comment]
In purple theme added Green border for the selected card in the sharing card screen 
<img width="333" alt="Screenshot 2023-03-14 at 11 14 57 AM" src="https://user-images.githubusercontent.com/46226958/224980774-2951f1da-a5dc-4287-959c-22b9c3e03707.png">

**Comment by ravikp** [comment]
This can be tested in purple theme. Kindly generate a purple theme build.

**Comment by santhoshsunder** [comment]
verified this task in the new build, we are seeing green borders around the VC, iam attaching screenshots below, hence this task can be closed 

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/226524424-414c1a68-8914-4ffd-871a-ea9777ef50d1.png)
![image](https://user-images.githubusercontent.com/102220709/226524435-e56f47c3-72bb-4efa-977d-dfd649c1c470.png)

Device : redmi note 10 lite
OS : android 10
APP link : https://github.com/mosip/inji/actions/runs/4447486079
BLE version : 5.0
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net

**Comment by Raginikrishnamurthy** [comment]
@Sujithbn the feature change in this task has been verified. Kindly get it closed.

**Comment by Sujithbn** [comment]
@Raginikrishnamurthy As this is a bug assigning back to QA team for closure
