### ISSUE TITLE
IOS - unable to download VC using iphones scan text feature

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#639]
**Describe the bug**
unable to download VC using iphones scan text feature

**To Reproduce**
1. Unlock the app
2. click on add ID and use scan text to copy VID 
3. Click on the generate ID

**Expected behavior**
we are unable to download VC using this feature 

**Actual behavior**
we are unable to download VC using this feature, the OTP is triggered, but the VC is not been downloading

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/224690840-1091913f-25a2-4a65-997c-a202b624b727.png)

**Smartphone :**
Device: iPhone 11
OS: 15.4.1
Inji app version: 0.4.0 (25) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/600b3da0-ca3e-49d5-bb54-732084d1c6f3)
