### ISSUE TITLE
IDP QR code login is not working

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#640]
**Describe the bug**
IDP QR code login is not working in both IOS and android 

**To Reproduce**
Prerequisite: one VC should be downloaded and binded, have VC's in the received id screen, have idp compatible login with qr portal ready

1. Authenticate the app and get into it
2. Go to the scanner page
3. Scan the IDP portal

**Expected behavior**
Should be able to scan the page, and login into the portal successfully 

**Actual behavior**
We are not able to scan the IDP portal QR code, we are facing a error, in both android and IOS

**Screenshots**
https://user-images.githubusercontent.com/102220709/224710170-af0f150e-119f-4843-a36a-c73d6ef33300.mp4

**Mobile details :**
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP server : mec.mosip.net
APP link : https://github.com/mosip/inji/actions/runs/4376878070
Testflight : 0.4.0 (27)

**Comment by ckm007** [comment]
https://mosip.atlassian.net/browse/DSD-2263
Applied the fix as per the details mentioned in the above DSD ticket.

**Comment by santhoshsunder** [comment]
Tested this issue in the new build, on the mac env, and the issue is not observed anymore, we are able login to QR code login successfully in both android and ios , attaching the screenshot and the device details below

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/225599360-570da192-0fa3-4596-b996-9fd340c38975.png)

Tested on : 
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP server : mec.mosip.net
APP link : https://github.com/mosip/inji/actions/runs/4376878070
Testflight : 0.4.0 (27)
