### ISSUE TITLE
Resident demographic data are not rendered in requested language

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#656]
**Describe the bug**
Resident demographic data are not rendered in requested language

**To Reproduce**
Prerequisite: Environment configured language is eng & ara. Create packet from regclient by filling data in both the language. 

1. Unlock the app
2. Navigate to settings page
3. change the Language to arabic
4. Navigate back to HOME page
5. Click on ADD ID
6. Enter VID
7. Download VC and view

**Expected behavior**
Download credential API in mimoto is returning back the response in two language, likewise app when VC download is requested in arabic language screen data of VC should also be in arabic.

**Actual behavior**
When VC is requested all labels are chenged to arabic but demographic details of the credentials are rendered in arabic language.

**Screenshots**
Download credential API:
![image](https://user-images.githubusercontent.com/79500509/226260300-1fb2b2eb-2732-40b5-8b54-465b85f8f44e.png)

VC in the Inji app after download:
![image](https://user-images.githubusercontent.com/79500509/226263513-8362d46e-3225-4068-821e-4eb96bd87250.png)

**Add the screenshot of the profile page with commit id**
![IMG20230320115926](https://user-images.githubusercontent.com/79500509/226265146-552267bc-15d8-449b-b175-fb20d31bb5c8.jpg)

**Smartphone (please complete the following information):**

Device: Redmi note 10 lite
  - Phone make/model: Redmi note 10 lite
  - OS: Android 10
  - BLE version : 5.0
  - App link: https://github.com/mosip/inji/actions/runs/4447474480

- Inji app version: 
![IMG20230320115926](https://user-images.githubusercontent.com/79500509/226265146-552267bc-15d8-449b-b175-fb20d31bb5c8.jpg)

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A

**Logs of wallet and verifier:**
Cannot get logs in release build

**Additional context**
This is not device specific issue.
VID: 2396187952165042
Response from API: 

[responsedwnldcred1.txt](https://github.com/mosip/inji/files/11014963/responsedwnldcred1.txt)

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed in jira https://mosip.atlassian.net/browse/INJI-44 , hence closing on Github.
