### ISSUE TITLE
Android: Upon scanning the qr code, wallet device still getting scan qr code screen for a while before navigating to sharing screen.

### ISSUE THREAD

**Issue by Anuranjan14** [mosip/inji#657]
**Describe the bug**
Upon scanning the qr code,wallet device still getting scan qr code screen for a while before navigating to sharing screen.

**To Reproduce**
1. Open scanner on wallet and qr code in verifier
2. Scan  the qr code from wallet
3.Observe the error on wallet device

**Expected behavior**
It should redirect to the sharing screen where we have downloaded credentials

**Actual behavior**
Wallet device is getting scan qr code screen for a while before navigating to sharing screen.

Video:

https://user-images.githubusercontent.com/120705365/226272522-29941af8-a16b-47e0-8bd5-6824e5bb7056.mp4

https://user-images.githubusercontent.com/120705365/226272557-ff238b84-5d2f-499e-ae0b-f49b18861180.mp4

**Add the screenshot of the profile page with commit id**
`
![image](https://user-images.githubusercontent.com/120705365/226273574-1489d4cd-790a-43dd-a911-33d4faf11eee.png)

**Smartphone (please complete the following information):**

- Wallet Device: 
  - Phone make/model: Redmi 6A
  - OS: Android 9
  - BLE version : BLE 4.2

- Verifier Device: 
  - Phone make/model: Redmi Note 10 Lite
  - OS: Android 10
  - BLE version : BLE 5.0

- Inji app version: https://github.com/mosip/inji/actions/runs/4447486079
- Mimoto version: 1.2.0.1
- MOSIP Version: 1.2.0.1

**Where does the issue occur: Wallet/Verifier?**
Wallet

**Logs of wallet and verifier:**
We can not get logs because this is release version
**Additional context**
This issues are reproducable when devices are exchanged (vice versa).

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/aae8fb4c-50bd-4336-a895-bdefcf42b3a7)
