### ISSUE TITLE
Android : The mobile camera is not opening on the scan page when the flight mode is turned

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#658]
**Describe the bug**
The mobile camera is not opening on the scan page when the flight mode is turned on the specific device 

**To Reproduce**
1. Turn on the flight mode 
2. Unlock the app using passcode / biometrics
3. Go to SCAN (second icon from left).

**Expected behavior**
The camera should open and sharing should be successful on all devices 

**Actual behavior**
The camera is not opening in specific devices, when the flight mode is turned on 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/226296261-ae0e870d-3fed-4098-b232-49d1d5a7f306.png)

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/226296343-7a8055dd-316d-4cc5-b5cf-c08da5d7aba1.png)

**Smartphone :**
device : redmi k20 pro
ble : 5.0
android : 11
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079

**Comment by Kratitva** [comment]
This issue is now tracked in JIRA: https://mosip.atlassian.net/browse/INJI-69

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed on jira https://mosip.atlassian.net/browse/INJI-69, hence closing on github.
