### ISSUE TITLE
Wallet stuck in sharing state even after disconnecting the verifier.

### ISSUE THREAD

**Issue by damodarguru** [mosip/inji#659]
**Describe the bug**
Wallet stuck in sharing state even after disconnecting the verifier.
**To Reproduce**

1. Open QR code in verifier.
2. Open scanner in wallet.
3. Scan the QR code from wallet.
4. Now select 'Share with Selfie', front camera will open.
5. Click on cancel button on verifier.
6. On wallet navigate back to previous screen using back option.
7. Now click on Share button.

**Expected behavior**
We should get disconnect message on wallet as verifier was already disconnected.

**Actual behavior**
Wallet stuck in sharing state even after disconnecting the verifier.

**Video**
https://user-images.githubusercontent.com/124761463/226352532-d80543af-9b76-460e-b79c-ea67a5dba64d.mp4
![image](https://user-images.githubusercontent.com/124761463/226353364-a70b13cd-ff97-4ebd-a1cf-7c84017b423b.png)

**Smartphone (please complete the following information):**

- Wallet Device: Redmi Note 10 Lite
  - OS: Android 10
  - BLE version : 5.0

- Verifier Device: Vivo Y73
  - OS: Android 12
  - BLE version: 5.0

- Inji app version: https://github.com/mosip/inji/actions/runs/4447486079
- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet

**Logs of wallet and verifier:  We can't get logs as it is a release build.

**Additional context**

**Comment by nayakrounak** [comment]
Hi @krishnakumar-tw, wouldn't this timeout automatically?

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/db2eaa98-43f5-4e35-baac-3145e28cba36)
