### ISSUE TITLE
Back button Implementation on View VC screen of Verifier

### ISSUE THREAD

**Issue by tilak-puli** [mosip/inji#660]
**Is your feature request related to a problem? Please describe.**
Similar #599 , Clicking on back button of Verifier VC screen goes back to white screen.

**Describe the solution you'd like**
![Screenshot_20230321-150139](https://user-images.githubusercontent.com/34330361/226566310-67a9fdb9-deff-4198-91bc-c5e05209ef20.png)

Handle this by doing one of the following(Please discuss with @nayakrounak)
1. Remove the back button functionality 
2. Safely start new transfer by showing new QR code.

**Comment by krishnakumar4a4** [comment]
This issue will be addressed as part of fix made for #669

**Comment by krishnakumar4a4** [comment]
The fix is given in 24-03-2023 release.

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by santhoshsunder** [comment]
Verified this enhancement in the new build, it's working as expected, the back button is takes back to the QR code screen, and new QR code is generated as expected 

Screenshot : 
https://user-images.githubusercontent.com/102220709/228202011-eea38da7-f392-452e-a0e1-a64a8e7e82b2.mp4

Tested on :
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622
