### ISSUE TITLE
Increase Retry Of Failure Frame to 15 

### ISSUE THREAD

**Issue by Alka1703** [mosip/inji#668]
Some of the devices with smaller negotiated MTU values fails to transfer larger VCs as there are a large number of missing chunks

**Comment by Alka1703** [comment]
Please use iphone 7 and Redmi 7A for this testing

**Comment by Raginikrishnamurthy** [comment]
@Alka1703 Please elaborate on the testing strategy.

**Comment by Alka1703** [comment]
The device combination Redmi 7A and iphone 7 agrees on a lesser MTU value(total number of bytes that can be written at one go). So when transferring large VCS(~700KB), there are a lot of failures which couldn't be handled in 5 retries. So we have increased the retries to 15. 
This will reduce the failure between these two devices.

**Comment by Anushree09-N** [comment]
**Verified in :**
Wallet: iphone 7 | iphone 15.6 BLE 4.2
Verifier: Redmi 7A | Android 10 BLE 4.2

 **app commit id:** 
![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

Attempted VC transfer for 17 times out of which 1 attempt of transfer failed i.e failed in 3 rd attempt.

VC size used for testing: 716.83 KB
VID : 6083794706725109
