### ISSUE TITLE
Reset the Request state machine when user clicks on back button or verifier icon in Incoming Card screen

### ISSUE THREAD

**Issue by PuBHARGAVI** [mosip/inji#669]
**Describe the bug**
When user clicks on app back button or phone back button or verifier icon in the Incoming Card screen it is showing white screen in the REQUEST screen instead of QR code

**To Reproduce**
prerequisite: Device A --> Verifier
Device B --> Wallet

Steps :

1. Open QR code in Device A
2. Open scanner in Device B
3. Scan the QR code from Device B
4. Select the VC to share
5. Click on the app back button or phone back button or verifier icon in the Verifier

**Expected behavior**
Should see QR code in the Request screen

**Actual behavior**
Seeing white screen instead of QR code

**Screenshots for the issue**
<img width="338" alt="Screenshot 2023-03-23 at 7 30 06 PM" src="https://user-images.githubusercontent.com/46226958/227227466-8a601432-713c-4f19-9baa-bf5e64171c3e.png">

<img width="335" alt="Screenshot 2023-03-23 at 6 51 54 PM" src="https://user-images.githubusercontent.com/46226958/227217245-aad213e4-5422-448f-bc52-8cd7a2a22577.png">

**Comment by krishnakumar4a4** [comment]
The fix is given in 24-03-2023 release:

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by Anushree09-N** [comment]
**Verified in :**
Verifier: k20 pro | Android 11 BLE 5.0
Wallet:  iphone 8 | iphone 16 BLE 5.0

**app commit id:** 
![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

When user clicks on app back button or phone back button or verifier icon in the Incoming Card screen it is displaying qr code, Able to pair and share VC successfully. Working as expected.


https://user-images.githubusercontent.com/79500509/228144526-85b5edf1-b9ac-4a03-8de1-17405922776f.mp4


https://user-images.githubusercontent.com/79500509/228144593-cbcd5844-c2aa-4d5d-b114-e94571883b95.mp4


https://user-images.githubusercontent.com/79500509/228144620-4cf9adbe-b17b-4a78-9fc9-e6d3eed4f50e.mp4
