### ISSUE TITLE
verifier: Vivo Y73 displayed failed to transfer message when clicked on qr code option and wallet : Vivo Y73 displayed failed to transfer message  after qr code scan

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#671]
**Describe the bug**
Vivo Y73 displayed failed to transfer message as verifier and also as wallet.

**To Reproduce**

1. open scanner on wallet 
2. open qr code in verifier
3. scan the qr code from the wallet and select VC and share

**Expected behavior**
Sharing should work with all the attempts

**Actual behavior**
**Device combination 1**
- Wallet Device: Redmi note 10 lite	 | Android 10 BLE 5.0
- Verifier Device: vivo Y73 | Android 12 BLE 5.0

**Device combination 2**
Verifier: Vivo Y73 | Android 12 BLE 5.0
Wallet: Redmi K20 pro | Android 11 BLE 5.0

1. Sharing worked for multiple attempt 
2. restarted wallet and shared VC - overall 20 attempt of VC was successful
3. now restart the verifier - click on qr code option - displayed the error 
![image](https://user-images.githubusercontent.com/79500509/227858014-570b9d52-fd92-410e-a6a1-1364bfa1fc42.png)
The above error was persistent with multiple try

-------------------------------------------------------------------------------------------------------------
4. Now , change the roles i.e

- Wallet Device: vivo Y73 | Android 12 BLE 5.0
- Verifier Device: Redmi note 10 lite | Android 10 BLE 5.0

5. open the scanner in wallet 
6. open qr code in verifier device
7. scan the qr code -displayed the error.

https://user-images.githubusercontent.com/79500509/227859814-3eb69719-ebfd-4c3e-91d8-aef71b273402.mp4

The above error was persistent with multiple try

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/79500509/227860303-b7cf3112-f7f6-4869-8956-49b3d896363c.png)

**Environment details (please complete the following information):**

- Inji app version: 
![image](https://user-images.githubusercontent.com/79500509/227860303-b7cf3112-f7f6-4869-8956-49b3d896363c.png)

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
Issue occurred on both after interchanging the roles

**Logs of wallet and verifier:**

[logshare.txt](https://github.com/mosip/inji/files/11075446/logshare.txt)

**NOTE**: As a work around reinstalled the app in Vivo Y73 but still issue is happening intermittently.

**Comment by Anushree09-N** [comment]
This issue may be related to https://github.com/mosip/inji/issues/515 as per the comments in #515 right now the pop up will be displayed instead of application crashing.
Ravi, Krishna. please check and confirm

**Comment by ravikp** [comment]
It is a generic error code, and they aren't related to application crash.

**Comment by Anuranjan14** [comment]
once the failed to transfer pop up came up, we are unable to proceed further even after killing the app or restarting the device. either generic error code or application crash, the user should not be blocked and after relaunching the app, it should start working.
@gsasikumar Need your inputs on this issue

**Comment by Anushree09-N** [comment]
We had a inference that crashing issue was gracefully handled with error message projection. As per @ravikp above error message will be displayed for various other reasons. @ravikp can we have the list of scenario that are meant to have above error?

As discussed over Inji triage call changing the word "crash" in above bug.
CC @Raginikrishnamurthy @lsivanand

**Comment by krishnakumar4a4** [comment]
@Anushree09-N 
Thanks for updating the title. 
As requested, the error scenarios are all documented here - https://docs.mosip.io/inji/tuvali#error-scenarios

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed on Jira https://mosip.atlassian.net/browse/INJI-45, hence closing on Github.
