### ISSUE TITLE
Android - We are not able to go back from the OTP screen while genrating VID from AID

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#674]
**Describe the bug**
We are not able to go back from the OTP screen while generating VID from AID

**To Reproduce**
1. Unlock the app
2. click on ADD ID button on the home page
3. click on "Don't have your UIN/VID? Get it here " link.
4. Enter AID
5. click on Get UIN/VID button
6. While entering OTP, click on back

**Expected behavior**
We should able to go back  from the OTP screen

**Actual behavior**
The app got frozen once we click on the back button, the workaround is only to kill the app after this 

**Screenshots**
https://user-images.githubusercontent.com/102220709/228157438-1ba13be2-cec8-4fa8-aeb8-76815c040e63.mp4

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/228156659-1b0813af-67c2-4b0b-91d8-2209365e6e80.png)

**Tested on :**
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/afd832ce-d954-4a45-82ea-fbea28a572d1)
