### ISSUE TITLE
IOS - App is getting crashed when we try to go back from the OTP screen while genrating VID from AID

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#675]
**Describe the bug**
The app is getting crashed when we try to go back from the OTP screen while generating VID from AID

**To Reproduce**
1. Unlock the app
2. click on ADD ID button on the home page
3. click on "Don't have your UIN/VID? Get it here " link.
4. Enter AID
5. click on Get UIN/VID button
6. While entering OTP, click on back

**Expected behavior**
We should able to go back from the OTP screen

**Actual behavior**
The app is getting crashed as shown in the below video 

**Screenshots**
https://user-images.githubusercontent.com/102220709/228160481-fc8d37c5-37ed-4901-8802-ef32ee231aea.MOV

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/228159370-4685c9fd-6b4a-46c4-8298-b230df35bcd1.png)

**Smartphone :**
Phone make/model: Iphone 8
OS: ios 16
BLE version : 5.0
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : testflight 0.4.1 (32)

**Comment by Sujithbn** [comment]
@santhoshsunder : Please add the logs here for the developer to troubleshoot further on this issue

**Comment by santhoshsunder** [comment]
@krishnakumar4a4 mono has provided these logs, please take a look
[testflight_feedback-4.zip](https://github.com/mosip/inji/files/11099654/testflight_feedback-4.zip)

**Comment by PuBHARGAVI** [comment]
Made the changes, if we go back from OTP screen to AID screen the AID screen is shown on both Android and IOS without crashing and the whole flow of generating UIN using AID is working without any issues
**AID screen:**
<img width="347" alt="Screenshot 2023-04-03 at 10 51 58 AM" src="https://user-images.githubusercontent.com/46226958/229419519-fe311338-0e65-4a6c-9ca8-a82e6e88fe86.png">
**Click on Get UIN/VID it opens OTP screen:**
<img width="269" alt="Screenshot 2023-04-03 at 10 54 18 AM" src="https://user-images.githubusercontent.com/46226958/229419606-d38168b1-8056-447a-adfc-8a096db7aa8c.png">
**Go back from OTP screen to AID screen:**
<img width="270" alt="Screenshot 2023-04-03 at 10 54 32 AM" src="https://user-images.githubusercontent.com/46226958/229419854-6a983cb9-b5cb-428f-83d6-43dcb990d490.png">
**Click on Get UIN/VID again and this time enter the OTP, UIN screen will be displayed:**
<img width="268" alt="Screenshot 2023-04-03 at 10 54 54 AM" src="https://user-images.githubusercontent.com/46226958/229420073-1ef4cca5-bc1b-48ff-a10c-bdf906391829.png">
**Click on generate My card and the card will be downloaded:**
<img width="268" alt="Screenshot 2023-04-03 at 10 53 39 AM" src="https://user-images.githubusercontent.com/46226958/229420225-80ced38c-f870-48f8-81dc-64606ded8ea2.png">

**Comment by vharsh** [comment]
Verified the same with `ravikp/inji/develop` with @PuBHARGAVI on iPhone 7(iOS 15.x)

Screenshots attached from `Get UIN/VID button is tapped` and the cross button is tapped later.



![IMG_0069](https://user-images.githubusercontent.com/9304050/229448303-659b939e-12d6-40a7-b03b-d50782344b73.PNG)

![IMG_0070](https://user-images.githubusercontent.com/9304050/229448315-c9f8eff7-5a7a-41c5-85c3-9eb3a4c39962.PNG)

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed in jira https://mosip.atlassian.net/browse/INJI-46, hence closing on Git.
