### ISSUE TITLE
The VC card activation ellipsis is not pointing to the expected page 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#677]
**Describe the bug**
The VC card activation ellipsis is not pointing to the expected page 

**To Reproduce**
1. Authenticate the app and enter inside
2. Download a VC 
3. click on ADD ID and download a VC

**Expected behavior**
As per the story, it should point to the screenshot mentioned below 
![image](https://user-images.githubusercontent.com/102220709/228185672-149337d6-a74c-48b1-9c23-5d6c548be442.png)

**Actual behavior**
Clicking on it takes inside the detailed view as shown in the below video 

**Screenshots**
https://user-images.githubusercontent.com/102220709/228190669-add36052-170f-44b0-89a8-400d1bc14cd0.mp4

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/228190748-122457c2-35d0-4ca8-8c33-2138ead1923c.png)

**Tested on :**
This is occurring on both android and ios 
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

Wire frame: https://xd.adobe.com/view/d1300570-ca38-41d1-a061-48a6950addf9-8463/screen/547376f4-1348-4d3e-a506-9680477d9b28/
story id #278

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/99675a9d-23bb-492d-8848-dce9da8379f7)
