### ISSUE TITLE
Android - Unable to login into QR code login from inji in specific devices 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#678]
**Describe the bug**
Unable to login into QR code login from inji in specific devices 

**To Reproduce**
Prerequisite: Download VC and have it binded 

1. Authenticate the app and get into it
2. Go to the scanner page
3. Scan the IDP portal

**Expected behavior**
We should be able login into and IDP portal on all devices successfully 

**Actual behavior**
We unable to login into IDP portal in specific devices, its projecting error

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/228222167-ea54e18a-6562-4ec4-8134-64362aabe90b.png)

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/228222232-d8819465-9365-4492-ac67-75d25bac92d6.png)

**Tested on :**
Phone make/model: Redmi 6A
OS: Android 9
BLE version : 4.2

Phone make/model: Samsung A03 core
OS: Android 11
BLE version : 4.2

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26851

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/a83d79f3-c5b4-4e31-b285-e71ed2b61bd1)
