### ISSUE TITLE
Getting error message in scanner page

### ISSUE THREAD

**Issue by damodarguru** [mosip/inji#679]
**Describe the bug**
Getting error message in scanner page and camera not opening

**To Reproduce**
1. Open Resident application.
2. Unlock application.
3. Immediately open QR scanner after unlocking the application. 
4. Press QR scanner button multiple times still QR scanner open.

**Expected behavior**
QR scanner should be open without any interrupt.

**Actual behavior**
We getting invalid error message as shown in the below screenshot, camera is opening after sometime.

**Screenshots**
https://user-images.githubusercontent.com/124761463/228228590-cea6373f-c4a2-430d-8901-5d30216674ef.mp4
![1Screenshot_2023-03-25-21-45-35-561_io mosip residentapp](https://user-images.githubusercontent.com/124761463/228229419-a560ebdd-213f-4cf6-95e8-5ba4e29e24af.jpg)
![2Screenshot_2023-03-28-17-27-23-960_io mosip residentapp](https://user-images.githubusercontent.com/124761463/228229588-7e9ad231-531c-48e4-a0de-86114413db8d.jpg)

**Smartphone (please complete the following information):**
This issue occurring on iOS and android.
Phone make/model: Redmi 6A
Android Version: 9
BLE version : 4.2
APP link : https://github.com/mosip/inji/actions/runs/4511525622
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/3fa9f691-ad89-474a-b985-f8de7e8b8a4d)
