### ISSUE TITLE
Android - Two specific android devices not connected in specific roles 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#683]
**Describe the bug**
Two specific android devices not connected in specific roles for some time

**To Reproduce**
Prerequisite: download VC in the wallet 

1. Open scaner in verifier 
2. Scan the QR code from the wallet 

**Expected behavior**
Both phones should able to connect to each other

**Actual behavior**
The two phones is not connected atall, once the wallets app is restarted its started working again 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/228261662-77133f85-6b65-4485-bde8-1bc174a61bda.png)

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/228261731-eeb2106e-37f1-4961-bc39-282f3723d2b7.png)

**Smartphone :**
Wallet :
device : 7A
BLE version : 4.2
OS version : Android 10

Verifier :
device : Redmi 6A
BLE version : 4.2
OS version : Android 9

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511543895

**Device logs:**
[redmi6A.zip](https://github.com/mosip/inji/files/11090493/redmi6A.zip)
[redmi7A.zip](https://github.com/mosip/inji/files/11090494/redmi7A.zip)

**Comment by Kratitva** [comment]
This issue is now tracked in JIRA: https://mosip.atlassian.net/browse/INJI-70

**Comment by Raginikrishnamurthy** [comment]
Issue verified and closed on jira https://mosip.atlassian.net/browse/INJI-70, hence closing the same on git.
