### ISSUE TITLE
iOS: cursor and keypad does not show up once the user navigates back to biometric to passcode page

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#684]
**Describe the bug**
cursor and keypad does not show up once the user navigates back to biometric to passcode page

**To Reproduce**

1. Install the app and click on Get Started button
2. Choose "unlock with biometrics".
3. Authenticate using fingerprint / face ID base device settings.
4. Otp is prompted to enter -> where cursor or keypad is automatically shown to user
5. Now navigate back to previous screen i.e app unlock screen.
6. and again navigate back to Otp screen

**Expected behavior**
cursor and keypad should show up whenever user enters the Otp screen irrespective of attempts. 

**Actual behavior**
cursor and keypad does not show up once the user navigates back to biometric to passcode page

**Screenshots**

https://user-images.githubusercontent.com/79500509/228442485-a700f19f-c0c8-4f24-8a90-5f98b68cb0a8.MP4

![IMG20230329115048](https://user-images.githubusercontent.com/79500509/228444203-d1bf7287-3f73-4391-9102-e1baa3869791.jpg)

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**

iphone 11 | iPhone OS version: 15, BLE 5.0

**Environment details:**
- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Additional context**
The issue is common across all the devices of iOS

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/384ce03b-8f2a-4992-b585-e249c30038aa)
