### ISSUE TITLE
iOS: Able to login to eSignet health portal using old binded credentials

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#685]
**Describe the bug**
Able to login using old binded credentials.

**To Reproduce**
**Prerequisite:** Download VC on iphone 11 & iphone 8

1. bind the VC using VID in iPhone 11
2. now bind VC  for same VID in iPhone 8
3. login to eSignet health portal using iPhone 8 -> Login is successful.
4. again to eSignet health portal using iPhone 11 

**Expected behavior**
Login on iPhone 11 should fail by displayed error message as on iPhone 11 binding of VC was done before iPhone 8.

**Actual behavior**
Able to login to eSignet portal using old binded VC i.e on iPhone 11

**Screenshots**

![IMG20230329122645](https://user-images.githubusercontent.com/79500509/228452649-a16e6b40-be77-4fdb-9744-1b37c41eed92.jpg)

![IMG20230329122719](https://user-images.githubusercontent.com/79500509/228452763-b9f475f6-f797-4012-9741-97ed60f4e321.jpg)

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**
Device 1 : iphone 11 | iPhone 15 BLE 5.0
Device 2 : iphone 8 | iphone 16 BLE 5.0

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Comment by dhivya0413** [comment]
Tried to reproduce the issue with iPhone 8 and iPhone 11. However, I couldn't able to reproduce it. 

It works as expected - Old binded vc not logging in esignet health portal 

![Image_20230405_122234_864](https://user-images.githubusercontent.com/120356578/230004229-64d5e720-812b-4232-b6fe-666473d6fecc.png)

cc @krishnakumar4a4 @ravikp

**Comment by dhivya0413** [comment]
@Anushree09-N @santhoshsunder 

I have tested in iPhone 11, XR and 14 Promax 5 times and couldn't able to reproduce the issue. 

Test details:

Test flight build: 0.4.1(32)
QA env: 1201 qa / Purple theme


![IMG_0199](https://user-images.githubusercontent.com/120356578/231159289-10a135e4-6f23-45bd-bf24-52c8bf0484ee.PNG)

**Comment by Raginikrishnamurthy** [comment]
This issue has been verified and closed in jira https://mosip.atlassian.net/browse/INJI-49 , hence closing the same on git.
