### ISSUE TITLE
iOS: Unable to login to eSignet health portal using iPhone 7

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#686]
**Describe the bug**
 Unable to login to eSignet health portal using iPhone 7

**To Reproduce**
**Prerequisite:** Download VC and bind VC in iPhone 7

1. Open the scanner in iPhone 7
2. Scan eSignet health portal qr code
3. perform face and give consent by selecting attributes in consent screen 
4. click on Allow button in consent screen

**Expected behavior**
Login should be successful and eSignet health portal should project the data on the browser screen that were select by resident to share details.

**Actual behavior**
Displayed a error message after giving a consent "Something went wrong please try again after sometimes". 

**Screenshots**

![IMG20230329124347](https://user-images.githubusercontent.com/79500509/228459703-4d81f39f-5a2f-4b08-9c7e-f6f7ec184491.jpg)

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**
iphone 7 | iphone 15.6 BLE 4.2

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Additional context**
Android bug: https://github.com/mosip/inji/issues/678

**Comment by vharsh** [comment]
I'm able to login via Inji against QA1201 setup and use the health-services UI. But with dev2 setup I'm getting IDA-KBT-003 error from https://api.dev2.mosip.net/v1/esignet/linked-authorization/authenticate . Can someone confirm if the dev setups' authentication service is up and functional and is configured correctly ?

**Comment by vharsh** [comment]
Re-iterating the above point/comment. This scenario was tested and found to be working correctly on the QA1201 environment as per expectation.

**Comment by Raginikrishnamurthy** [comment]
This issue has been verified and closed in jira https://mosip.atlassian.net/browse/INJI-48 , hence closing the same on git.
