### ISSUE TITLE
iOS : Inji passcode fallback mechanism when biometric authentication fails is no where used

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#687]
**Describe the bug**
 Inji passcode fallback mechanism when biometric authentication fails is no where used

**To Reproduce**
**Prerequisite** biometric should be set in device setting page

1. Install the app 
2. click on Get started button
3. Go with "Use biometrics " option 
4. toast is prompted asking to authenticate the biometrics , Authenticate
5. Otp is prompted to set as a fall back mechanism
6. Enter 6 digit otp and confirm the Otp by entering same digit in next screen
7. Now user will be taken to HOME page.
8. Navigate to settings page
9. click on logout
10. Again open the app 
11. Biometrics is ask to unlock the inji app.
12. Fail the biometric unlock by placing incorrect finger for 2/3 attempts.

**Expected behavior**
When biometric unlock method fails the app should ask resident to use passcode that is set in the app while enabling biometrics.

**Actual behavior**
When biometrics unlock fails the app prompts to enter device passcode instead of app passcode.

**Screenshots**

https://user-images.githubusercontent.com/124761463/228505448-b22ebab0-323a-468d-9dbd-f528e6a7c441.MP4

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**

iphone 8 | iPhone 16 |BLE 5.0

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

Refer to the story for details: https://github.com/mosip/inji/issues/44

**Comment by hegdenitin** [comment]
Moved this bug to JIRA, Hence closing the bug from here .
JIRA Link: https://mosip.atlassian.net/browse/INJIMOB-1741
