### ISSUE TITLE
iOS : When downloading activated VC on same device, VC should be downloaded with binded details

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#689]
**Describe the bug**
When downloading activated VC on same device, VC should be downloaded with binded details

**To Reproduce**
**prerequisite**
 1. VC is downloaded in inji app (VID)
 2. eSigned is configured and has an option to login with Inji

**steps:** 

 1. unlock the app
 2. click on activate VC for online login link
 4. Otp is prompted to enter
 5. enter received Otp -> Otp matched
 6. VC activation is successful
 7. click on Add ID Enter VID number for which VC activation was successful.
 8. Download the VC

**Expected behavior**
VC should be downloaded and should have binded details with it , as binding was done for same ID / VID and on same device

**Actual behavior**
VC is downloaded and resident is allowed to bind the VC though same ID was binded on the device in last attempt.

**Screenshots**

https://user-images.githubusercontent.com/124761463/228561261-fafe7258-dc91-44bd-bac6-07e2f1dfbaf9.mp4

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**

iphone 8 | iPhone 16 BLE 5.0

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Comment by hegdenitin** [comment]
Moved this bug to JIRA, Hence closing the bug from here .
JIRA Link: https://mosip.atlassian.net/browse/INJIMOB-1740
