### ISSUE TITLE
iOS : Get started button is not aligned properly

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#690]
**Describe the bug**
Get started button is not aligned properly

**To Reproduce**

1. Install the app
2. unlock the app by setting passcode / biometrics
3. Navigate to last screen of User guide

**Expected behavior**
Get started and AddID button should be aligned properly

**Actual behavior**
Get started and AddID button has doubly line in the bottom of the button

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/228536704-5785d27b-5688-4a94-b3db-1803debce0cf.png)
![IMG_0218](https://user-images.githubusercontent.com/124761463/228564040-52d712ee-8653-4603-9827-dced08289645.PNG)

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**

iphone 8 | iphone 16 BLE 5.0

**Note**:  the issue is replicable in all iOS devices

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A

**Logs of wallet and verifier:**
N/A

**Additional context**
The issue is applicable to both orange and purple theme

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![Uploading image.png…]()
