### ISSUE TITLE
iOS: spelling mistake in the tips/user guide note

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#691]
**Describe the bug**
spelling mistake in the tips/user guide note

**To Reproduce**

- Install the APK and the open it
- Add the Authentication method
- Head to the home page
- Once the tip page pop-up, Navigate to last slide in the user guide pop up

**Expected behavior**
Spelling should be corrected to "swiftly".

**Actual behavior**
The word swiftly is spelled wrongly in the tips note in the first install

**Screenshots**

![image](https://user-images.githubusercontent.com/79500509/228539504-72b8fa6b-7707-44a6-9a39-d2966dea1642.png)
![IMG_0218](https://user-images.githubusercontent.com/124761463/228564636-ec0cb072-608d-4451-af29-f0b38314026e.PNG)

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**

 iphone 8	| iphone 16 BLE 5.0

Note: the issue is replicable in all the devices.

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Additional context**
The issue is applicable to both Orange and purple theme

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/af770444-4f05-41cc-bfa1-0fa0a2d1d511)
