### ISSUE TITLE
iOS : Revoke ID option should be removed from detail view of the card.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#694]
**Describe the bug**
Revoke ID option should be removed from detail view of the card.

**To Reproduce**

1. Unlock the app
2. Download VC
3. View the VC in detail view
4. click on ellipses 

**Expected behavior**
Revoke ID option in detail view of the card should be removed / hidden as feature no longer available for current release.

**Actual behavior**
Revoke ID option is still available

**Screenshots**

![image](https://user-images.githubusercontent.com/79500509/228546091-bc8a1188-6498-4618-8a7d-049ce2ddda72.png)

**Add the screenshot of the profile page with commit id**

![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

**Smartphone (please complete the following information):**

 iphone 11 | iPhone 15 BLE 5.0

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![Uploading image.png…]()
