### ISSUE TITLE
Android - Devices getting disconnected while face auth

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#697]
**Describe the bug**
Devices getting disconnected while face auth intermittently 

**To Reproduce**
Prerequisite: have VC downloaded in the wallet

1. open the scanner on the wallet
2. open qr code in the verifier
3. Select a VC in your wallet and click on face auth
4. perform face auth

**Expected behavior**
The transfer should work properly without any interruption 

**Actual behavior**
The devices go disconnected, this issue I faced intermittently for 3 times in 25 attempts 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/228813839-7200712c-da91-4816-b116-3595f63ecba0.png) 

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/228814568-a614308c-d42a-4b53-b406-6a6999ff0aea.png)

**Smartphone:**

Wallet :
device : 7A
BLE version : 4.2
OS version : Android 10

Verifier :
device : Samsung A03
BLE version : 4.2
OS version : Android 11

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4555460456

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/8203df6d-12c0-4a10-a965-3962c6939be5)
