### ISSUE TITLE
iOS: Get started word in the button is repetitive

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#701]
**Describe the bug**
Get started word in the button is repetitive

**To Reproduce**

1. Install the app and open- button displayed "Get started".
2. set passcode and unlock the app
3. swipe to last slide in user guide. -button displayed "Get started and Add ID".

**Expected behavior**
Get started word should be removed in the User guide slide.

**Actual behavior**
 Get start button is shown to user in Login screen and same is repetitive in User guide after login.

**Screenshots**

https://user-images.githubusercontent.com/124761463/229482568-a77c26b9-c15d-4e49-95e6-abf15ce93355.MP4

![image](https://user-images.githubusercontent.com/124761463/229482782-6419a0db-25e6-401d-af91-141496276a02.png)

**Smartphone (please complete the following information):**

 iphone 8| iPhone 16 BLE 5.0

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot
![image](https://github.com/mosip/inji/assets/88436594/abfd3e8c-1842-4973-be5a-22d167fbb433)
