### ISSUE TITLE
Error message displayed twice one on pop up and other one in the bottom of the page

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#703]
**Describe the bug**
Error message displayed twice one on pop up and other one in the bottom of the page

**To Reproduce**
Prerequisite:  VC downloaded .

1. Unlock the app 
2. Activate the VC card for login in offline.

**Expected behavior**
Error message which is being displayed in the bottom screen should be removed

**Actual behavior**
Error message displayed twice one on pop up and other one in the bottom of the page

**Screenshots**
![image](https://user-images.githubusercontent.com/124761463/229497980-edd2c9be-a162-4ccb-90ff-2807cac9a781.png)

![image](https://user-images.githubusercontent.com/124761463/229498082-e1c8ce49-a904-4ba5-905b-137efdfa1858.png)

**Smartphone (please complete the following information):**

Vivo Y73 | Android 12 BLE 5.0

- Mimoto version: 1.2.0.1
- MOSIP Version: qa-1201-b2.mosip.net

**Where does the issue occur: Wallet/Verifier?**
N/A
**Logs of wallet and verifier:**
N/A

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/a6614092-b62d-4597-a40b-300cfc10ef1a)
