### ISSUE TITLE
iOS: Background app is refreshing after Bluetooth permission is enabled.

### ISSUE THREAD

**Issue by damodarguru** [mosip/inji#707]
**Describe the bug**
Background app is refreshing after Bluetooth permission is enabled.

**To Reproduce**

1. In settings open 'Mosip Resident App'.
2. Disable the Bluetooth toggle.
3. Now open QR scanner of MOSIP Resident APP
4. It asking for enable Bluetooth. 
5. Run the application in background now go through settings enable Bluetooth toggle.
6. Now again open Mosip Resident app.

**Expected behavior**
Background app is refreshing after Bluetooth permission is enabled.

**Actual behavior**
Application should be open without refreshing after Bluetooth permission is enabled.

**Screenshots**

https://user-images.githubusercontent.com/124761463/231172510-a702c974-e847-406c-a7b4-b7221faf4243.mp4

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/124761463/231173318-1829735a-6b83-4bf3-a88a-cc44cd735249.png)

**Smartphone (please complete the following information):**

  -  Device: iPhone 8
  - OS: 16.0
  - BLE version : 5.0
  - TestFlight Version: 0.4.1(39)

**Where does the issue occur: Wallet/Verifier?**

**Logs of wallet and verifier:**

**Additional context**

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/b9fa3d07-89d7-4f95-b845-b897dd322d7f)
