### ISSUE TITLE
VC sharing issues

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#76]
**Describe the bugs**
1. The QR code on the requesting device (iOS) is not displayed during the process of sharing ID. (**Android >> iOS**)
2. The QR code on the requesting device (android) is not displayed during the process of sharing ID. (**Android >> Android**)
3. After rejecting, receiving device (iOS) did not direct me back to QR code after dismissing toast. Also gets stuck in Incoming ID page after dismissing toast (**Android >> iOS**)

**To Reproduce bugs**

**BUG 1**
1. On device A (iOS), go to REQUEST 
2. On device B (android), go to SCAN 
3. Scan QR code using device B
4. Device A should display “Connected to device. Waiting for VC…”. Device B should display “Sharing VC” card
5. See error in device A: QR code not displayed

**BUG 2**
1. On device A, go to REQUEST 
2. On device B, go to SCAN 
3. Scan QR code using device B
4. Device A should display “Connected to device. Waiting for VC…”. Device B should display “Sharing VC” card
5. See error in device A: QR code not displayed

**BUG 3**
Steps:
1. On device A (iOS), go to REQUEST 
2. On device B (android), go to SCAN 
3. Scan QR code using device B
4. Device A should display “Connected to device. Waiting for VC…”. Device B should display “Sharing VC” card
5.  Click “Accept request and choose VC”
6. Device B should display card with list of possible VC to share. No VC should be preselected. “Share” button should only be activated when a VC has been selected. Name of receiving device should be displayed.
7. On device B, select VC to share and click “Share”
8. On device B, text “Sharing…” should be displayed. On device A, “Incoming VC” card should be displayed
9. On device A, click “Reject”
10. See Error

**Release Build**
iOS build: **Version 0.4.0 (1.0.0)**
Android build: **0.4.0-beta.1**

**Comment by jannahadlaon** [comment]
Here are the results after testing @pmigueld 

Bug 1 - issue it still present 
Bug 2 - issue it still present
Bug 3 - issue it still present
Bug 4 - Works as expected
Bug 6 - issue it still present

I also deleted Bug 5 since it's a duplicate of Bug 3.

**Comment by jannahadlaon** [comment]
@pmigueld a separate ticket was created for Bug 1 and Bug 6. 
Here's the link to the ticket: [https://github.com/mosip/inji/issues/86](url)

**Comment by jannahadlaon** [comment]
Tested on:
iOS build: version 0.4.0 (4)
Android build: version 0.4.0-beta.4

**WORKS AS EXPECTED**

**Comment by kyanthony** [comment]
To hide the QR code whenever a connection has been established

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
