### ISSUE TITLE
Toast is not displayed informing users to enable bluetooth (iOS)

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#78]
**Describe the bug**
Toast is not displayed informing users to enable Bluetooth
“MOSIP Resident App is asking to turn on Bluetooth” with options “Deny” and “Allow”

**To Reproduce**
**Prerequisite** (requesting device: iOS): Bluetooth disabled
1. Go to third icon from left
3. See error

**iOS release build**
Version 0.4.0 (1.0.0)

**Comment by pmigueld** [comment]
Note that the library we use does not support automatically enabling bluetooth from the app (could be a limitation in iOS). The fix adds a button to go to the settings so the user can enable bluetooth if they miss the dialog the first time:

![image](https://user-images.githubusercontent.com/1631922/185854688-b4f529d1-0d3d-4850-b0e5-55e0ddf3bb34.png)

**Comment by jannahadlaon** [comment]
- Toast did not appear. 
- Bluetooth is already enabled after going to settings (Press on **Go to settings**)
- Disabling and enabling Bluetooth on the settings restarts app
- QR code still won't appear after enabling Bluetooth in the settings

**Recording**
https://user-images.githubusercontent.com/102940764/186325814-407146e6-bcc5-439c-9c13-c95121eaa4b4.mp4

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
