### ISSUE TITLE
"network request failed" message is still showing after the network is connected when we try to add id and when otp is provided

### ISSUE THREAD

**Issue by rakhimosip** [mosip/inji#79]
**Describe the bug**
"network request failed" message is still showing after the network is connected when we try to add id and when otp is provided

**To Reproduce**

1. turn off the internet connection in your mobile
2. open the app and authenticate it 
3. click on add id
4. enter an valid uin and click on generate
5. it will show a message as “network request failed”
6. turn on the internet connection in your mobile
7. click on add id and enter otp

**Current behavior**
the “network request failed” is still showing in mobile app

**Expected behavior**
the “network request failed” should not be showing in the previous screen and vc should be generated

**Video**
https://user-images.githubusercontent.com/86289097/185603034-edeec75f-6d5f-4a17-abd3-8ee68910bc83.mp4

**Smartphone (please complete the following information):**

- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
apk details 0.2.2 for 1.1.5  [Release 0.2.2 · idpass/inji](https://github.com/idpass/inji/releases/tag/0.2.2)
ENV : qa3.mosip.net

**Comment by santhoshsunder** [comment]
![image](https://user-images.githubusercontent.com/102220709/188603867-1485e97e-f94d-42bb-9f86-77df637fc657.png)

**Comment by santhoshsunder** [comment]
comment by @rakhimosip : 
@santhoshsunder  is this issue still happening?

**Comment by santhoshsunder** [comment]
comment by @Anushree09-N : 
@rakhimosip Re-tested the above scenario again , we are still able to replicate the issue.

**Comment by santhoshsunder** [comment]
Comment by @Anushree09-N : 
@rakhimosip Re-tested the above scenario again , we are still able to replicate the issue.

**Comment by Anil-kumar-Majji** [comment]
@rakhimosip @santhoshsunder I completed resolving this bug. There is the remainder of raising PR.

**Comment by santhoshsunder** [comment]
Verified this issue in QA5 env, issue is not observed any more, we are able to download credentials now, hense closing the jira

**Smartphone :**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
APP link; https://mosip.atlassian.net/browse/DSD-1816
