### ISSUE TITLE
The error message "connection interrupted" should be revised to more user friendly message

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#87]
**Describe the bug**
The error message "connection interrupted" should be revised to more user friendly message

**To Reproduce**
1. Establish a connection between resident and relying party
2. Resident chooses the VC to share and clicks on "Share button".
3. The requesting relying party thens clicks on "Reject button".

**Current behavior**
Displays "The Connection was interrupted, Please try again" in relying party mobile 

**Expected behavior**
App should display a user friendly message.

**Smartphone (please complete the following information):**

- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Comment by santhoshsunder** [comment]
![image](https://user-images.githubusercontent.com/102220709/188604791-16a577f4-e3c5-41d4-a767-41f2ba021c63.png)

**Comment by kyanthony** [comment]
Please provide the new error message @Sujithbn @Anushree09-N

**Comment by Sujithbn** [comment]
@rakhimosip Please share the error message

**Comment by rakhimosip** [comment]
@Anushree09-N @Sujithbn a user-friendly message is being displayed now. Tested on QA5.

**Comment by Raginikrishnamurthy** [comment]
@rakhimosip Please elaborate on the user friendly message that should be displayed to update the test cases and verify the same.

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
