### ISSUE TITLE
Mobile app session should get expire ,if the app is opened longer time.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#90]
**Describe the bug**
Mobile app session should get expired, if the app is opened for a longer time and user tries to login again with the PIN to generate VC by using UIN/VID.

**Current behaviour**
Session not getting expired

**Expected behaviour**
It should end up the active session and try to ask kindly re login.
Actual: Session wont get expire.

**Smartphone (please complete the following information):**

- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Comment by santhoshsunder** [comment]
![image](https://user-images.githubusercontent.com/102220709/188607502-178cdd94-1e3b-4d7b-bdc7-6ab465275a54.png)

The link attached in the image : https://github.com/idpass/inji/issues/138

**Comment by hegdenitin** [comment]
Moved  this bug to JIRA, Hence closing the bug from here .
JIRA Link: https://mosip.atlassian.net/browse/INJIMOB-1741
