### ISSUE TITLE
The error message when revoked VID used should be revised

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#92]
**Describe the bug**
The error message when revoked VID used should be revised

**To Reproduce**
1. Request credential with VID that is revoked.

**Current behaviour**
Displayed error message "Invalid id::VID is REVOKED".

**Expected behaviour**
the error message should be "VID is revoked".

**Screenshots**
![WhatsApp Image 2022-04-07 at 3 31 41 PM](https://user-images.githubusercontent.com/79500509/188359698-66540c22-11ea-44e9-b349-ecfa6117b361.jpeg)

**Smartphone (please complete the following information):**
- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
Error message should not contain special characters and uppercase.

**Comment by santhoshsunder** [comment]
![image](https://user-images.githubusercontent.com/102220709/188609397-fc81d6f0-a04f-42e6-a016-45178ce798bd.png)

The link attached in the image : https://github.com/idpass/inji/issues/154

**Comment by santhoshsunder** [comment]
The user is not allowed to use the revoked VID, downloading VC is blocked for revoked vid, hence closing the bug, commit id mentioned below 
![image](https://github.com/mosip/inji/assets/102220709/1c912ece-adcb-4567-a895-4623278b522c)
