### ISSUE TITLE
Able to get VC when dropdown selected as UIN and input data is VID number and vice-versa

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#98]
**Describe the bug**
Able to get VC when dropdown selected as UIN and input data is VID number and vice-versa

**To Reproduce**
1. Open the app and authenticate it
2. From the home screen clikck on generate VC
3. Select the dropdown as UIN and enter the value of VID
4. Click on genrate VC

**Current behavior**
It is allowing us to the OTP page and aloowing to genrate VC, this is issue is happening in vice-versa senario also, while selecting VID dropdown and entering UIN value it is allowing us to genrate VC.

**Expected behavior**
It should not allow us to genrate vc and need to show a error message as invalid UIN

**Screenshots**

https://user-images.githubusercontent.com/79500509/188789793-d316c5d2-454b-4bea-b1d3-d89f656c90d7.mp4

https://user-images.githubusercontent.com/79500509/188789799-2f8a59fe-06a5-49db-be00-cc5d3e66aa30.mp4

**Smartphone (please complete the following information):**
- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
Env: qa4.mosip.net

**Comment by krishnakumar4a4** [comment]
Today, we don't see this issue happening. UIN and VID fields have corresponding validations in place.
